#PriorHessian
language: cpp
os: linux

git:
  depth: 3
  quiet: true

branches:
    only:
        - master

matrix:
  include:
      #- env:
          #- MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
          #- OPT_ARMADILLO_INT64=On
      - env:
          - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9 && FC=/usr/bin/gfortran-4.9"
          - OPT_ARMADILLO_INT64=Off
      - env:
          - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9 && FC=gfortran-4.9"
          - OPT_ARMADILLO_INT64=Off
          - FC=gfortran-4.9
      - env:
          - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && FC=gfortran-7"
          - OPT_ARMADILLO_INT64=Off

      ##Documentation build
      - env: DOC=On PDFDOC=On DOPT_ARMADILLO_INT64=Off FC=gfortran
        script: ./scripts/pdf-doc-build.sh -DOPT_ARMADILLO_INT64=${OPT_ARMADILLO_INT64}
        dist: xenial #supports newer doxygen

#MATRIX_EVAL allows CC and CXX to be set before dependencies are installed
before_install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update
    - eval "${MATRIX_EVAL}"

install:
    - if [ "${DOC}" == "On" ]; then sudo apt-get install -y doxygen graphviz; fi
    - if [ "${PDFDOC}" == "On" ]; then sudo apt-get install -y doxygen-latex; fi
    - if [ "${CXX}" == "g++-4.9" ];   then sudo apt-get install -y g++-4.9 gfortran-4.9;   fi
    - if [ "${CXX}" == "g++-5" ];     then sudo apt-get install -y g++-5 gfortran-5;     fi
    - if [ "${CXX}" == "g++-6" ];     then sudo apt-get install -y g++-6 gfortran-6;     fi
    - if [ "${CXX}" == "g++-7" ];     then sudo apt-get install -y g++-7 gfortran-7;     fi
    - if [ "${OPT_ARMADILLO_INT64}" == "Off" ]; then sudo apt-get install -y libblas-dev libblas3 liblapack3 liblapack-dev; fi
    - sudo apt-get install -y libarmadillo-dev libboost-math-dev
    - if [ -z "$DOC" ]; then ./scripts/travis-trusty-install-gtest.sh; fi
    - ls -l /usr/bin/gfortran*

script:
    - ./scripts/travis-build-test.sh

deploy:
    name: Docu-Bot
    provider: pages
    skip-cleanup: true
    github-token: $GH_TRAVISCI_DOCUMENTATION_TOKEN
    keep-history: true
    verbosed: true
    local_dir: _build/documentation/doc/html
    on:
        branch: master
        condition: $DOC = On
