PriorHessian: prior_hessian::MultivariateNormalDist< Ndim > Class Template Reference
prior_hessian::MultivariateNormalDist< Ndim > Class Template Reference
Multivariate Normal distribution.
#include </home/travis/build/markjolah/PriorHessian/include/PriorHessian/MultivariateNormalDist.h>
Public Types
using NdimVecT = arma::Col< double >::fixed< Ndim >
using NdimMatT = arma::Mat< double >::fixed< Ndim, Ndim >
using NparamsVecT = arma::Col< double >::fixed< _num_params >
Public Member Functions
MultivariateNormalDist ()
template<class Vec , class Mat >
MultivariateNormalDist (Vec &&mu, Mat &&sigma)
const NdimVecT & mu () const
const NdimMatT & sigma () const
const NdimMatT & sigma_inv () const
template<class Vec >
void set_mu (Vec &&val)
template<class Mat >
void set_sigma (Mat &&val)
bool operator== (const MultivariateNormalDist< Ndim > &o) const
bool operator!= (const MultivariateNormalDist< Ndim > &o) const
double get_param (int idx) const
NparamsVecT params () const
template<class Vec >
void set_params (const Vec &p)
template<class Vec , class Mat >
void set_params (Vec &&mu, Mat &&sigma)
NdimVecT mean () const
NdimVecT mode () const
template<class Vec >
double cdf (Vec x) const
template<class Vec >
double pdf (const Vec &x) const
template<class Vec >
double llh (const Vec &x) const
template<class Vec >
double rllh (const Vec &x) const
template<class Vec >
NdimVecT grad (const Vec &x) const
template<class Vec >
NdimVecT grad2 (const Vec &x) const
template<class Vec >
NdimMatT hess (const Vec &x) const
template<class Vec , class Vec2 >
void grad_grad2_accumulate (const Vec &x, Vec2 &g, Vec2 &g2) const
template<class Vec , class Vec2 , class Mat >
void grad_hess_accumulate (const Vec &x, Vec2 &g, Mat &hess) const
template<class RngT >
NdimVecT sample (RngT &rng) const
template<class IterT >
void append_params (IterT &params) const
template<class IterT >
void set_params_iter (IterT &params)
template<>
double cdf (Vec x) const
Static Public Member Functions
static constexpr IdxT num_params ()
static constexpr IdxT num_dim ()
static const NdimVecT & lbound ()
static const NdimVecT & ubound ()
template<class Vec >
static bool in_bounds (const Vec &u)
static const StringVecT & param_names ()
static const NparamsVecT & param_lbound ()
static const NparamsVecT & param_ubound ()
template<class Vec >
static bool check_mu (const Vec &mu)
template<class Mat >
static bool check_sigma (const Mat &sigma)
template<class Vec , class Mat >
static bool check_params (const Vec &mu, const Mat &sigma)
template<class Vec >
static bool check_params (const Vec &params)
template<class IterT >
static bool check_params_iter (IterT &params)
Static Protected Member Functions
template<class Vec >
static void check_bounds (const Vec &lbound, const Vec &ubound)
Detailed Description
template<int Ndim>
class prior_hessian::MultivariateNormalDist< Ndim >
Multivariate Normal distribution.
Parameters
Ndim Number of dimensions >=2
Definition at line 20 of file MultivariateNormalDist.h.
Member Typedef Documentation
template<int Ndim> using prior_hessian::MultivariateNormalDist< Ndim >::NdimMatT = arma::Mat<double>::fixed<Ndim,Ndim>
Definition at line 26 of file MultivariateNormalDist.h.
template<int Ndim> using prior_hessian::MultivariateNormalDist< Ndim >::NdimVecT = arma::Col<double>::fixed<Ndim>
Definition at line 25 of file MultivariateNormalDist.h.
template<int Ndim> using prior_hessian::MultivariateNormalDist< Ndim >::NparamsVecT = arma::Col<double>::fixed<_num_params>
Definition at line 27 of file MultivariateNormalDist.h.
Constructor & Destructor Documentation
template<int Ndim> prior_hessian::MultivariateNormalDist< Ndim >::MultivariateNormalDist ()
Definition at line 174 of file MultivariateNormalDist.h.
Referenced by prior_hessian::MultivariateNormalDist< Ndim >::in_bounds().
template<int Ndim> template<class Vec , class Mat > prior_hessian::MultivariateNormalDist< Ndim >::MultivariateNormalDist (Vec && mu, Mat && sigma)
Definition at line 187 of file MultivariateNormalDist.h.
References prior_hessian::MultivariateNormalDist< Ndim >::mu(), prior_hessian::MultivariateNormalDist< Ndim >::set_mu(), prior_hessian::MultivariateNormalDist< Ndim >::set_sigma(), and prior_hessian::MultivariateNormalDist< Ndim >::sigma().
Member Function Documentation
template<int Ndim> template<class IterT > void prior_hessian::MultivariateNormalDist< Ndim >::append_params (IterT & params) const
Referenced by prior_hessian::MultivariateNormalDist< Ndim >::mode().
template<int Ndim> template<class Vec > double prior_hessian::MultivariateNormalDist< Ndim >::cdf (Vec x) const
Definition at line 481 of file MultivariateNormalDist.h.
References prior_hessian::MultivariateNormalDist< Ndim >::mu(), prior_hessian::genz::mvn_cdf_genz(), and prior_hessian::MultivariateNormalDist< Ndim >::sigma().
Referenced by prior_hessian::MultivariateNormalDist< Ndim >::mode().
template<> double prior_hessian::MultivariateNormalDist< 2 >::cdf (Vec x) const
Definition at line 490 of file MultivariateNormalDist.h.
References prior_hessian::MultivariateNormalDist< Ndim >::mu(), prior_hessian::owen_bvn_cdf(), and prior_hessian::MultivariateNormalDist< Ndim >::sigma().
template<class Vec > static void prior_hessian::MultivariateDist::check_bounds (const Vec & lbound, const Vec & ubound) inline static protected inherited
Definition at line 57 of file MultivariateDist.h.
template<int Ndim> template<class Vec > bool prior_hessian::MultivariateNormalDist< Ndim >::check_mu (const Vec & mu) static
Definition at line 196 of file MultivariateNormalDist.h.
Referenced by prior_hessian::MultivariateNormalDist< Ndim >::check_params(), prior_hessian::MultivariateNormalDist< Ndim >::in_bounds(), and prior_hessian::MultivariateNormalDist< Ndim >::set_mu().
template<int Ndim> template<class Vec , class Mat > bool prior_hessian::MultivariateNormalDist< Ndim >::check_params (const Vec & mu, const Mat & sigma) static
Definition at line 213 of file MultivariateNormalDist.h.
References prior_hessian::MultivariateNormalDist< Ndim >::check_mu(), and prior_hessian::MultivariateNormalDist< Ndim >::check_sigma().
Referenced by prior_hessian::MultivariateNormalDist< Ndim >::in_bounds().
template<int Ndim> template<class Vec > bool prior_hessian::MultivariateNormalDist< Ndim >::check_params (const Vec & params) static
Definition at line 220 of file MultivariateNormalDist.h.
References prior_hessian::MultivariateNormalDist< Ndim >::check_mu(), prior_hessian::MultivariateNormalDist< Ndim >::check_sigma(), and prior_hessian::MultivariateNormalDist< Ndim >::num_params().
template<int Ndim> template<class IterT > bool prior_hessian::MultivariateNormalDist< Ndim >::check_params_iter (IterT & params) static
Definition at line 228 of file MultivariateNormalDist.h.
References prior_hessian::MultivariateNormalDist< Ndim >::check_sigma(), and prior_hessian::MultivariateNormalDist< Ndim >::num_params().
Referenced by prior_hessian::MultivariateNormalDist< Ndim >::mode().
template<int Ndim> template<class Mat > bool prior_hessian::MultivariateNormalDist< Ndim >::check_sigma (const Mat & sigma) static
Definition at line 203 of file MultivariateNormalDist.h.
Referenced by prior_hessian::MultivariateNormalDist< Ndim >::check_params(), prior_hessian::MultivariateNormalDist< Ndim >::check_params_iter(), and prior_hessian::MultivariateNormalDist< Ndim >::in_bounds().
template<int Ndim> double prior_hessian::MultivariateNormalDist< Ndim >::get_param (int idx) const
Definition at line 441 of file MultivariateNormalDist.h.
Referenced by prior_hessian::MultivariateNormalDist< Ndim >::operator!=().
template<int Ndim> template<class Vec > MultivariateNormalDist< Ndim >::NdimVecT prior_hessian::MultivariateNormalDist< Ndim >::grad (const Vec & x) const
Definition at line 523 of file MultivariateNormalDist.h.
References prior_hessian::MultivariateNormalDist< Ndim >::mu(), and prior_hessian::MultivariateNormalDist< Ndim >::sigma_inv().
Referenced by prior_hessian::MultivariateNormalDist< Ndim >::mode().
template<int Ndim> template<class Vec > MultivariateNormalDist< Ndim >::NdimVecT prior_hessian::MultivariateNormalDist< Ndim >::grad2 (const Vec & x) const
Definition at line 531 of file MultivariateNormalDist.h.
References prior_hessian::MultivariateNormalDist< Ndim >::sigma_inv().
Referenced by prior_hessian::MultivariateNormalDist< Ndim >::mode().
template<int Ndim> template<class Vec , class Vec2 > void prior_hessian::MultivariateNormalDist< Ndim >::grad_grad2_accumulate (const Vec & x, Vec2 & g, Vec2 & g2) const
Definition at line 546 of file MultivariateNormalDist.h.
References prior_hessian::MultivariateNormalDist< Ndim >::mu(), and prior_hessian::MultivariateNormalDist< Ndim >::sigma_inv().
Referenced by prior_hessian::MultivariateNormalDist< Ndim >::mode().
template<int Ndim> template<class Vec , class Vec2 , class Mat > void prior_hessian::MultivariateNormalDist< Ndim >::grad_hess_accumulate (const Vec & x, Vec2 & g, Mat & hess) const
Definition at line 554 of file MultivariateNormalDist.h.
References prior_hessian::MultivariateNormalDist< Ndim >::mu(), and prior_hessian::MultivariateNormalDist< Ndim >::sigma_inv().
Referenced by prior_hessian::MultivariateNormalDist< Ndim >::mode().
template<int Ndim> template<class Vec > MultivariateNormalDist< Ndim >::NdimMatT prior_hessian::MultivariateNormalDist< Ndim >::hess (const Vec & x) const
Definition at line 539 of file MultivariateNormalDist.h.
References prior_hessian::MultivariateNormalDist< Ndim >::sigma_inv().
Referenced by prior_hessian::MultivariateNormalDist< Ndim >::mode().
template<int Ndim> template<class Vec > static bool prior_hessian::MultivariateNormalDist< Ndim >::in_bounds (const Vec & u) inline static
Definition at line 34 of file MultivariateNormalDist.h.
References prior_hessian::MultivariateNormalDist< Ndim >::check_mu(), prior_hessian::MultivariateNormalDist< Ndim >::check_params(), prior_hessian::MultivariateNormalDist< Ndim >::check_sigma(), prior_hessian::MultivariateNormalDist< Ndim >::lbound(), prior_hessian::MultivariateNormalDist< Ndim >::mu(), prior_hessian::MultivariateNormalDist< Ndim >::MultivariateNormalDist(), prior_hessian::MultivariateNormalDist< Ndim >::operator==(), prior_hessian::MultivariateNormalDist< Ndim >::param_lbound(), prior_hessian::MultivariateNormalDist< Ndim >::param_names(), prior_hessian::MultivariateNormalDist< Ndim >::param_ubound(), prior_hessian::MultivariateNormalDist< Ndim >::params(), prior_hessian::MultivariateNormalDist< Ndim >::set_mu(), prior_hessian::MultivariateNormalDist< Ndim >::set_sigma(), prior_hessian::MultivariateNormalDist< Ndim >::sigma(), prior_hessian::MultivariateNormalDist< Ndim >::sigma_inv(), and prior_hessian::MultivariateNormalDist< Ndim >::ubound().
template<int Ndim> const MultivariateNormalDist< Ndim >::NdimVecT & prior_hessian::MultivariateNormalDist< Ndim >::lbound () static
Definition at line 298 of file MultivariateNormalDist.h.
Referenced by prior_hessian::MultivariateNormalDist< Ndim >::in_bounds(), and prior_hessian::MultivariateNormalDist< Ndim >::num_dim().
template<int Ndim> template<class Vec > double prior_hessian::MultivariateNormalDist< Ndim >::llh (const Vec & x) const
Definition at line 507 of file MultivariateNormalDist.h.
References prior_hessian::MultivariateNormalDist< Ndim >::rllh().
Referenced by prior_hessian::MultivariateNormalDist< Ndim >::mode(), and prior_hessian::MultivariateNormalDist< Ndim >::pdf().
template<int Ndim> NdimVecT prior_hessian::MultivariateNormalDist< Ndim >::mean () const inline
Definition at line 73 of file MultivariateNormalDist.h.
References prior_hessian::MultivariateNormalDist< Ndim >::mu().
template<int Ndim> NdimVecT prior_hessian::MultivariateNormalDist< Ndim >::mode () const inline
Definition at line 74 of file MultivariateNormalDist.h.
References prior_hessian::MultivariateNormalDist< Ndim >::append_params(), prior_hessian::MultivariateNormalDist< Ndim >::cdf(), prior_hessian::MultivariateNormalDist< Ndim >::check_params_iter(), prior_hessian::MultivariateNormalDist< Ndim >::grad(), prior_hessian::MultivariateNormalDist< Ndim >::grad2(), prior_hessian::MultivariateNormalDist< Ndim >::grad_grad2_accumulate(), prior_hessian::MultivariateNormalDist< Ndim >::grad_hess_accumulate(), prior_hessian::MultivariateNormalDist< Ndim >::hess(), prior_hessian::MultivariateNormalDist< Ndim >::llh(), prior_hessian::MultivariateNormalDist< Ndim >::mu(), prior_hessian::MultivariateNormalDist< Ndim >::pdf(), prior_hessian::MultivariateNormalDist< Ndim >::rllh(), prior_hessian::MultivariateNormalDist< Ndim >::sample(), and prior_hessian::MultivariateNormalDist< Ndim >::set_params_iter().
template<int Ndim> const MultivariateNormalDist< Ndim >::NdimVecT & prior_hessian::MultivariateNormalDist< Ndim >::mu () const
Definition at line 376 of file MultivariateNormalDist.h.
Referenced by prior_hessian::MultivariateNormalDist< Ndim >::cdf(), prior_hessian::MultivariateNormalDist< Ndim >::grad(), prior_hessian::MultivariateNormalDist< Ndim >::grad_grad2_accumulate(), prior_hessian::MultivariateNormalDist< Ndim >::grad_hess_accumulate(), prior_hessian::MultivariateNormalDist< Ndim >::in_bounds(), prior_hessian::MultivariateNormalDist< Ndim >::mean(), prior_hessian::MultivariateNormalDist< Ndim >::mode(), prior_hessian::MultivariateNormalDist< Ndim >::MultivariateNormalDist(), prior_hessian::MultivariateNormalDist< Ndim >::operator==(), prior_hessian::MultivariateNormalDist< Ndim >::params(), prior_hessian::MultivariateNormalDist< Ndim >::rllh(), and prior_hessian::MultivariateNormalDist< Ndim >::sample().
template<int Ndim> static constexpr IdxT prior_hessian::MultivariateNormalDist< Ndim >::num_dim () inline static
Definition at line 30 of file MultivariateNormalDist.h.
References prior_hessian::MultivariateNormalDist< Ndim >::lbound(), and prior_hessian::MultivariateNormalDist< Ndim >::ubound().
Referenced by prior_hessian::MultivariateNormalDist< Ndim >::rllh().
template<int Ndim> static constexpr IdxT prior_hessian::MultivariateNormalDist< Ndim >::num_params () inline static
Definition at line 29 of file MultivariateNormalDist.h.
Referenced by prior_hessian::MultivariateNormalDist< Ndim >::check_params(), prior_hessian::MultivariateNormalDist< Ndim >::check_params_iter(), prior_hessian::MultivariateNormalDist< Ndim >::params(), prior_hessian::MultivariateNormalDist< Ndim >::set_params(), and prior_hessian::MultivariateNormalDist< Ndim >::ubound().
template<int Ndim> bool prior_hessian::MultivariateNormalDist< Ndim >::operator!= (const MultivariateNormalDist< Ndim > & o) const inline
Definition at line 61 of file MultivariateNormalDist.h.
References prior_hessian::MultivariateNormalDist< Ndim >::get_param(), prior_hessian::MultivariateNormalDist< Ndim >::operator==(), prior_hessian::MultivariateNormalDist< Ndim >::params(), and prior_hessian::MultivariateNormalDist< Ndim >::set_params().
template<int Ndim> bool prior_hessian::MultivariateNormalDist< Ndim >::operator== (const MultivariateNormalDist< Ndim > & o) const
Definition at line 425 of file MultivariateNormalDist.h.
References prior_hessian::MultivariateNormalDist< Ndim >::mu(), and prior_hessian::MultivariateNormalDist< Ndim >::sigma().
Referenced by prior_hessian::MultivariateNormalDist< Ndim >::in_bounds(), and prior_hessian::MultivariateNormalDist< Ndim >::operator!=().
template<int Ndim> const MultivariateNormalDist< Ndim >::NparamsVecT & prior_hessian::MultivariateNormalDist< Ndim >::param_lbound () static
Definition at line 280 of file MultivariateNormalDist.h.
Referenced by prior_hessian::MultivariateNormalDist< Ndim >::in_bounds().
template<int Ndim> const StringVecT & prior_hessian::MultivariateNormalDist< Ndim >::param_names () static
Definition at line 271 of file MultivariateNormalDist.h.
Referenced by prior_hessian::MultivariateNormalDist< Ndim >::in_bounds().
template<int Ndim> const MultivariateNormalDist< Ndim >::NparamsVecT & prior_hessian::MultivariateNormalDist< Ndim >::param_ubound () static
Definition at line 289 of file MultivariateNormalDist.h.
Referenced by prior_hessian::MultivariateNormalDist< Ndim >::in_bounds().
template<int Ndim> MultivariateNormalDist< Ndim >::NparamsVecT prior_hessian::MultivariateNormalDist< Ndim >::params () const
Definition at line 432 of file MultivariateNormalDist.h.
References prior_hessian::MultivariateNormalDist< Ndim >::mu(), prior_hessian::MultivariateNormalDist< Ndim >::num_params(), and prior_hessian::MultivariateNormalDist< Ndim >::sigma().
Referenced by prior_hessian::MultivariateNormalDist< Ndim >::in_bounds(), and prior_hessian::MultivariateNormalDist< Ndim >::operator!=().
template<int Ndim> template<class Vec > double prior_hessian::MultivariateNormalDist< Ndim >::pdf (const Vec & x) const
Definition at line 497 of file MultivariateNormalDist.h.
References prior_hessian::MultivariateNormalDist< Ndim >::llh().
Referenced by prior_hessian::MultivariateNormalDist< Ndim >::mode().
template<int Ndim> template<class Vec > double prior_hessian::MultivariateNormalDist< Ndim >::rllh (const Vec & x) const
Definition at line 515 of file MultivariateNormalDist.h.
References prior_hessian::helpers::compute_quadratic_from_symmetric(), prior_hessian::MultivariateNormalDist< Ndim >::mu(), prior_hessian::MultivariateNormalDist< Ndim >::num_dim(), and prior_hessian::MultivariateNormalDist< Ndim >::sigma_inv().
Referenced by prior_hessian::MultivariateNormalDist< Ndim >::llh(), and prior_hessian::MultivariateNormalDist< Ndim >::mode().
template<int Ndim> template<class RngT > MultivariateNormalDist< Ndim >::NdimVecT prior_hessian::MultivariateNormalDist< Ndim >::sample (RngT & rng) const
Definition at line 563 of file MultivariateNormalDist.h.
References prior_hessian::constants::log2pi, prior_hessian::MultivariateNormalDist< Ndim >::mu(), and prior_hessian::MultivariateNormalDist< Ndim >::sigma().
Referenced by prior_hessian::MultivariateNormalDist< Ndim >::mode().
template<int Ndim> template<class Vec > void prior_hessian::MultivariateNormalDist< Ndim >::set_mu (Vec && val)
Definition at line 396 of file MultivariateNormalDist.h.
References prior_hessian::MultivariateNormalDist< Ndim >::check_mu().
Referenced by prior_hessian::MultivariateNormalDist< Ndim >::in_bounds(), prior_hessian::MultivariateNormalDist< Ndim >::MultivariateNormalDist(), and prior_hessian::MultivariateNormalDist< Ndim >::set_params().
template<int Ndim> template<class Vec > void prior_hessian::MultivariateNormalDist< Ndim >::set_params (const Vec & p)
Definition at line 453 of file MultivariateNormalDist.h.
References prior_hessian::MultivariateNormalDist< Ndim >::num_params(), prior_hessian::MultivariateNormalDist< Ndim >::set_mu(), and prior_hessian::MultivariateNormalDist< Ndim >::set_sigma().
Referenced by prior_hessian::MultivariateNormalDist< Ndim >::operator!=(), and prior_hessian::MultivariateNormalDist< Ndim >::set_params_iter().
template<int Ndim> template<class Vec , class Mat > void prior_hessian::MultivariateNormalDist< Ndim >::set_params (Vec && mu, Mat && sigma)
Definition at line 461 of file MultivariateNormalDist.h.
References prior_hessian::MultivariateNormalDist< Ndim >::set_mu(), and prior_hessian::MultivariateNormalDist< Ndim >::set_sigma().
template<int Ndim> template<class IterT > void prior_hessian::MultivariateNormalDist< Ndim >::set_params_iter (IterT & params)
Definition at line 469 of file MultivariateNormalDist.h.
References prior_hessian::MultivariateNormalDist< Ndim >::set_params().
Referenced by prior_hessian::MultivariateNormalDist< Ndim >::mode().
template<int Ndim> template<class Mat > void prior_hessian::MultivariateNormalDist< Ndim >::set_sigma (Mat && val)
Definition at line 401 of file MultivariateNormalDist.h.
Referenced by prior_hessian::MultivariateNormalDist< Ndim >::in_bounds(), prior_hessian::MultivariateNormalDist< Ndim >::MultivariateNormalDist(), and prior_hessian::MultivariateNormalDist< Ndim >::set_params().
template<int Ndim> const MultivariateNormalDist< Ndim >::NdimMatT & prior_hessian::MultivariateNormalDist< Ndim >::sigma () const
Definition at line 381 of file MultivariateNormalDist.h.
Referenced by prior_hessian::MultivariateNormalDist< Ndim >::cdf(), prior_hessian::MultivariateNormalDist< Ndim >::in_bounds(), prior_hessian::MultivariateNormalDist< Ndim >::MultivariateNormalDist(), prior_hessian::MultivariateNormalDist< Ndim >::operator==(), prior_hessian::MultivariateNormalDist< Ndim >::params(), and prior_hessian::MultivariateNormalDist< Ndim >::sample().
template<int Ndim> const MultivariateNormalDist< Ndim >::NdimMatT & prior_hessian::MultivariateNormalDist< Ndim >::sigma_inv () const
Definition at line 386 of file MultivariateNormalDist.h.
Referenced by prior_hessian::MultivariateNormalDist< Ndim >::grad(), prior_hessian::MultivariateNormalDist< Ndim >::grad2(), prior_hessian::MultivariateNormalDist< Ndim >::grad_grad2_accumulate(), prior_hessian::MultivariateNormalDist< Ndim >::grad_hess_accumulate(), prior_hessian::MultivariateNormalDist< Ndim >::hess(), prior_hessian::MultivariateNormalDist< Ndim >::in_bounds(), and prior_hessian::MultivariateNormalDist< Ndim >::rllh().
template<int Ndim> const MultivariateNormalDist< Ndim >::NdimVecT & prior_hessian::MultivariateNormalDist< Ndim >::ubound () static
Definition at line 307 of file MultivariateNormalDist.h.
References prior_hessian::MultivariateNormalDist< Ndim >::num_params().
Referenced by prior_hessian::MultivariateNormalDist< Ndim >::in_bounds(), and prior_hessian::MultivariateNormalDist< Ndim >::num_dim().
The documentation for this class was generated from the following file:
MultivariateNormalDist.h