PriorHessian: prior_hessian::ScaledDist< Dist > Class Template Reference
prior_hessian::ScaledDist< Dist > Class Template Reference
#include </home/travis/build/markjolah/PriorHessian/include/PriorHessian/ScaledDist.h>
Public Member Functions
ScaledDist ()
ScaledDist (double lbound, double ubound)
template<typename = meta::EnableIfNotIsSelfT<Dist,ScaledDist>>
ScaledDist (const Dist &dist)
template<typename = meta::EnableIfNotIsSelfT<Dist,ScaledDist>>
ScaledDist (Dist &&dist)
ScaledDist (const Dist &dist, double lbound, double ubound)
ScaledDist (Dist &&dist, double lbound, double ubound)
double lbound () const
double ubound () const
bool operator== (const ScaledDist< Dist > &o) const
bool operator!= (const ScaledDist< Dist > &o) const
void set_lbound (double lbound)
void set_ubound (double ubound)
void set_bounds (double lbound, double ubound)
double mean () const
double median () const
double cdf (double x) const
double pdf (double x) const
double icdf (double u) const
double llh (double x) const
template<class RngT >
double sample (RngT &rng) const
Static Public Member Functions
static double unscaled_lbound ()
static double unscaled_ubound ()
static double global_lbound ()
static double global_ubound ()
Protected Member Functions
double convert_to_unitary_coords (double x) const
double convert_from_unitary_coords (double u) const
Protected Attributes
double _scaled_lbound
double _scaled_ubound
double scaling_ratio
double llh_scaling_const
Detailed Description
template<class Dist>
class prior_hessian::ScaledDist< Dist >
Definition at line 19 of file ScaledDist.h.
Constructor & Destructor Documentation
template<class Dist> prior_hessian::ScaledDist< Dist >::ScaledDist () inline
Definition at line 22 of file ScaledDist.h.
template<class Dist> prior_hessian::ScaledDist< Dist >::ScaledDist (double lbound, double ubound) inline
Definition at line 23 of file ScaledDist.h.
References prior_hessian::ScaledDist< Dist >::lbound(), and prior_hessian::ScaledDist< Dist >::ubound().
template<class Dist> template<typename = meta::EnableIfNotIsSelfT<Dist,ScaledDist>> prior_hessian::ScaledDist< Dist >::ScaledDist (const Dist & dist) inline
Definition at line 26 of file ScaledDist.h.
template<class Dist> template<typename = meta::EnableIfNotIsSelfT<Dist,ScaledDist>> prior_hessian::ScaledDist< Dist >::ScaledDist (Dist && dist) inline
Definition at line 29 of file ScaledDist.h.
template<class Dist> prior_hessian::ScaledDist< Dist >::ScaledDist (const Dist & dist, double lbound, double ubound) inline
Definition at line 31 of file ScaledDist.h.
References prior_hessian::ScaledDist< Dist >::set_bounds().
template<class Dist> prior_hessian::ScaledDist< Dist >::ScaledDist (Dist && dist, double lbound, double ubound) inline
Definition at line 32 of file ScaledDist.h.
References prior_hessian::ScaledDist< Dist >::set_bounds().
Member Function Documentation
template<class Dist > double prior_hessian::ScaledDist< Dist >::cdf (double x) const
Definition at line 112 of file ScaledDist.h.
References prior_hessian::ScaledDist< Dist >::convert_to_unitary_coords().
Referenced by prior_hessian::ScaledDist< Dist >::median().
template<class Dist > double prior_hessian::ScaledDist< Dist >::convert_from_unitary_coords (double u) const protected
Definition at line 143 of file ScaledDist.h.
References prior_hessian::ScaledDist< Dist >::lbound(), prior_hessian::ScaledDist< Dist >::scaling_ratio, and prior_hessian::ScaledDist< Dist >::unscaled_lbound().
Referenced by prior_hessian::ScaledDist< Dist >::icdf(), prior_hessian::ScaledDist< Dist >::mean(), prior_hessian::ScaledDist< Dist >::median(), and prior_hessian::ScaledDist< Dist >::sample().
template<class Dist > double prior_hessian::ScaledDist< Dist >::convert_to_unitary_coords (double x) const protected
Definition at line 137 of file ScaledDist.h.
References prior_hessian::ScaledDist< Dist >::lbound(), prior_hessian::ScaledDist< Dist >::scaling_ratio, and prior_hessian::ScaledDist< Dist >::unscaled_lbound().
Referenced by prior_hessian::ScaledDist< Dist >::cdf(), and prior_hessian::ScaledDist< Dist >::pdf().
template<class Dist> static double prior_hessian::ScaledDist< Dist >::global_lbound () inline static
Definition at line 38 of file ScaledDist.h.
template<class Dist> static double prior_hessian::ScaledDist< Dist >::global_ubound () inline static
Definition at line 39 of file ScaledDist.h.
template<class Dist > double prior_hessian::ScaledDist< Dist >::icdf (double u) const
Definition at line 118 of file ScaledDist.h.
References prior_hessian::ScaledDist< Dist >::convert_from_unitary_coords().
Referenced by prior_hessian::ScaledDist< Dist >::median().
template<class Dist> double prior_hessian::ScaledDist< Dist >::lbound () const inline
Definition at line 34 of file ScaledDist.h.
References prior_hessian::ScaledDist< Dist >::_scaled_lbound.
Referenced by prior_hessian::ScaledDist< Dist >::convert_from_unitary_coords(), prior_hessian::ScaledDist< Dist >::convert_to_unitary_coords(), prior_hessian::ScaledDist< Dist >::operator!=(), prior_hessian::ScaledDist< Dist >::ScaledDist(), prior_hessian::ScaledDist< Dist >::set_bounds(), and prior_hessian::ScaledDist< Dist >::set_ubound().
template<class Dist > double prior_hessian::ScaledDist< Dist >::llh (double x) const
Definition at line 106 of file ScaledDist.h.
References prior_hessian::ScaledDist< Dist >::llh_scaling_const.
Referenced by prior_hessian::ScaledDist< Dist >::median().
template<class Dist> double prior_hessian::ScaledDist< Dist >::mean () const inline
Definition at line 53 of file ScaledDist.h.
References prior_hessian::ScaledDist< Dist >::convert_from_unitary_coords().
template<class Dist> double prior_hessian::ScaledDist< Dist >::median () const inline
Definition at line 54 of file ScaledDist.h.
References prior_hessian::ScaledDist< Dist >::cdf(), prior_hessian::ScaledDist< Dist >::convert_from_unitary_coords(), prior_hessian::ScaledDist< Dist >::icdf(), prior_hessian::ScaledDist< Dist >::llh(), prior_hessian::ScaledDist< Dist >::pdf(), and prior_hessian::ScaledDist< Dist >::sample().
template<class Dist> bool prior_hessian::ScaledDist< Dist >::operator!= (const ScaledDist< Dist > & o) const inline
Definition at line 47 of file ScaledDist.h.
References prior_hessian::ScaledDist< Dist >::lbound(), prior_hessian::ScaledDist< Dist >::operator==(), prior_hessian::ScaledDist< Dist >::set_bounds(), prior_hessian::ScaledDist< Dist >::set_lbound(), prior_hessian::ScaledDist< Dist >::set_ubound(), and prior_hessian::ScaledDist< Dist >::ubound().
template<class Dist> bool prior_hessian::ScaledDist< Dist >::operator== (const ScaledDist< Dist > & o) const inline
Definition at line 41 of file ScaledDist.h.
References prior_hessian::ScaledDist< Dist >::_scaled_lbound, and prior_hessian::ScaledDist< Dist >::_scaled_ubound.
Referenced by prior_hessian::ScaledDist< Dist >::operator!=().
template<class Dist > double prior_hessian::ScaledDist< Dist >::pdf (double x) const
Definition at line 124 of file ScaledDist.h.
References prior_hessian::ScaledDist< Dist >::convert_to_unitary_coords(), and prior_hessian::ScaledDist< Dist >::scaling_ratio.
Referenced by prior_hessian::ScaledDist< Dist >::median().
template<class Dist > template<class RngT > double prior_hessian::ScaledDist< Dist >::sample (RngT & rng) const
Definition at line 131 of file ScaledDist.h.
References prior_hessian::ScaledDist< Dist >::convert_from_unitary_coords().
Referenced by prior_hessian::ScaledDist< Dist >::median().
template<class Dist > void prior_hessian::ScaledDist< Dist >::set_bounds (double lbound, double ubound)
Definition at line 76 of file ScaledDist.h.
References prior_hessian::ScaledDist< Dist >::_scaled_lbound, prior_hessian::ScaledDist< Dist >::_scaled_ubound, prior_hessian::ScaledDist< Dist >::lbound(), prior_hessian::ScaledDist< Dist >::llh_scaling_const, prior_hessian::ScaledDist< Dist >::scaling_ratio, prior_hessian::ScaledDist< Dist >::ubound(), prior_hessian::ScaledDist< Dist >::unscaled_lbound(), and prior_hessian::ScaledDist< Dist >::unscaled_ubound().
Referenced by prior_hessian::ScaledDist< Dist >::operator!=(), prior_hessian::ScaledDist< Dist >::ScaledDist(), prior_hessian::ScaledDist< Dist >::set_lbound(), and prior_hessian::ScaledDist< Dist >::set_ubound().
template<class Dist > void prior_hessian::ScaledDist< Dist >::set_lbound (double lbound)
Definition at line 98 of file ScaledDist.h.
References prior_hessian::ScaledDist< Dist >::set_bounds(), and prior_hessian::ScaledDist< Dist >::ubound().
Referenced by prior_hessian::ScaledDist< Dist >::operator!=().
template<class Dist > void prior_hessian::ScaledDist< Dist >::set_ubound (double ubound)
Definition at line 102 of file ScaledDist.h.
References prior_hessian::ScaledDist< Dist >::lbound(), and prior_hessian::ScaledDist< Dist >::set_bounds().
Referenced by prior_hessian::ScaledDist< Dist >::operator!=().
template<class Dist> double prior_hessian::ScaledDist< Dist >::ubound () const inline
Definition at line 35 of file ScaledDist.h.
References prior_hessian::ScaledDist< Dist >::_scaled_ubound.
Referenced by prior_hessian::ScaledDist< Dist >::operator!=(), prior_hessian::ScaledDist< Dist >::ScaledDist(), prior_hessian::ScaledDist< Dist >::set_bounds(), and prior_hessian::ScaledDist< Dist >::set_lbound().
template<class Dist> static double prior_hessian::ScaledDist< Dist >::unscaled_lbound () inline static
Definition at line 36 of file ScaledDist.h.
Referenced by prior_hessian::ScaledDist< Dist >::convert_from_unitary_coords(), prior_hessian::ScaledDist< Dist >::convert_to_unitary_coords(), and prior_hessian::ScaledDist< Dist >::set_bounds().
template<class Dist> static double prior_hessian::ScaledDist< Dist >::unscaled_ubound () inline static
Definition at line 37 of file ScaledDist.h.
Referenced by prior_hessian::ScaledDist< Dist >::set_bounds().
Member Data Documentation
template<class Dist> double prior_hessian::ScaledDist< Dist >::_scaled_lbound protected
Definition at line 64 of file ScaledDist.h.
Referenced by prior_hessian::ScaledDist< Dist >::lbound(), prior_hessian::ScaledDist< Dist >::operator==(), and prior_hessian::ScaledDist< Dist >::set_bounds().
template<class Dist> double prior_hessian::ScaledDist< Dist >::_scaled_ubound protected
Definition at line 65 of file ScaledDist.h.
Referenced by prior_hessian::ScaledDist< Dist >::operator==(), prior_hessian::ScaledDist< Dist >::set_bounds(), and prior_hessian::ScaledDist< Dist >::ubound().
template<class Dist> double prior_hessian::ScaledDist< Dist >::llh_scaling_const protected
Definition at line 68 of file ScaledDist.h.
Referenced by prior_hessian::ScaledDist< Dist >::llh(), and prior_hessian::ScaledDist< Dist >::set_bounds().
template<class Dist> double prior_hessian::ScaledDist< Dist >::scaling_ratio protected
Definition at line 67 of file ScaledDist.h.
Referenced by prior_hessian::ScaledDist< Dist >::convert_from_unitary_coords(), prior_hessian::ScaledDist< Dist >::convert_to_unitary_coords(), prior_hessian::ScaledDist< Dist >::pdf(), and prior_hessian::ScaledDist< Dist >::set_bounds().
The documentation for this class was generated from the following file:
ScaledDist.h