PriorHessian: prior_hessian::UpperTruncatedDist< Dist > Class Template Reference
prior_hessian::UpperTruncatedDist< Dist > Class Template Reference
#include </home/travis/build/markjolah/PriorHessian/include/PriorHessian/UpperTruncatedDist.h>
Public Member Functions
UpperTruncatedDist ()
UpperTruncatedDist (double ubound)
template<typename = meta::EnableIfNotIsSelfT<Dist,UpperTruncatedDist>>
UpperTruncatedDist (const Dist &dist)
template<typename = meta::EnableIfNotIsSelfT<Dist,UpperTruncatedDist>>
UpperTruncatedDist (Dist &&dist)
UpperTruncatedDist (const Dist &dist, double ubound)
UpperTruncatedDist (Dist &&dist, double ubound)
double ubound () const
bool truncated () const
bool operator== (const UpperTruncatedDist< Dist > &o) const
bool operator!= (const UpperTruncatedDist< Dist > &o) const
void set_bounds (double lbound, double ubound)
void set_lbound (double ubound)
void set_ubound (double ubound)
double mean () const
double median () const
double cdf (double x) const
double pdf (double x) const
double icdf (double u) const
double llh (double x) const
template<class RngT >
double sample (RngT &rng) const
Static Public Member Functions
static double global_ubound ()
Detailed Description
template<class Dist>
class prior_hessian::UpperTruncatedDist< Dist >
Definition at line 22 of file UpperTruncatedDist.h.
Constructor & Destructor Documentation
template<class Dist> prior_hessian::UpperTruncatedDist< Dist >::UpperTruncatedDist () inline
Definition at line 25 of file UpperTruncatedDist.h.
template<class Dist> prior_hessian::UpperTruncatedDist< Dist >::UpperTruncatedDist (double ubound) inline explicit
Definition at line 26 of file UpperTruncatedDist.h.
References prior_hessian::UpperTruncatedDist< Dist >::ubound().
template<class Dist> template<typename = meta::EnableIfNotIsSelfT<Dist,UpperTruncatedDist>> prior_hessian::UpperTruncatedDist< Dist >::UpperTruncatedDist (const Dist & dist) inline
Definition at line 29 of file UpperTruncatedDist.h.
template<class Dist> template<typename = meta::EnableIfNotIsSelfT<Dist,UpperTruncatedDist>> prior_hessian::UpperTruncatedDist< Dist >::UpperTruncatedDist (Dist && dist) inline
Definition at line 32 of file UpperTruncatedDist.h.
template<class Dist> prior_hessian::UpperTruncatedDist< Dist >::UpperTruncatedDist (const Dist & dist, double ubound) inline
Definition at line 34 of file UpperTruncatedDist.h.
References prior_hessian::UpperTruncatedDist< Dist >::set_ubound().
template<class Dist> prior_hessian::UpperTruncatedDist< Dist >::UpperTruncatedDist (Dist && dist, double ubound) inline
Definition at line 35 of file UpperTruncatedDist.h.
References prior_hessian::UpperTruncatedDist< Dist >::set_ubound().
Member Function Documentation
template<class Dist > double prior_hessian::UpperTruncatedDist< Dist >::cdf (double x) const
Definition at line 141 of file UpperTruncatedDist.h.
Referenced by prior_hessian::UpperTruncatedDist< Dist >::median().
template<class Dist> static double prior_hessian::UpperTruncatedDist< Dist >::global_ubound () inline static
Definition at line 38 of file UpperTruncatedDist.h.
Referenced by prior_hessian::UpperTruncatedDist< Dist >::set_bounds(), and prior_hessian::UpperTruncatedDist< Dist >::set_ubound().
template<class Dist > double prior_hessian::UpperTruncatedDist< Dist >::icdf (double u) const
Definition at line 147 of file UpperTruncatedDist.h.
Referenced by prior_hessian::UpperTruncatedDist< Dist >::median(), and prior_hessian::UpperTruncatedDist< Dist >::sample().
template<class Dist > double prior_hessian::UpperTruncatedDist< Dist >::llh (double x) const
Definition at line 159 of file UpperTruncatedDist.h.
Referenced by prior_hessian::UpperTruncatedDist< Dist >::median().
template<class Dist> double prior_hessian::UpperTruncatedDist< Dist >::mean () const inline
Definition at line 52 of file UpperTruncatedDist.h.
template<class Dist> double prior_hessian::UpperTruncatedDist< Dist >::median () const inline
Definition at line 53 of file UpperTruncatedDist.h.
References prior_hessian::UpperTruncatedDist< Dist >::cdf(), prior_hessian::UpperTruncatedDist< Dist >::icdf(), prior_hessian::UpperTruncatedDist< Dist >::llh(), prior_hessian::UpperTruncatedDist< Dist >::pdf(), and prior_hessian::UpperTruncatedDist< Dist >::sample().
template<class Dist> bool prior_hessian::UpperTruncatedDist< Dist >::operator!= (const UpperTruncatedDist< Dist > & o) const inline
Definition at line 46 of file UpperTruncatedDist.h.
References prior_hessian::UpperTruncatedDist< Dist >::operator==(), prior_hessian::UpperTruncatedDist< Dist >::set_bounds(), prior_hessian::UpperTruncatedDist< Dist >::set_lbound(), prior_hessian::UpperTruncatedDist< Dist >::set_ubound(), and prior_hessian::UpperTruncatedDist< Dist >::ubound().
template<class Dist> bool prior_hessian::UpperTruncatedDist< Dist >::operator== (const UpperTruncatedDist< Dist > & o) const inline
Definition at line 40 of file UpperTruncatedDist.h.
Referenced by prior_hessian::UpperTruncatedDist< Dist >::operator!=().
template<class Dist > double prior_hessian::UpperTruncatedDist< Dist >::pdf (double x) const
Definition at line 153 of file UpperTruncatedDist.h.
Referenced by prior_hessian::UpperTruncatedDist< Dist >::median().
template<class Dist > template<class RngT > double prior_hessian::UpperTruncatedDist< Dist >::sample (RngT & rng) const
Definition at line 166 of file UpperTruncatedDist.h.
References prior_hessian::UpperTruncatedDist< Dist >::icdf().
Referenced by prior_hessian::UpperTruncatedDist< Dist >::median().
template<class Dist > void prior_hessian::UpperTruncatedDist< Dist >::set_bounds (double lbound, double ubound)
Definition at line 73 of file UpperTruncatedDist.h.
References prior_hessian::UpperTruncatedDist< Dist >::global_ubound(), prior_hessian::UpperTruncatedDist< Dist >::set_lbound(), and prior_hessian::UpperTruncatedDist< Dist >::ubound().
Referenced by prior_hessian::UpperTruncatedDist< Dist >::operator!=().
template<class Dist > void prior_hessian::UpperTruncatedDist< Dist >::set_lbound (double ubound)
Definition at line 95 of file UpperTruncatedDist.h.
References prior_hessian::UpperTruncatedDist< Dist >::ubound().
Referenced by prior_hessian::UpperTruncatedDist< Dist >::operator!=(), and prior_hessian::UpperTruncatedDist< Dist >::set_bounds().
template<class Dist > void prior_hessian::UpperTruncatedDist< Dist >::set_ubound (double ubound)
Definition at line 111 of file UpperTruncatedDist.h.
References prior_hessian::UpperTruncatedDist< Dist >::global_ubound(), and prior_hessian::UpperTruncatedDist< Dist >::ubound().
Referenced by prior_hessian::UpperTruncatedDist< Dist >::operator!=(), and prior_hessian::UpperTruncatedDist< Dist >::UpperTruncatedDist().
template<class Dist> bool prior_hessian::UpperTruncatedDist< Dist >::truncated () const inline
Definition at line 39 of file UpperTruncatedDist.h.
template<class Dist> double prior_hessian::UpperTruncatedDist< Dist >::ubound () const inline
Definition at line 37 of file UpperTruncatedDist.h.
Referenced by prior_hessian::UpperTruncatedDist< Dist >::operator!=(), prior_hessian::UpperTruncatedDist< Dist >::set_bounds(), prior_hessian::UpperTruncatedDist< Dist >::set_lbound(), prior_hessian::UpperTruncatedDist< Dist >::set_ubound(), and prior_hessian::UpperTruncatedDist< Dist >::UpperTruncatedDist().
The documentation for this class was generated from the following file:
UpperTruncatedDist.h