PriorHessian: prior_hessian::CompositeDist Class Reference
prior_hessian::CompositeDist Class Reference
A probability distribution made of independent component distributions composing groups of 1 or more variables.
#include </home/travis/build/markjolah/PriorHessian/include/PriorHessian/CompositeDist.h>
Classes
class ComponentDistAdaptor
class ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, MultivariateDist > >
class ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, UnivariateDist > >
Public Types
using AnyRngT = any_rng::AnyRng< std::size_t >
template<class DistT >
using ComponentDistT = ComponentDistAdaptor< BoundsAdaptedDistT< std::remove_reference_t< DistT >>>
Public Member Functions
CompositeDist ()
template<class... Ts, meta::ConstructableIfAllAreNotTupleAndAreNotT< CompositeDist, Ts... > = true>
CompositeDist (Ts &&...dists)
Construct from a variadic list of subclasses of UnivariateDist's or MulitvariateDist's.
template<class... Ts>
CompositeDist (std::tuple< Ts... > &&dist_tuple)
Construct from a rvalue tuple of subclasses of UnivariateDist's or MulitvariateDist's.
template<class... Ts>
CompositeDist (const std::tuple< Ts... > &dist_tuple)
Construct from a lvalue tuple of subclasses of UnivariateDist's or MulitvariateDist's.
void initialize ()
void initialize (const std::tuple<> &)
Initialize to the empty state.
void initialize (std::tuple<> &&)
Initialize of an empty lvalue tuple produces the empty state.
template<class... Ts, typename = meta::EnableIfAllAreNotTupleT<Ts...>>
void initialize (Ts &&...dists)
Initialize of an empty rvalue tuple produces the empty state.
template<class... Ts, typename = meta::EnableIfAllAreNotTupleT<Ts...>>
void initialize (std::tuple< Ts... > &&dist_tuple)
template<class... Ts, typename = meta::EnableIfNonEmpty<Ts...>>
void initialize (const std::tuple< Ts... > &dist_tuple)
CompositeDist (const CompositeDist &)
CompositeDist & operator= (const CompositeDist &)
CompositeDist (CompositeDist &&)
CompositeDist & operator= (CompositeDist &&)
void clear ()
template<class... Ts>
const std::tuple< Ts... > & get_dist_tuple () const
bool is_empty () const
operator bool () const
IdxT num_components () const
TypeInfoVecT component_types () const
const StringVecT & component_names () const
template<class StringVec >
void set_component_names (StringVec &&names)
bool operator== (const CompositeDist &o) const
bool operator!= (const CompositeDist &o) const
IdxT num_dim () const
UVecT num_dim_components () const
const StringVecT & dim_variables () const
template<class StringVec >
void set_dim_variables (StringVec &&vars)
VecT lbound () const
VecT ubound () const
VecT global_lbound () const
VecT global_ubound () const
bool in_bounds (const VecT &u) const
bool in_bounds_all (const MatT &u) const
void set_lbound (const VecT &new_bound)
void set_ubound (const VecT &new_bound)
void set_bounds (const VecT &new_lbound, const VecT &new_ubound)
IdxT num_params () const
UVecT num_params_components () const
VecT params () const
void set_params (const VecT &new_params)
bool check_params (const VecT &new_params) const
VecT params_lbound () const
VecT params_ubound () const
std::vector< VecT > params_components () const
const StringVecT & param_names () const
template<class StringVec >
void set_param_names (StringVec &&vars)
bool has_dim_variable (const std::string &name) const
IdxT get_dim_variable_index (const std::string &name) const
void rename_dim_variable (const std::string &old_name, std::string new_name)
bool has_param (const std::string &name) const
double get_param_value (const std::string &name) const
IdxT get_param_index (const std::string &name) const
void set_param_value (const std::string &name, double value)
void rename_param (const std::string &old_name, std::string new_name)
double cdf (const VecT &u) const
double pdf (const VecT &u) const
double llh (const VecT &u) const
double rllh (const VecT &u) const
VecT grad (const VecT &u) const
VecT grad2 (const VecT &u) const
MatT hess (const VecT &u) const
void grad_accumulate (const VecT &theta, VecT &grad) const
void grad2_accumulate (const VecT &theta, VecT &grad2) const
void hess_accumulate (const VecT &theta, MatT &hess) const
void grad_grad2_accumulate (const VecT &theta, VecT &grad, VecT &grad2) const
void grad_hess_accumulate (const VecT &theta, VecT &grad, MatT &hess) const
VecT make_zero_grad () const
MatT make_zero_hess () const
VecT sample (AnyRngT &rng) const
VecT sample (AnyRngT &&rng) const
MatT sample (AnyRngT &rng, IdxT num_samples) const
MatT sample (AnyRngT &&rng, IdxT num_samples) const
template<class RngT >
VecT sample (RngT &&rng) const
template<class RngT >
MatT sample (RngT &&rng, IdxT num_samples) const
VecT llh_components (const VecT &u) const
VecT rllh_components (const VecT &u) const
Static Public Member Functions
template<class DistT >
static meta::ReturnIfInstantiatedFromT< DistT, DistT, ComponentDistAdaptor > make_component_dist (DistT &&dist)
template<class DistT >
static meta::ReturnIfNotInstantiatedFromT< ComponentDistT< DistT >, DistT, ComponentDistAdaptor > make_component_dist (DistT &&dist)
template<class... Ts>
static std::tuple< ComponentDistT< Ts >... > make_component_dist_tuple (const std::tuple< Ts... > &dists)
template<class... Ts, std::size_t... I>
static std::tuple< ComponentDistT< Ts >... > make_component_dist_tuple (const std::tuple< Ts... > &dists, std::index_sequence< I... >)
template<class... Ts>
static std::tuple< ComponentDistT< Ts >... > make_component_dist_tuple (std::tuple< Ts... > &&dists)
template<class... Ts, std::size_t... I>
static std::tuple< ComponentDistT< Ts >... > make_component_dist_tuple (std::tuple< Ts... > &&dists, std::index_sequence< I... >)
Detailed Description
A probability distribution made of independent component distributions composing groups of 1 or more variables.
CompositeDist is a world unto itself.
class UnivariateDistInterface { static CONSTEXPR IdxT num_dim(); static CONSTEXPR IdxT num_params(); static const StringVecT param_names; double lbound() const; double ubound() const; void set_bounds(double lbound, double ubound); void set_lbound(double lbound); void set_ubound(double ubound); double get_param(int idx) const; void set_param(int idx, double val); double cdf(double x) const; double icdf(double u) const; double pdf(double x) const; double llh(double x) const; double rllh(double x) const; double grad(double x) const; double grad2(double x) const; void grad_grad2_accumulate(double x, double &g, double &g2) const; template< class RngT > double sample(RngT &rng) const; }
dim_variables and param_names are lazily computed. If they are not accessed, they are not created.
Definition at line 60 of file CompositeDist.h.
Class Documentation
class prior_hessian::CompositeDist::ComponentDistAdaptor
template<class DistT, typename Enable = void>
class prior_hessian::CompositeDist::ComponentDistAdaptor< DistT, Enable >
Definition at line 64 of file CompositeDist.h.
Member Typedef Documentation
using prior_hessian::CompositeDist::AnyRngT = any_rng::AnyRng<std::size_t>
Definition at line 67 of file CompositeDist.h.
template<class DistT > using prior_hessian::CompositeDist::ComponentDistT = ComponentDistAdaptor<BoundsAdaptedDistT<std::remove_reference_t<DistT>>>
Definition at line 844 of file CompositeDist.h.
Constructor & Destructor Documentation
prior_hessian::CompositeDist::CompositeDist ()
Definition at line 13 of file CompositeDist.cpp.
Referenced by initialize().
template<class... Ts, meta::ConstructableIfAllAreNotTupleAndAreNotT< CompositeDist, Ts... > = true> prior_hessian::CompositeDist::CompositeDist (Ts &&... dists) inline explicit
Construct from a variadic list of subclasses of UnivariateDist's or MulitvariateDist's.
Definition at line 73 of file CompositeDist.h.
References make_component_dist().
template<class... Ts> prior_hessian::CompositeDist::CompositeDist (std::tuple< Ts... > && dist_tuple) inline explicit
Construct from a rvalue tuple of subclasses of UnivariateDist's or MulitvariateDist's.
Definition at line 79 of file CompositeDist.h.
References make_component_dist_tuple().
template<class... Ts> prior_hessian::CompositeDist::CompositeDist (const std::tuple< Ts... > & dist_tuple) inline explicit
Construct from a lvalue tuple of subclasses of UnivariateDist's or MulitvariateDist's.
Definition at line 85 of file CompositeDist.h.
References make_component_dist_tuple().
prior_hessian::CompositeDist::CompositeDist (const CompositeDist & o)
Definition at line 17 of file CompositeDist.cpp.
prior_hessian::CompositeDist::CompositeDist (CompositeDist && o)
Definition at line 28 of file CompositeDist.cpp.
Member Function Documentation
double prior_hessian::CompositeDist::cdf (const VecT & u) const inline
Definition at line 186 of file CompositeDist.h.
Referenced by prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, UnivariateDist > >::cdf_from_iter(), prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, MultivariateDist > >::cdf_from_iter(), and rllh_components().
bool prior_hessian::CompositeDist::check_params (const VecT & new_params) const inline
Definition at line 163 of file CompositeDist.h.
Referenced by rllh_components().
void prior_hessian::CompositeDist::clear ()
Definition at line 38 of file CompositeDist.cpp.
Referenced by initialize().
const StringVecT & prior_hessian::CompositeDist::component_names () const
Definition at line 108 of file CompositeDist.cpp.
Referenced by component_types(), prior_hessian::operator<<(), and param_names().
TypeInfoVecT prior_hessian::CompositeDist::component_types () const inline
Definition at line 127 of file CompositeDist.h.
References component_names(), operator==(), and set_component_names().
Referenced by rllh_components().
const StringVecT & prior_hessian::CompositeDist::dim_variables () const
Definition at line 114 of file CompositeDist.cpp.
Referenced by num_dim_components(), and prior_hessian::operator<<().
IdxT prior_hessian::CompositeDist::get_dim_variable_index (const std::string & name) const
Definition at line 175 of file CompositeDist.cpp.
Referenced by params_components().
template<class... Ts> const std::tuple< Ts... > & prior_hessian::CompositeDist::get_dist_tuple () const
Definition at line 930 of file CompositeDist.h.
Referenced by initialize().
IdxT prior_hessian::CompositeDist::get_param_index (const std::string & name) const
Definition at line 221 of file CompositeDist.cpp.
Referenced by params_components().
double prior_hessian::CompositeDist::get_param_value (const std::string & name) const
Definition at line 209 of file CompositeDist.cpp.
References params().
Referenced by params_components().
VecT prior_hessian::CompositeDist::global_lbound () const inline
Definition at line 145 of file CompositeDist.h.
Referenced by prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, MultivariateDist > >::append_global_lbound(), prior_hessian::operator<<(), and rllh_components().
VecT prior_hessian::CompositeDist::global_ubound () const inline
Definition at line 146 of file CompositeDist.h.
Referenced by prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, MultivariateDist > >::append_global_ubound(), prior_hessian::operator<<(), and rllh_components().
VecT prior_hessian::CompositeDist::grad (const VecT & u) const inline
Definition at line 190 of file CompositeDist.h.
References num_dim().
Referenced by prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, UnivariateDist > >::grad_accumulate_idx(), prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, MultivariateDist > >::grad_accumulate_idx(), prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, MultivariateDist > >::grad_grad2_accumulate_idx(), prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, MultivariateDist > >::grad_hess_accumulate_idx(), and rllh_components().
VecT prior_hessian::CompositeDist::grad2 (const VecT & u) const inline
Definition at line 197 of file CompositeDist.h.
References num_dim().
Referenced by prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, UnivariateDist > >::grad2_accumulate_idx(), prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, MultivariateDist > >::grad2_accumulate_idx(), prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, MultivariateDist > >::grad_grad2_accumulate_idx(), prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, UnivariateDist > >::hess_accumulate_idx(), and rllh_components().
void prior_hessian::CompositeDist::grad2_accumulate (const VecT & theta, VecT & grad2) const inline
Definition at line 219 of file CompositeDist.h.
Referenced by rllh_components().
void prior_hessian::CompositeDist::grad_accumulate (const VecT & theta, VecT & grad) const inline
Definition at line 218 of file CompositeDist.h.
Referenced by rllh_components().
void prior_hessian::CompositeDist::grad_grad2_accumulate (const VecT & theta, VecT & grad, VecT & grad2) const inline
Definition at line 221 of file CompositeDist.h.
Referenced by prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, UnivariateDist > >::grad_grad2_accumulate_idx(), prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, UnivariateDist > >::grad_hess_accumulate_idx(), and rllh_components().
void prior_hessian::CompositeDist::grad_hess_accumulate (const VecT & theta, VecT & grad, MatT & hess) const inline
Definition at line 224 of file CompositeDist.h.
Referenced by rllh_components().
bool prior_hessian::CompositeDist::has_dim_variable (const std::string & name) const
Definition at line 169 of file CompositeDist.cpp.
Referenced by params_components().
bool prior_hessian::CompositeDist::has_param (const std::string & name) const
Definition at line 203 of file CompositeDist.cpp.
Referenced by params_components().
MatT prior_hessian::CompositeDist::hess (const VecT & u) const inline
Definition at line 205 of file CompositeDist.h.
References num_dim().
Referenced by prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, MultivariateDist > >::grad_hess_accumulate_idx(), prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, MultivariateDist > >::hess_accumulate_idx(), and rllh_components().
void prior_hessian::CompositeDist::hess_accumulate (const VecT & theta, MatT & hess) const inline
Definition at line 220 of file CompositeDist.h.
Referenced by rllh_components().
bool prior_hessian::CompositeDist::in_bounds (const VecT & u) const inline
Definition at line 147 of file CompositeDist.h.
References lbound(), and ubound().
bool prior_hessian::CompositeDist::in_bounds_all (const MatT & u) const inline
Definition at line 149 of file CompositeDist.h.
References lbound(), and ubound().
void prior_hessian::CompositeDist::initialize () inline
Definition at line 89 of file CompositeDist.h.
References clear().
void prior_hessian::CompositeDist::initialize (const std::tuple<> &) inline
Initialize to the empty state.
Definition at line 90 of file CompositeDist.h.
References clear().
void prior_hessian::CompositeDist::initialize (std::tuple<> &&) inline
Initialize of an empty lvalue tuple produces the empty state.
Definition at line 91 of file CompositeDist.h.
References clear().
template<class... Ts, typename = meta::EnableIfAllAreNotTupleT<Ts...>> void prior_hessian::CompositeDist::initialize (Ts &&... dists) inline
Initialize of an empty rvalue tuple produces the empty state.
Definition at line 93 of file CompositeDist.h.
References make_component_dist().
template<class... Ts, typename = meta::EnableIfAllAreNotTupleT<Ts...>> void prior_hessian::CompositeDist::initialize (std::tuple< Ts... > && dist_tuple) inline
Definition at line 100 of file CompositeDist.h.
References make_component_dist_tuple().
template<class... Ts, typename = meta::EnableIfNonEmpty<Ts...>> void prior_hessian::CompositeDist::initialize (const std::tuple< Ts... > & dist_tuple) inline
Definition at line 107 of file CompositeDist.h.
References clear(), CompositeDist(), get_dist_tuple(), make_component_dist_tuple(), and operator=().
bool prior_hessian::CompositeDist::is_empty () const inline
Definition at line 124 of file CompositeDist.h.
Referenced by operator==().
VecT prior_hessian::CompositeDist::lbound () const inline
Definition at line 143 of file CompositeDist.h.
Referenced by prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, UnivariateDist > >::append_global_lbound(), prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, UnivariateDist > >::append_lbound(), prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, MultivariateDist > >::append_lbound(), in_bounds(), in_bounds_all(), prior_hessian::operator<<(), and rllh_components().
double prior_hessian::CompositeDist::llh (const VecT & u) const inline
Definition at line 188 of file CompositeDist.h.
Referenced by prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, UnivariateDist > >::llh_from_iter(), prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, MultivariateDist > >::llh_from_iter(), and rllh_components().
VecT prior_hessian::CompositeDist::llh_components (const VecT & u) const inline
Definition at line 249 of file CompositeDist.h.
Referenced by rllh_components().
template<class DistT > static meta::ReturnIfInstantiatedFromT<DistT,DistT,ComponentDistAdaptor> prior_hessian::CompositeDist::make_component_dist (DistT && dist) inline static
Definition at line 851 of file CompositeDist.h.
Referenced by CompositeDist(), initialize(), and make_component_dist_tuple().
template<class DistT > static meta::ReturnIfNotInstantiatedFromT<ComponentDistT<DistT>,DistT,ComponentDistAdaptor> prior_hessian::CompositeDist::make_component_dist (DistT && dist) inline static
Definition at line 857 of file CompositeDist.h.
References prior_hessian::make_adapted_bounded_dist().
template<class... Ts> static std::tuple<ComponentDistT<Ts>...> prior_hessian::CompositeDist::make_component_dist_tuple (const std::tuple< Ts... > & dists) inline static
Definition at line 867 of file CompositeDist.h.
Referenced by CompositeDist(), initialize(), and make_component_dist_tuple().
template<class... Ts, std::size_t... I> static std::tuple<ComponentDistT<Ts>...> prior_hessian::CompositeDist::make_component_dist_tuple (const std::tuple< Ts... > & dists, std::index_sequence< I... >) inline static
Definition at line 874 of file CompositeDist.h.
References prior_hessian::make_adapted_bounded_dist(), and make_component_dist().
template<class... Ts> static std::tuple<ComponentDistT<Ts>...> prior_hessian::CompositeDist::make_component_dist_tuple (std::tuple< Ts... > && dists) inline static
Definition at line 880 of file CompositeDist.h.
References make_component_dist_tuple().
template<class... Ts, std::size_t... I> static std::tuple<ComponentDistT<Ts>...> prior_hessian::CompositeDist::make_component_dist_tuple (std::tuple< Ts... > && dists, std::index_sequence< I... >) inline static
Definition at line 887 of file CompositeDist.h.
References prior_hessian::make_adapted_bounded_dist(), and make_component_dist().
VecT prior_hessian::CompositeDist::make_zero_grad () const inline
Definition at line 226 of file CompositeDist.h.
References num_dim().
MatT prior_hessian::CompositeDist::make_zero_hess () const inline
Definition at line 227 of file CompositeDist.h.
References num_dim().
IdxT prior_hessian::CompositeDist::num_components () const inline
Definition at line 126 of file CompositeDist.h.
Referenced by prior_hessian::operator<<(), param_names(), and set_component_names().
IdxT prior_hessian::CompositeDist::num_dim () const inline
Definition at line 136 of file CompositeDist.h.
Referenced by grad(), grad2(), hess(), make_zero_grad(), make_zero_hess(), prior_hessian::operator<<(), param_names(), rllh_components(), and set_dim_variables().
UVecT prior_hessian::CompositeDist::num_dim_components () const inline
Definition at line 137 of file CompositeDist.h.
References dim_variables(), and set_dim_variables().
Referenced by prior_hessian::operator<<(), and rllh_components().
IdxT prior_hessian::CompositeDist::num_params () const inline
Definition at line 159 of file CompositeDist.h.
Referenced by prior_hessian::operator<<(), rllh_components(), and set_param_names().
UVecT prior_hessian::CompositeDist::num_params_components () const inline
Definition at line 160 of file CompositeDist.h.
Referenced by prior_hessian::operator<<(), param_names(), and rllh_components().
prior_hessian::CompositeDist::operator bool () const inline
Definition at line 125 of file CompositeDist.h.
bool prior_hessian::CompositeDist::operator!= (const CompositeDist & o) const inline
Definition at line 133 of file CompositeDist.h.
References operator==().
CompositeDist & prior_hessian::CompositeDist::operator= (const CompositeDist & o)
Definition at line 44 of file CompositeDist.cpp.
Referenced by initialize().
CompositeDist & prior_hessian::CompositeDist::operator= (CompositeDist && o)
Definition at line 57 of file CompositeDist.cpp.
bool prior_hessian::CompositeDist::operator== (const CompositeDist & o) const
Definition at line 70 of file CompositeDist.cpp.
References is_empty().
Referenced by component_types(), and operator!=().
const StringVecT & prior_hessian::CompositeDist::param_names () const
Definition at line 120 of file CompositeDist.cpp.
References component_names(), num_components(), num_dim(), and num_params_components().
Referenced by prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, UnivariateDist > >::append_param_names(), prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, MultivariateDist > >::append_param_names(), prior_hessian::operator<<(), params_components(), rllh_components(), and set_param_names().
VecT prior_hessian::CompositeDist::params () const inline
Definition at line 161 of file CompositeDist.h.
Referenced by prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, UnivariateDist > >::append_params(), prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, MultivariateDist > >::append_params(), get_param_value(), prior_hessian::operator<<(), rllh_components(), and set_param_value().
std::vector<VecT> prior_hessian::CompositeDist::params_components () const inline
Definition at line 166 of file CompositeDist.h.
References get_dim_variable_index(), get_param_index(), get_param_value(), has_dim_variable(), has_param(), param_names(), rename_dim_variable(), rename_param(), set_param_names(), and set_param_value().
Referenced by rllh_components().
VecT prior_hessian::CompositeDist::params_lbound () const inline
Definition at line 164 of file CompositeDist.h.
Referenced by prior_hessian::operator<<(), and rllh_components().
VecT prior_hessian::CompositeDist::params_ubound () const inline
Definition at line 165 of file CompositeDist.h.
Referenced by prior_hessian::operator<<(), and rllh_components().
double prior_hessian::CompositeDist::pdf (const VecT & u) const inline
Definition at line 187 of file CompositeDist.h.
Referenced by prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, UnivariateDist > >::pdf_from_iter(), prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, MultivariateDist > >::pdf_from_iter(), and rllh_components().
void prior_hessian::CompositeDist::rename_dim_variable (const std::string & old_name, std::string new_name)
Definition at line 187 of file CompositeDist.cpp.
Referenced by params_components().
void prior_hessian::CompositeDist::rename_param (const std::string & old_name, std::string new_name)
Definition at line 247 of file CompositeDist.cpp.
Referenced by params_components().
double prior_hessian::CompositeDist::rllh (const VecT & u) const inline
Definition at line 189 of file CompositeDist.h.
Referenced by rllh_components(), prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, UnivariateDist > >::rllh_from_iter(), and prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, MultivariateDist > >::rllh_from_iter().
VecT prior_hessian::CompositeDist::rllh_components (const VecT & u) const inline
Definition at line 250 of file CompositeDist.h.
References prior_hessian::meta::call_in_order(), cdf(), check_params(), component_types(), global_lbound(), global_ubound(), grad(), grad2(), grad2_accumulate(), grad_accumulate(), grad_grad2_accumulate(), grad_hess_accumulate(), hess(), hess_accumulate(), lbound(), llh(), llh_components(), prior_hessian::meta::logical_and_in_order(), num_dim(), num_dim_components(), num_params(), num_params_components(), param_names(), params(), params_components(), params_lbound(), params_ubound(), pdf(), rllh(), sample(), set_bounds(), set_lbound(), set_param_names(), set_params(), set_ubound(), and ubound().
VecT prior_hessian::CompositeDist::sample (AnyRngT & rng) const inline
Definition at line 229 of file CompositeDist.h.
Referenced by prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, UnivariateDist > >::append_sample(), prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, MultivariateDist > >::append_sample(), and rllh_components().
VecT prior_hessian::CompositeDist::sample (AnyRngT && rng) const inline
Definition at line 230 of file CompositeDist.h.
MatT prior_hessian::CompositeDist::sample (AnyRngT & rng, IdxT num_samples) const inline
Definition at line 231 of file CompositeDist.h.
MatT prior_hessian::CompositeDist::sample (AnyRngT && rng, IdxT num_samples) const inline
Definition at line 232 of file CompositeDist.h.
template<class RngT > VecT prior_hessian::CompositeDist::sample (RngT && rng) const inline
Definition at line 235 of file CompositeDist.h.
template<class RngT > MatT prior_hessian::CompositeDist::sample (RngT && rng, IdxT num_samples) const inline
Definition at line 242 of file CompositeDist.h.
void prior_hessian::CompositeDist::set_bounds (const VecT & new_lbound, const VecT & new_ubound) inline
Definition at line 156 of file CompositeDist.h.
Referenced by rllh_components(), prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, UnivariateDist > >::set_bounds_from_iter(), and prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, MultivariateDist > >::set_bounds_from_iter().
template<class StringVec > void prior_hessian::CompositeDist::set_component_names (StringVec && names)
Definition at line 943 of file CompositeDist.h.
References num_components().
Referenced by component_types().
template<class StringVec > void prior_hessian::CompositeDist::set_dim_variables (StringVec && vars)
Definition at line 955 of file CompositeDist.h.
References num_dim().
Referenced by num_dim_components().
void prior_hessian::CompositeDist::set_lbound (const VecT & new_bound) inline
Definition at line 154 of file CompositeDist.h.
Referenced by rllh_components(), prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, UnivariateDist > >::set_lbound_from_iter(), and prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, MultivariateDist > >::set_lbound_from_iter().
template<class StringVec > void prior_hessian::CompositeDist::set_param_names (StringVec && vars)
Definition at line 967 of file CompositeDist.h.
References num_params(), prior_hessian::operator<<(), and param_names().
Referenced by params_components(), and rllh_components().
void prior_hessian::CompositeDist::set_param_value (const std::string & name, double value)
Definition at line 233 of file CompositeDist.cpp.
References params(), and set_params().
Referenced by params_components().
void prior_hessian::CompositeDist::set_params (const VecT & new_params) inline
Definition at line 162 of file CompositeDist.h.
Referenced by rllh_components(), and set_param_value().
void prior_hessian::CompositeDist::set_ubound (const VecT & new_bound) inline
Definition at line 155 of file CompositeDist.h.
Referenced by rllh_components(), prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, UnivariateDist > >::set_ubound_from_iter(), and prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, MultivariateDist > >::set_ubound_from_iter().
VecT prior_hessian::CompositeDist::ubound () const inline
Definition at line 144 of file CompositeDist.h.
Referenced by prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, UnivariateDist > >::append_global_ubound(), prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, UnivariateDist > >::append_ubound(), prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, MultivariateDist > >::append_ubound(), in_bounds(), in_bounds_all(), prior_hessian::operator<<(), and rllh_components().
The documentation for this class was generated from the following files:
CompositeDist.h
CompositeDist.cpp