PriorHessian: prior_hessian::TruncatedDist< Dist > Class Template Reference
prior_hessian::TruncatedDist< Dist > Class Template Reference
#include </home/travis/build/markjolah/PriorHessian/include/PriorHessian/TruncatedDist.h>
Public Member Functions
TruncatedDist ()
TruncatedDist (double lbound, double ubound)
template<typename = meta::EnableIfNotIsSelfT<Dist,TruncatedDist>>
TruncatedDist (const Dist &dist)
template<typename = meta::EnableIfNotIsSelfT<Dist,TruncatedDist>>
TruncatedDist (Dist &&dist)
TruncatedDist (const Dist &dist, double lbound, double ubound)
TruncatedDist (Dist &&dist, double lbound, double ubound)
double lbound () const
double ubound () const
bool truncated () const
bool operator== (const TruncatedDist< Dist > &o) const
bool operator!= (const TruncatedDist< Dist > &o) const
void set_bounds (double lbound, double ubound)
void set_lbound (double lbound)
void set_ubound (double ubound)
double mean () const
double median () const
double cdf (double x) const
double pdf (double x) const
double icdf (double u) const
double llh (double x) const
template<class RngT >
double sample (RngT &rng) const
Static Public Member Functions
static constexpr IdxT num_params ()
static double global_lbound ()
static double global_ubound ()
Static Public Attributes
static constexpr const double min_bounds_pdf_integral = 1.0e-8
Protected Attributes
double _truncated_lbound
double _truncated_ubound
bool _truncated = false
double lbound_cdf
double bounds_pdf_integral
double llh_truncation_const
Detailed Description
template<class Dist>
class prior_hessian::TruncatedDist< Dist >
Definition at line 22 of file TruncatedDist.h.
Constructor & Destructor Documentation
template<class Dist> prior_hessian::TruncatedDist< Dist >::TruncatedDist () inline
Definition at line 30 of file TruncatedDist.h.
template<class Dist> prior_hessian::TruncatedDist< Dist >::TruncatedDist (double lbound, double ubound) inline
Definition at line 31 of file TruncatedDist.h.
References prior_hessian::TruncatedDist< Dist >::lbound(), and prior_hessian::TruncatedDist< Dist >::ubound().
template<class Dist> template<typename = meta::EnableIfNotIsSelfT<Dist,TruncatedDist>> prior_hessian::TruncatedDist< Dist >::TruncatedDist (const Dist & dist) inline
Definition at line 34 of file TruncatedDist.h.
template<class Dist> template<typename = meta::EnableIfNotIsSelfT<Dist,TruncatedDist>> prior_hessian::TruncatedDist< Dist >::TruncatedDist (Dist && dist) inline
Definition at line 37 of file TruncatedDist.h.
template<class Dist> prior_hessian::TruncatedDist< Dist >::TruncatedDist (const Dist & dist, double lbound, double ubound) inline
Definition at line 39 of file TruncatedDist.h.
References prior_hessian::TruncatedDist< Dist >::set_bounds().
template<class Dist> prior_hessian::TruncatedDist< Dist >::TruncatedDist (Dist && dist, double lbound, double ubound) inline
Definition at line 43 of file TruncatedDist.h.
References prior_hessian::TruncatedDist< Dist >::set_bounds().
Member Function Documentation
template<class Dist > double prior_hessian::TruncatedDist< Dist >::cdf (double x) const
Definition at line 135 of file TruncatedDist.h.
References prior_hessian::TruncatedDist< Dist >::bounds_pdf_integral, and prior_hessian::TruncatedDist< Dist >::lbound_cdf.
Referenced by prior_hessian::TruncatedDist< Dist >::median().
template<class Dist> static double prior_hessian::TruncatedDist< Dist >::global_lbound () inline static
minimum allowabale delta in cdf for a valid truncation
Definition at line 27 of file TruncatedDist.h.
Referenced by prior_hessian::TruncatedDist< Dist >::set_bounds().
template<class Dist> static double prior_hessian::TruncatedDist< Dist >::global_ubound () inline static
Definition at line 28 of file TruncatedDist.h.
Referenced by prior_hessian::TruncatedDist< Dist >::set_bounds().
template<class Dist > double prior_hessian::TruncatedDist< Dist >::icdf (double u) const
Definition at line 141 of file TruncatedDist.h.
References prior_hessian::TruncatedDist< Dist >::bounds_pdf_integral, and prior_hessian::TruncatedDist< Dist >::lbound_cdf.
Referenced by prior_hessian::TruncatedDist< Dist >::median(), and prior_hessian::TruncatedDist< Dist >::sample().
template<class Dist> double prior_hessian::TruncatedDist< Dist >::lbound () const inline
Definition at line 47 of file TruncatedDist.h.
References prior_hessian::TruncatedDist< Dist >::_truncated_lbound.
Referenced by prior_hessian::TruncatedDist< Dist >::operator!=(), prior_hessian::TruncatedDist< Dist >::set_bounds(), prior_hessian::TruncatedDist< Dist >::set_ubound(), and prior_hessian::TruncatedDist< Dist >::TruncatedDist().
template<class Dist > double prior_hessian::TruncatedDist< Dist >::llh (double x) const
Definition at line 153 of file TruncatedDist.h.
References prior_hessian::TruncatedDist< Dist >::llh_truncation_const.
Referenced by prior_hessian::TruncatedDist< Dist >::median().
template<class Dist> double prior_hessian::TruncatedDist< Dist >::mean () const inline
Definition at line 62 of file TruncatedDist.h.
template<class Dist> double prior_hessian::TruncatedDist< Dist >::median () const inline
Definition at line 63 of file TruncatedDist.h.
References prior_hessian::TruncatedDist< Dist >::bounds_pdf_integral, prior_hessian::TruncatedDist< Dist >::cdf(), prior_hessian::TruncatedDist< Dist >::icdf(), prior_hessian::TruncatedDist< Dist >::lbound_cdf, prior_hessian::TruncatedDist< Dist >::llh(), prior_hessian::TruncatedDist< Dist >::pdf(), and prior_hessian::TruncatedDist< Dist >::sample().
template<class Dist> static constexpr IdxT prior_hessian::TruncatedDist< Dist >::num_params () inline static
Definition at line 25 of file TruncatedDist.h.
template<class Dist> bool prior_hessian::TruncatedDist< Dist >::operator!= (const TruncatedDist< Dist > & o) const inline
Definition at line 56 of file TruncatedDist.h.
References prior_hessian::TruncatedDist< Dist >::lbound(), prior_hessian::TruncatedDist< Dist >::operator==(), prior_hessian::TruncatedDist< Dist >::set_bounds(), prior_hessian::TruncatedDist< Dist >::set_lbound(), prior_hessian::TruncatedDist< Dist >::set_ubound(), and prior_hessian::TruncatedDist< Dist >::ubound().
template<class Dist> bool prior_hessian::TruncatedDist< Dist >::operator== (const TruncatedDist< Dist > & o) const inline
Definition at line 50 of file TruncatedDist.h.
References prior_hessian::TruncatedDist< Dist >::_truncated_lbound, and prior_hessian::TruncatedDist< Dist >::_truncated_ubound.
Referenced by prior_hessian::TruncatedDist< Dist >::operator!=().
template<class Dist > double prior_hessian::TruncatedDist< Dist >::pdf (double x) const
Definition at line 147 of file TruncatedDist.h.
References prior_hessian::TruncatedDist< Dist >::bounds_pdf_integral.
Referenced by prior_hessian::TruncatedDist< Dist >::median().
template<class Dist > template<class RngT > double prior_hessian::TruncatedDist< Dist >::sample (RngT & rng) const
Definition at line 166 of file TruncatedDist.h.
References prior_hessian::TruncatedDist< Dist >::icdf(), and prior_hessian::TruncatedDist< Dist >::truncated().
Referenced by prior_hessian::TruncatedDist< Dist >::median().
template<class Dist > void prior_hessian::TruncatedDist< Dist >::set_bounds (double lbound, double ubound)
Definition at line 82 of file TruncatedDist.h.
References prior_hessian::TruncatedDist< Dist >::_truncated, prior_hessian::TruncatedDist< Dist >::_truncated_lbound, prior_hessian::TruncatedDist< Dist >::_truncated_ubound, prior_hessian::TruncatedDist< Dist >::bounds_pdf_integral, prior_hessian::TruncatedDist< Dist >::global_lbound(), prior_hessian::TruncatedDist< Dist >::global_ubound(), prior_hessian::TruncatedDist< Dist >::lbound(), prior_hessian::TruncatedDist< Dist >::lbound_cdf, prior_hessian::TruncatedDist< Dist >::llh_truncation_const, prior_hessian::TruncatedDist< Dist >::min_bounds_pdf_integral, prior_hessian::TruncatedDist< Dist >::truncated(), and prior_hessian::TruncatedDist< Dist >::ubound().
Referenced by prior_hessian::TruncatedDist< Dist >::operator!=(), prior_hessian::TruncatedDist< Dist >::set_lbound(), prior_hessian::TruncatedDist< Dist >::set_ubound(), and prior_hessian::TruncatedDist< Dist >::TruncatedDist().
template<class Dist > void prior_hessian::TruncatedDist< Dist >::set_lbound (double lbound)
Definition at line 123 of file TruncatedDist.h.
References prior_hessian::TruncatedDist< Dist >::set_bounds(), and prior_hessian::TruncatedDist< Dist >::ubound().
Referenced by prior_hessian::TruncatedDist< Dist >::operator!=().
template<class Dist > void prior_hessian::TruncatedDist< Dist >::set_ubound (double ubound)
Definition at line 129 of file TruncatedDist.h.
References prior_hessian::TruncatedDist< Dist >::lbound(), and prior_hessian::TruncatedDist< Dist >::set_bounds().
Referenced by prior_hessian::TruncatedDist< Dist >::operator!=().
template<class Dist> bool prior_hessian::TruncatedDist< Dist >::truncated () const inline
Definition at line 49 of file TruncatedDist.h.
References prior_hessian::TruncatedDist< Dist >::_truncated.
Referenced by prior_hessian::TruncatedDist< Dist >::sample(), and prior_hessian::TruncatedDist< Dist >::set_bounds().
template<class Dist> double prior_hessian::TruncatedDist< Dist >::ubound () const inline
Definition at line 48 of file TruncatedDist.h.
References prior_hessian::TruncatedDist< Dist >::_truncated_ubound.
Referenced by prior_hessian::TruncatedDist< Dist >::operator!=(), prior_hessian::TruncatedDist< Dist >::set_bounds(), prior_hessian::TruncatedDist< Dist >::set_lbound(), and prior_hessian::TruncatedDist< Dist >::TruncatedDist().
Member Data Documentation
template<class Dist> bool prior_hessian::TruncatedDist< Dist >::_truncated = false protected
Definition at line 74 of file TruncatedDist.h.
Referenced by prior_hessian::TruncatedDist< Dist >::set_bounds(), and prior_hessian::TruncatedDist< Dist >::truncated().
template<class Dist> double prior_hessian::TruncatedDist< Dist >::_truncated_lbound protected
Definition at line 72 of file TruncatedDist.h.
Referenced by prior_hessian::TruncatedDist< Dist >::lbound(), prior_hessian::TruncatedDist< Dist >::operator==(), and prior_hessian::TruncatedDist< Dist >::set_bounds().
template<class Dist> double prior_hessian::TruncatedDist< Dist >::_truncated_ubound protected
Definition at line 73 of file TruncatedDist.h.
Referenced by prior_hessian::TruncatedDist< Dist >::operator==(), prior_hessian::TruncatedDist< Dist >::set_bounds(), and prior_hessian::TruncatedDist< Dist >::ubound().
template<class Dist> double prior_hessian::TruncatedDist< Dist >::bounds_pdf_integral protected
Definition at line 77 of file TruncatedDist.h.
Referenced by prior_hessian::TruncatedDist< Dist >::cdf(), prior_hessian::TruncatedDist< Dist >::icdf(), prior_hessian::TruncatedDist< Dist >::median(), prior_hessian::TruncatedDist< Dist >::pdf(), and prior_hessian::TruncatedDist< Dist >::set_bounds().
template<class Dist> double prior_hessian::TruncatedDist< Dist >::lbound_cdf protected
Definition at line 76 of file TruncatedDist.h.
Referenced by prior_hessian::TruncatedDist< Dist >::cdf(), prior_hessian::TruncatedDist< Dist >::icdf(), prior_hessian::TruncatedDist< Dist >::median(), and prior_hessian::TruncatedDist< Dist >::set_bounds().
template<class Dist> double prior_hessian::TruncatedDist< Dist >::llh_truncation_const protected
Definition at line 78 of file TruncatedDist.h.
Referenced by prior_hessian::TruncatedDist< Dist >::llh(), and prior_hessian::TruncatedDist< Dist >::set_bounds().
template<class Dist> constexpr const double prior_hessian::TruncatedDist< Dist >::min_bounds_pdf_integral = 1.0e-8 static
Definition at line 26 of file TruncatedDist.h.
Referenced by prior_hessian::TruncatedDist< Dist >::set_bounds().
The documentation for this class was generated from the following file:
TruncatedDist.h