PriorHessian: prior_hessian::GammaDist Class Reference
prior_hessian::GammaDist Class Reference
Single parameter beta distribution where = , leading to symmetric bounded distribution.
#include </home/travis/build/markjolah/PriorHessian/include/PriorHessian/GammaDist.h>
Public Types
using NparamsVecT = arma::Col< double >::fixed< _num_params >
Public Member Functions
GammaDist (double scale, double shape)
GammaDist ()
template<class Vec , meta::ConstructableIfNotSelfT< Vec, GammaDist > = true>
GammaDist (const Vec &params)
double get_param (int idx) const
void set_param (int idx, double val)
NparamsVecT params () const
template<class Vec >
void set_params (const Vec &p)
void set_params (double scale, double shape)
bool operator== (const GammaDist &o) const
bool operator!= (const GammaDist &o) const
double scale () const
double shape () const
void set_scale (double val)
void set_shape (double val)
double mean () const
double median () const
double cdf (double x) const
double icdf (double u) const
double pdf (double x) const
double llh (double x) const
double rllh (double x) const
double grad (double x) const
double grad2 (double x) const
void grad_grad2_accumulate (double x, double &g, double &g2) const
template<class RngT >
double sample (RngT &rng) const
template<class IterT >
void set_params_iter (IterT &params)
Static Public Member Functions
static constexpr IdxT num_params ()
static constexpr double lbound ()
static constexpr double ubound ()
static bool in_bounds (double u)
static const StringVecT & param_names ()
static const NparamsVecT & param_lbound ()
static const NparamsVecT & param_ubound ()
static bool check_params (double shape, double scale)
template<class Vec >
static bool check_params (const Vec &params)
template<class IterT >
static bool check_params_iter (IterT &params)
static constexpr IdxT num_dim ()
Static Protected Member Functions
static void check_bounds (double lbound, double ubound)
Detailed Description
Single parameter beta distribution where = , leading to symmetric bounded distribution.
Definition at line 22 of file GammaDist.h.
Member Typedef Documentation
using prior_hessian::GammaDist::NparamsVecT = arma::Col<double>::fixed<_num_params>
Definition at line 26 of file GammaDist.h.
Constructor & Destructor Documentation
prior_hessian::GammaDist::GammaDist (double scale, double shape)
Definition at line 25 of file GammaDist.cpp.
prior_hessian::GammaDist::GammaDist () inline
Definition at line 43 of file GammaDist.h.
Referenced by param_ubound().
template<class Vec , meta::ConstructableIfNotSelfT< Vec, GammaDist > = true> prior_hessian::GammaDist::GammaDist (const Vec & params) inline explicit
Definition at line 45 of file GammaDist.h.
References get_param(), and set_param().
Member Function Documentation
double prior_hessian::GammaDist::cdf (double x) const
Definition at line 53 of file GammaDist.cpp.
Referenced by median().
void prior_hessian::UnivariateDist::check_bounds (double lbound, double ubound) static protected inherited
Definition at line 22 of file UnivariateDist.cpp.
Referenced by prior_hessian::UnivariateDist::UnivariateDist().
bool prior_hessian::GammaDist::check_params (double shape, double scale) inline static
Definition at line 107 of file GammaDist.h.
Referenced by check_params_iter(), and param_ubound().
template<class Vec > bool prior_hessian::GammaDist::check_params (const Vec & params) static
Definition at line 113 of file GammaDist.h.
References params().
template<class IterT > bool prior_hessian::GammaDist::check_params_iter (IterT & params) static
Definition at line 183 of file GammaDist.h.
References check_params(), scale(), and shape().
Referenced by median().
double prior_hessian::GammaDist::get_param (int idx) const inline
Definition at line 119 of file GammaDist.h.
Referenced by GammaDist().
double prior_hessian::GammaDist::grad (double x) const inline
Definition at line 155 of file GammaDist.h.
Referenced by median().
double prior_hessian::GammaDist::grad2 (double x) const inline
Definition at line 161 of file GammaDist.h.
Referenced by median().
void prior_hessian::GammaDist::grad_grad2_accumulate (double x, double & g, double & g2) const inline
Definition at line 167 of file GammaDist.h.
Referenced by median().
double prior_hessian::GammaDist::icdf (double u) const
Definition at line 58 of file GammaDist.cpp.
Referenced by median().
static bool prior_hessian::GammaDist::in_bounds (double u) inline static
Definition at line 32 of file GammaDist.h.
References lbound(), and ubound().
static constexpr double prior_hessian::GammaDist::lbound () inline static
Definition at line 30 of file GammaDist.h.
Referenced by in_bounds().
double prior_hessian::GammaDist::llh (double x) const
Definition at line 72 of file GammaDist.cpp.
References rllh(), scale(), and shape().
Referenced by median().
double prior_hessian::GammaDist::mean () const inline
Definition at line 61 of file GammaDist.h.
double prior_hessian::GammaDist::median () const inline
Definition at line 62 of file GammaDist.h.
References cdf(), check_params_iter(), grad(), grad2(), grad_grad2_accumulate(), icdf(), llh(), pdf(), rllh(), sample(), and set_params_iter().
static constexpr IdxT prior_hessian::UnivariateDist::num_dim () inline static inherited
Definition at line 17 of file UnivariateDist.h.
static constexpr IdxT prior_hessian::GammaDist::num_params () inline static
Definition at line 29 of file GammaDist.h.
bool prior_hessian::GammaDist::operator!= (const GammaDist & o) const inline
Definition at line 54 of file GammaDist.h.
References operator==().
bool prior_hessian::GammaDist::operator== (const GammaDist & o) const inline
Definition at line 53 of file GammaDist.h.
Referenced by operator!=().
static const NparamsVecT& prior_hessian::GammaDist::param_lbound () inline static
Definition at line 35 of file GammaDist.h.
static const StringVecT& prior_hessian::GammaDist::param_names () inline static
Definition at line 34 of file GammaDist.h.
static const NparamsVecT& prior_hessian::GammaDist::param_ubound () inline static
Definition at line 36 of file GammaDist.h.
References check_params(), GammaDist(), params(), scale(), and shape().
NparamsVecT prior_hessian::GammaDist::params () const inline
Definition at line 49 of file GammaDist.h.
Referenced by check_params(), and param_ubound().
double prior_hessian::GammaDist::pdf (double x) const
Definition at line 65 of file GammaDist.cpp.
Referenced by median().
double prior_hessian::GammaDist::rllh (double x) const inline
Definition at line 149 of file GammaDist.h.
Referenced by llh(), and median().
template<class RngT > double prior_hessian::GammaDist::sample (RngT & rng) const
Definition at line 175 of file GammaDist.h.
Referenced by median().
double prior_hessian::GammaDist::scale () const inline
Definition at line 56 of file GammaDist.h.
Referenced by check_params_iter(), llh(), param_ubound(), and set_params_iter().
void prior_hessian::GammaDist::set_param (int idx, double val) inline
Definition at line 133 of file GammaDist.h.
References set_scale(), and set_shape().
Referenced by GammaDist().
template<class Vec > void prior_hessian::GammaDist::set_params (const Vec & p) inline
Definition at line 51 of file GammaDist.h.
References set_params().
Referenced by set_params(), and set_params_iter().
void prior_hessian::GammaDist::set_params (double scale, double shape)
Definition at line 46 of file GammaDist.cpp.
template<class IterT > void prior_hessian::GammaDist::set_params_iter (IterT & params)
Definition at line 191 of file GammaDist.h.
References scale(), set_params(), and shape().
Referenced by median().
void prior_hessian::GammaDist::set_scale (double val)
Definition at line 34 of file GammaDist.cpp.
Referenced by set_param(), and shape().
void prior_hessian::GammaDist::set_shape (double val)
Definition at line 40 of file GammaDist.cpp.
Referenced by set_param(), and shape().
double prior_hessian::GammaDist::shape () const inline
Definition at line 57 of file GammaDist.h.
References set_scale(), and set_shape().
Referenced by check_params_iter(), llh(), param_ubound(), and set_params_iter().
static constexpr double prior_hessian::GammaDist::ubound () inline static
Definition at line 31 of file GammaDist.h.
Referenced by in_bounds().
The documentation for this class was generated from the following files:
GammaDist.h
GammaDist.cpp