PriorHessian: prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs > Class Template Reference
prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs > Class Template Reference
#include </home/travis/build/markjolah/PriorHessian/include/PriorHessian/CopulaDist.h>
Public Types
using NdimVecT = arma::Col< double >::fixed< _num_dim >
using NdimMatT = arma::Mat< double >::fixed< _num_dim, _num_dim >
using NparamsVecT = arma::Col< double >
using MarginalDistTupleT = std::tuple< MarginalDistTs... >
using CopulaT = CopulaTemplate< _num_dim >
template<size_t I>
using MarginalDistT = std::tuple_element< I, MarginalDistTupleT >
Public Member Functions
CopulaDist ()
template<class Copula , class... DistTs, std::enable_if_t< sizeof...(DistTs)==sizeof...(MarginalDistTs), bool > Enable = true>
CopulaDist (Copula &&copula, DistTs &&...dists)
void initialize_copula (const CopulaT &_copula)
void initialize_marginals (const MarginalDistTupleT &dists)
NdimVecT lbound () const
NdimVecT ubound () const
template<class Vec , class Vec2 >
void set_bounds (const Vec &lbound, const Vec2 &ubound)
template<class Vec >
void set_lbound (const Vec &lbound)
template<class Vec >
void set_ubound (const Vec &ubound)
bool operator== (const CopulaDist< CopulaTemplate, MarginalDistTs... > &o) const
bool operator!= (const CopulaDist< CopulaTemplate, MarginalDistTs... > &o) const
NparamsVecT params () const
double get_copula_theta () const
void set_copula_theta (double theta)
template<class Vec >
void set_params (const Vec &params)
template<class Vec >
double cdf (const Vec &x) const
template<class Vec >
double pdf (const Vec &x) const
template<class Vec >
double llh (const Vec &x) const
template<class Vec >
double rllh (const Vec &x) const
template<class Vec >
NdimVecT grad (const Vec &x) const
template<class Vec >
NdimVecT grad2 (const Vec &x) const
template<class Vec >
NdimMatT hess (const Vec &x) const
template<class Vec , class Vec2 >
void grad_grad2_accumulate (const Vec &x, Vec2 &g, Vec2 &g2) const
template<class Vec , class Vec2 , class Mat >
void grad_hess_accumulate (const Vec &x, Vec2 &g, Mat &hess) const
template<class RngT >
NdimVecT sample (RngT &rng) const
template<class IterT >
void set_params_iter (IterT &params)
Static Public Member Functions
static IdxT num_params ()
static constexpr IdxT num_components ()
static constexpr IdxT num_dim ()
template<class Vec >
static bool check_params (const Vec &params)
static bool check_copula_theta (double theta)
static const StringVecT & param_names ()
static const NparamsVecT & param_lbound ()
static const NparamsVecT & param_ubound ()
static const NdimVecT & global_lbound ()
static const NdimVecT & global_ubound ()
template<class IterT >
static bool check_params_iter (IterT &params)
Static Protected Member Functions
template<class Vec >
static void check_bounds (const Vec &lbound, const Vec &ubound)
Detailed Description
template<template< int > class CopulaTemplate, class... MarginalDistTs>
class prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >
Definition at line 22 of file CopulaDist.h.
Member Typedef Documentation
template<template< int > class CopulaTemplate, class... MarginalDistTs> using prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::CopulaT = CopulaTemplate<_num_dim>
Definition at line 41 of file CopulaDist.h.
template<template< int > class CopulaTemplate, class... MarginalDistTs> template<size_t I> using prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::MarginalDistT = std::tuple_element<I,MarginalDistTupleT>
Definition at line 44 of file CopulaDist.h.
template<template< int > class CopulaTemplate, class... MarginalDistTs> using prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::MarginalDistTupleT = std::tuple<MarginalDistTs...>
Definition at line 40 of file CopulaDist.h.
template<template< int > class CopulaTemplate, class... MarginalDistTs> using prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::NdimMatT = arma::Mat<double>::fixed<_num_dim,_num_dim>
Definition at line 32 of file CopulaDist.h.
template<template< int > class CopulaTemplate, class... MarginalDistTs> using prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::NdimVecT = arma::Col<double>::fixed<_num_dim>
Definition at line 31 of file CopulaDist.h.
template<template< int > class CopulaTemplate, class... MarginalDistTs> using prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::NparamsVecT = arma::Col<double>
Definition at line 37 of file CopulaDist.h.
Constructor & Destructor Documentation
template<template< int > class CopulaTemplate, class... MarginalDistTs> prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::CopulaDist ()
Definition at line 242 of file CopulaDist.h.
Referenced by prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::num_dim().
template<template< int > class CopulaTemplate, class... MarginalDistTs> template<class Copula , class... DistTs, std::enable_if_t< sizeof...(DistTs)==sizeof...(MarginalDistTs), bool > Enable> prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::CopulaDist (Copula && copula, DistTs &&... dists)
Definition at line 233 of file CopulaDist.h.
Member Function Documentation
template<template< int > class CopulaTemplate, class... MarginalDistTs> template<class Vec > double prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::cdf (const Vec & x) const
Definition at line 385 of file CopulaDist.h.
Referenced by prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::global_ubound(), and prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::operator!=().
template<class Vec > static void prior_hessian::MultivariateDist::check_bounds (const Vec & lbound, const Vec & ubound) inline static protected inherited
Definition at line 57 of file MultivariateDist.h.
template<template< int > class CopulaTemplate, class... MarginalDistTs> static bool prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::check_copula_theta (double theta) static
Referenced by prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::num_dim().
template<template< int > class CopulaTemplate, class... MarginalDistTs> template<class Vec > static bool prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::check_params (const Vec & params) static
Referenced by prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::num_dim().
template<template< int > class CopulaTemplate, class... MarginalDistTs> template<class IterT > bool prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::check_params_iter (IterT & params) static
Definition at line 368 of file CopulaDist.h.
Referenced by prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::operator!=().
template<template< int > class CopulaTemplate, class... MarginalDistTs> double prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::get_copula_theta () const
Definition at line 346 of file CopulaDist.h.
Referenced by prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::operator!=().
template<template< int > class CopulaTemplate, class... MarginalDistTs> const CopulaDist< CopulaTemplate, MarginalDistTs... >::NdimVecT & prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::global_lbound () static
Definition at line 536 of file CopulaDist.h.
Referenced by prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::num_dim(), prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::set_bounds(), and prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::set_lbound().
template<template< int > class CopulaTemplate, class... MarginalDistTs> const CopulaDist< CopulaTemplate, MarginalDistTs... >::NdimVecT & prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::global_ubound () static
Definition at line 545 of file CopulaDist.h.
References prior_hessian::meta::call_in_order(), prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::cdf(), prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::lbound(), prior_hessian::meta::logical_and_in_order(), prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::num_components(), prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::num_params(), prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::pdf(), prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::set_bounds(), prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::set_lbound(), prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::set_params_iter(), prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::set_ubound(), and prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::ubound().
Referenced by prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::num_dim(), prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::set_bounds(), and prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::set_ubound().
template<template< int > class CopulaTemplate, class... MarginalDistTs> template<class Vec > CopulaDist< CopulaTemplate, MarginalDistTs... >::NdimVecT prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::grad (const Vec & x) const
Definition at line 428 of file CopulaDist.h.
Referenced by prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::operator!=().
template<template< int > class CopulaTemplate, class... MarginalDistTs> template<class Vec > CopulaDist< CopulaTemplate, MarginalDistTs... >::NdimVecT prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::grad2 (const Vec & x) const
Definition at line 440 of file CopulaDist.h.
Referenced by prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::operator!=().
template<template< int > class CopulaTemplate, class... MarginalDistTs> template<class Vec , class Vec2 > void prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::grad_grad2_accumulate (const Vec & x, Vec2 & g, Vec2 & g2) const
Definition at line 466 of file CopulaDist.h.
Referenced by prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::operator!=().
template<template< int > class CopulaTemplate, class... MarginalDistTs> template<class Vec , class Vec2 , class Mat > void prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::grad_hess_accumulate (const Vec & x, Vec2 & g, Mat & hess) const
Definition at line 481 of file CopulaDist.h.
Referenced by prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::operator!=().
template<template< int > class CopulaTemplate, class... MarginalDistTs> template<class Vec > CopulaDist< CopulaTemplate, MarginalDistTs... >::NdimMatT prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::hess (const Vec & x) const
Definition at line 452 of file CopulaDist.h.
Referenced by prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::operator!=().
template<template< int > class CopulaTemplate, class... MarginalDistTs> void prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::initialize_copula (const CopulaT & _copula)
Definition at line 255 of file CopulaDist.h.
Referenced by prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::num_dim().
template<template< int > class CopulaTemplate, class... MarginalDistTs> void prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::initialize_marginals (const MarginalDistTupleT & dists)
Definition at line 262 of file CopulaDist.h.
Referenced by prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::num_dim().
template<template< int > class CopulaTemplate, class... MarginalDistTs> NdimVecT prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::lbound () const inline
Definition at line 67 of file CopulaDist.h.
Referenced by prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::global_ubound(), prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::set_ubound(), and prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::ubound().
template<template< int > class CopulaTemplate, class... MarginalDistTs> template<class Vec > double prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::llh (const Vec & x) const
Definition at line 405 of file CopulaDist.h.
Referenced by prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::operator!=().
template<template< int > class CopulaTemplate, class... MarginalDistTs> static constexpr IdxT prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::num_components () inline static
Definition at line 46 of file CopulaDist.h.
Referenced by prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::global_ubound().
template<template< int > class CopulaTemplate, class... MarginalDistTs> static constexpr IdxT prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::num_dim () inline static
Definition at line 47 of file CopulaDist.h.
References prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::check_copula_theta(), prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::check_params(), prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::CopulaDist(), prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::global_lbound(), prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::global_ubound(), prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::initialize_copula(), prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::initialize_marginals(), prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::param_lbound(), prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::param_names(), prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::param_ubound(), and prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::params().
template<template< int > class CopulaTemplate, class... MarginalDistTs> static IdxT prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::num_params () inline static
Definition at line 38 of file CopulaDist.h.
Referenced by prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::global_ubound(), and prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::operator!=().
template<template< int > class CopulaTemplate, class... MarginalDistTs> bool prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::operator!= (const CopulaDist< CopulaTemplate, MarginalDistTs... > & o) const inline
Definition at line 80 of file CopulaDist.h.
References prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::cdf(), prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::check_params_iter(), prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::get_copula_theta(), prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::grad(), prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::grad2(), prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::grad_grad2_accumulate(), prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::grad_hess_accumulate(), prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::hess(), prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::llh(), prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::num_params(), prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::operator==(), prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::params(), prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::pdf(), prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::rllh(), prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::sample(), prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::set_copula_theta(), prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::set_params(), prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::set_params_iter(), and prior_hessian::meta::sum_in_order().
template<template< int > class CopulaTemplate, class... MarginalDistTs> bool prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::operator== (const CopulaDist< CopulaTemplate, MarginalDistTs... > & o) const
Definition at line 330 of file CopulaDist.h.
Referenced by prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::operator!=(), and prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::ubound().
template<template< int > class CopulaTemplate, class... MarginalDistTs> const CopulaDist< CopulaTemplate, MarginalDistTs... >::NparamsVecT & prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::param_lbound () static
Definition at line 518 of file CopulaDist.h.
Referenced by prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::num_dim().
template<template< int > class CopulaTemplate, class... MarginalDistTs> const StringVecT & prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::param_names () static
Definition at line 509 of file CopulaDist.h.
Referenced by prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::num_dim().
template<template< int > class CopulaTemplate, class... MarginalDistTs> const CopulaDist< CopulaTemplate, MarginalDistTs... >::NparamsVecT & prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::param_ubound () static
Definition at line 527 of file CopulaDist.h.
Referenced by prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::num_dim().
template<template< int > class CopulaTemplate, class... MarginalDistTs> CopulaDist< CopulaTemplate, MarginalDistTs... >::NparamsVecT prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::params () const
Definition at line 337 of file CopulaDist.h.
Referenced by prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::num_dim(), and prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::operator!=().
template<template< int > class CopulaTemplate, class... MarginalDistTs> template<class Vec > double prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::pdf (const Vec & x) const
Definition at line 394 of file CopulaDist.h.
Referenced by prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::global_ubound(), and prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::operator!=().
template<template< int > class CopulaTemplate, class... MarginalDistTs> template<class Vec > double prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::rllh (const Vec & x) const
Definition at line 416 of file CopulaDist.h.
Referenced by prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::operator!=().
template<template< int > class CopulaTemplate, class... MarginalDistTs> template<class RngT > CopulaDist< CopulaTemplate, MarginalDistTs... >::NdimVecT prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::sample (RngT & rng) const
Definition at line 499 of file CopulaDist.h.
Referenced by prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::operator!=().
template<template< int > class CopulaTemplate, class... MarginalDistTs> template<class Vec , class Vec2 > void prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::set_bounds (const Vec & lbound, const Vec2 & ubound)
Definition at line 271 of file CopulaDist.h.
References prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::global_lbound(), and prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::global_ubound().
Referenced by prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::global_ubound(), and prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::ubound().
template<template< int > class CopulaTemplate, class... MarginalDistTs> void prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::set_copula_theta (double theta)
Definition at line 352 of file CopulaDist.h.
Referenced by prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::operator!=().
template<template< int > class CopulaTemplate, class... MarginalDistTs> template<class Vec > void prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::set_lbound (const Vec & lbound)
Definition at line 295 of file CopulaDist.h.
References prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::global_lbound(), and prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::ubound().
Referenced by prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::global_ubound(), and prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::ubound().
template<template< int > class CopulaTemplate, class... MarginalDistTs> template<class Vec > void prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::set_params (const Vec & params)
Definition at line 359 of file CopulaDist.h.
Referenced by prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::operator!=().
template<template< int > class CopulaTemplate, class... MarginalDistTs> template<class IterT > void prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::set_params_iter (IterT & params)
Definition at line 375 of file CopulaDist.h.
Referenced by prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::global_ubound(), and prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::operator!=().
template<template< int > class CopulaTemplate, class... MarginalDistTs> template<class Vec > void prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::set_ubound (const Vec & ubound)
Definition at line 313 of file CopulaDist.h.
References prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::global_ubound(), and prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::lbound().
Referenced by prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::global_ubound(), and prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::ubound().
template<template< int > class CopulaTemplate, class... MarginalDistTs> NdimVecT prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::ubound () const inline
Definition at line 68 of file CopulaDist.h.
References prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::lbound(), prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::operator==(), prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::set_bounds(), prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::set_lbound(), and prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::set_ubound().
Referenced by prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::global_ubound(), and prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::set_lbound().
The documentation for this class was generated from the following file:
CopulaDist.h