PriorHessian: prior_hessian::AMHCopula< Ndim > Class Template Reference
prior_hessian::AMHCopula< Ndim > Class Template Reference
#include </home/travis/build/markjolah/PriorHessian/include/PriorHessian/AMHCopula.h>
Public Types
using NdimVecT = arma::Col< double >::fixed< Ndim >
using NdimMatT = arma::Mat< double >::fixed< Ndim, Ndim >
Public Member Functions
AMHCopula ()
AMHCopula (double theta)
double theta () const
void set_theta (double val)
bool operator== (const AMHCopula< Ndim > &o) const
bool operator!= (const AMHCopula< Ndim > &o) const
template<class Vec >
void set_params (const Vec &params)
template<class IterT >
void append_params (IterT &params)
template<class IterT >
void set_params_iter (IterT &params)
template<class Vec >
double cdf (const Vec &u) const
template<class Vec >
double pdf (const Vec &u) const
template<class Vec >
double llh (const Vec &u) const
template<class Vec >
double rllh (const Vec &u) const
double rllh_const () const
template<class Vec >
NdimVecT grad (const Vec &u) const
template<class Vec >
NdimVecT grad2 (const Vec &u) const
template<class Vec >
NdimMatT hess (const Vec &u) const
template<class Vec , class Vec2 >
void rllh_grad_accumulate (const Vec &u, double &rllh, Vec2 &grad) const
template<class Vec , class Vec2 >
void rllh_grad_grad2_accumulate (const Vec &u, double &rllh, Vec2 &grad, Vec2 &grad2) const
template<class Vec , class Vec2 , class Mat >
void rllh_grad_hess_accumulate (const Vec &u, double &rllh, Vec2 &grad, Mat &hess) const
template<class RngT >
NdimVecT sample (RngT &rng) const
double gen (double t) const
double ddim_gen (double t) const
double igen (double u) const
double d1_igen (double u) const
template<class Vec >
double igen_sum (const Vec &u)
Static Public Member Functions
static const StringVecT & param_names ()
static constexpr IdxT num_params ()
static constexpr IdxT num_dim ()
static double param_lbound ()
static double param_ubound ()
static bool check_theta (double val)
template<class Vec >
static bool check_params (const Vec &params)
template<class IterT >
static bool check_params_iter (IterT &params)
template<class Vec >
static void rllh_dtheta_accumulate (double theta, const Vec &u, double &rllh, double &dtheta)
template<class Vec >
static void rllh_d2theta_accumulate (double theta, const Vec &u, double &rllh, double &dtheta, double &d2theta)
Detailed Description
template<int Ndim>
class prior_hessian::AMHCopula< Ndim >
Definition at line 18 of file AMHCopula.h.
Member Typedef Documentation
template<int Ndim> using prior_hessian::AMHCopula< Ndim >::NdimMatT = arma::Mat<double>::fixed<Ndim,Ndim>
Definition at line 27 of file AMHCopula.h.
template<int Ndim> using prior_hessian::AMHCopula< Ndim >::NdimVecT = arma::Col<double>::fixed<Ndim>
Definition at line 26 of file AMHCopula.h.
Constructor & Destructor Documentation
template<int Ndim> prior_hessian::AMHCopula< Ndim >::AMHCopula () inline
Definition at line 35 of file AMHCopula.h.
References prior_hessian::AMHCopula< Ndim >::theta().
template<int Ndim> prior_hessian::AMHCopula< Ndim >::AMHCopula (double theta)
Definition at line 169 of file AMHCopula.h.
References prior_hessian::AMHCopula< Ndim >::set_theta().
Member Function Documentation
template<int Ndim> template<class IterT > void prior_hessian::AMHCopula< Ndim >::append_params (IterT & params) inline
Definition at line 51 of file AMHCopula.h.
References prior_hessian::AMHCopula< Ndim >::theta().
template<int Ndim> template<class Vec > double prior_hessian::AMHCopula< Ndim >::cdf (const Vec & u) const
Definition at line 194 of file AMHCopula.h.
References prior_hessian::AMHCopula< Ndim >::theta().
Referenced by prior_hessian::AMHCopula< Ndim >::set_params_iter().
template<int Ndim> template<class Vec > static bool prior_hessian::AMHCopula< Ndim >::check_params (const Vec & params) inline static
Definition at line 45 of file AMHCopula.h.
References prior_hessian::AMHCopula< Ndim >::check_theta().
template<int Ndim> template<class IterT > static bool prior_hessian::AMHCopula< Ndim >::check_params_iter (IterT & params) inline static
Definition at line 49 of file AMHCopula.h.
References prior_hessian::AMHCopula< Ndim >::check_theta().
template<int Ndim> bool prior_hessian::AMHCopula< Ndim >::check_theta (double val) static
Definition at line 163 of file AMHCopula.h.
Referenced by prior_hessian::AMHCopula< Ndim >::check_params(), prior_hessian::AMHCopula< Ndim >::check_params_iter(), prior_hessian::AMHCopula< Ndim >::param_ubound(), and prior_hessian::AMHCopula< Ndim >::set_theta().
template<int Ndim> double prior_hessian::AMHCopula< Ndim >::d1_igen (double u) const
Definition at line 284 of file AMHCopula.h.
References prior_hessian::AMHCopula< Ndim >::igen_sum(), prior_hessian::AMHCopula< Ndim >::num_dim(), prior_hessian::polylog::polylog(), and prior_hessian::AMHCopula< Ndim >::theta().
Referenced by prior_hessian::AMHCopula< Ndim >::llh(), and prior_hessian::AMHCopula< Ndim >::set_params_iter().
template<int Ndim> double prior_hessian::AMHCopula< Ndim >::ddim_gen (double t) const
Definition at line 270 of file AMHCopula.h.
References prior_hessian::AMHCopula< Ndim >::num_dim(), and prior_hessian::polylog::polylog().
Referenced by prior_hessian::AMHCopula< Ndim >::llh(), and prior_hessian::AMHCopula< Ndim >::set_params_iter().
template<int Ndim> double prior_hessian::AMHCopula< Ndim >::gen (double t) const
Definition at line 265 of file AMHCopula.h.
Referenced by prior_hessian::AMHCopula< Ndim >::set_params_iter().
template<int Ndim> template<class Vec > AMHCopula< Ndim >::NdimVecT prior_hessian::AMHCopula< Ndim >::grad (const Vec & u) const
Definition at line 220 of file AMHCopula.h.
References prior_hessian::AMHCopula< Ndim >::grad2(), and prior_hessian::AMHCopula< Ndim >::theta().
Referenced by prior_hessian::AMHCopula< Ndim >::set_params_iter().
template<int Ndim> template<class Vec > AMHCopula< Ndim >::NdimVecT prior_hessian::AMHCopula< Ndim >::grad2 (const Vec & u) const
Definition at line 234 of file AMHCopula.h.
References prior_hessian::square(), and prior_hessian::AMHCopula< Ndim >::theta().
Referenced by prior_hessian::AMHCopula< Ndim >::grad(), and prior_hessian::AMHCopula< Ndim >::set_params_iter().
template<int Ndim> template<class Vec > AMHCopula< Ndim >::NdimMatT prior_hessian::AMHCopula< Ndim >::hess (const Vec & u) const
Definition at line 248 of file AMHCopula.h.
References prior_hessian::square(), and prior_hessian::AMHCopula< Ndim >::theta().
Referenced by prior_hessian::AMHCopula< Ndim >::set_params_iter().
template<int Ndim> double prior_hessian::AMHCopula< Ndim >::igen (double u) const
Definition at line 279 of file AMHCopula.h.
Referenced by prior_hessian::AMHCopula< Ndim >::set_params_iter().
template<int Ndim> template<class Vec > double prior_hessian::AMHCopula< Ndim >::igen_sum (const Vec & u) inline
Definition at line 97 of file AMHCopula.h.
References prior_hessian::AMHCopula< Ndim >::igen_sum(), and prior_hessian::AMHCopula< Ndim >::theta().
Referenced by prior_hessian::AMHCopula< Ndim >::d1_igen(), prior_hessian::AMHCopula< Ndim >::igen_sum(), and prior_hessian::AMHCopula< Ndim >::llh().
template<int Ndim> template<class Vec > double prior_hessian::AMHCopula< Ndim >::llh (const Vec & u) const
Definition at line 210 of file AMHCopula.h.
References prior_hessian::AMHCopula< Ndim >::d1_igen(), prior_hessian::AMHCopula< Ndim >::ddim_gen(), and prior_hessian::AMHCopula< Ndim >::igen_sum().
Referenced by prior_hessian::AMHCopula< Ndim >::set_params_iter().
template<int Ndim> static constexpr IdxT prior_hessian::AMHCopula< Ndim >::num_dim () inline static
Definition at line 30 of file AMHCopula.h.
Referenced by prior_hessian::AMHCopula< Ndim >::d1_igen(), and prior_hessian::AMHCopula< Ndim >::ddim_gen().
template<int Ndim> static constexpr IdxT prior_hessian::AMHCopula< Ndim >::num_params () inline static
Definition at line 29 of file AMHCopula.h.
template<int Ndim> bool prior_hessian::AMHCopula< Ndim >::operator!= (const AMHCopula< Ndim > & o) const inline
Definition at line 42 of file AMHCopula.h.
References prior_hessian::AMHCopula< Ndim >::theta().
template<int Ndim> bool prior_hessian::AMHCopula< Ndim >::operator== (const AMHCopula< Ndim > & o) const inline
Definition at line 41 of file AMHCopula.h.
References prior_hessian::AMHCopula< Ndim >::theta().
template<int Ndim> static double prior_hessian::AMHCopula< Ndim >::param_lbound () inline static
Definition at line 31 of file AMHCopula.h.
template<int Ndim> static const StringVecT& prior_hessian::AMHCopula< Ndim >::param_names () inline static
Definition at line 28 of file AMHCopula.h.
template<int Ndim> static double prior_hessian::AMHCopula< Ndim >::param_ubound () inline static
Definition at line 32 of file AMHCopula.h.
References prior_hessian::AMHCopula< Ndim >::check_theta().
template<int Ndim> template<class Vec > double prior_hessian::AMHCopula< Ndim >::pdf (const Vec & u) const
Definition at line 202 of file AMHCopula.h.
References prior_hessian::AMHCopula< Ndim >::theta().
Referenced by prior_hessian::AMHCopula< Ndim >::set_params_iter().
template<int Ndim> template<class Vec > double prior_hessian::AMHCopula< Ndim >::rllh (const Vec & u) const
Referenced by prior_hessian::AMHCopula< Ndim >::set_params_iter().
template<int Ndim> double prior_hessian::AMHCopula< Ndim >::rllh_const () const
Referenced by prior_hessian::AMHCopula< Ndim >::set_params_iter().
template<int Ndim> template<class Vec > static void prior_hessian::AMHCopula< Ndim >::rllh_d2theta_accumulate (double theta, const Vec & u, double & rllh, double & dtheta, double & d2theta) static
Referenced by prior_hessian::AMHCopula< Ndim >::set_params_iter().
template<int Ndim> template<class Vec > static void prior_hessian::AMHCopula< Ndim >::rllh_dtheta_accumulate (double theta, const Vec & u, double & rllh, double & dtheta) static
Referenced by prior_hessian::AMHCopula< Ndim >::set_params_iter().
template<int Ndim> template<class Vec , class Vec2 > void prior_hessian::AMHCopula< Ndim >::rllh_grad_accumulate (const Vec & u, double & rllh, Vec2 & grad) const
Referenced by prior_hessian::AMHCopula< Ndim >::set_params_iter().
template<int Ndim> template<class Vec , class Vec2 > void prior_hessian::AMHCopula< Ndim >::rllh_grad_grad2_accumulate (const Vec & u, double & rllh, Vec2 & grad, Vec2 & grad2) const
Referenced by prior_hessian::AMHCopula< Ndim >::set_params_iter().
template<int Ndim> template<class Vec , class Vec2 , class Mat > void prior_hessian::AMHCopula< Ndim >::rllh_grad_hess_accumulate (const Vec & u, double & rllh, Vec2 & grad, Mat & hess) const
Referenced by prior_hessian::AMHCopula< Ndim >::set_params_iter().
template<int Ndim> template<class RngT > AMHCopula< Ndim >::NdimVecT prior_hessian::AMHCopula< Ndim >::sample (RngT & rng) const
Definition at line 596 of file AMHCopula.h.
Referenced by prior_hessian::AMHCopula< Ndim >::set_params_iter().
template<int Ndim> template<class Vec > void prior_hessian::AMHCopula< Ndim >::set_params (const Vec & params) inline
Definition at line 47 of file AMHCopula.h.
References prior_hessian::AMHCopula< Ndim >::set_theta().
template<int Ndim> template<class IterT > void prior_hessian::AMHCopula< Ndim >::set_params_iter (IterT & params) inline
Definition at line 53 of file AMHCopula.h.
References prior_hessian::AMHCopula< Ndim >::cdf(), prior_hessian::AMHCopula< Ndim >::d1_igen(), prior_hessian::AMHCopula< Ndim >::ddim_gen(), prior_hessian::AMHCopula< Ndim >::gen(), prior_hessian::AMHCopula< Ndim >::grad(), prior_hessian::AMHCopula< Ndim >::grad2(), prior_hessian::AMHCopula< Ndim >::hess(), prior_hessian::AMHCopula< Ndim >::igen(), prior_hessian::AMHCopula< Ndim >::llh(), prior_hessian::AMHCopula< Ndim >::pdf(), prior_hessian::AMHCopula< Ndim >::rllh(), prior_hessian::AMHCopula< Ndim >::rllh_const(), prior_hessian::AMHCopula< Ndim >::rllh_d2theta_accumulate(), prior_hessian::AMHCopula< Ndim >::rllh_dtheta_accumulate(), prior_hessian::AMHCopula< Ndim >::rllh_grad_accumulate(), prior_hessian::AMHCopula< Ndim >::rllh_grad_grad2_accumulate(), prior_hessian::AMHCopula< Ndim >::rllh_grad_hess_accumulate(), prior_hessian::AMHCopula< Ndim >::sample(), and prior_hessian::AMHCopula< Ndim >::set_theta().
template<int Ndim> void prior_hessian::AMHCopula< Ndim >::set_theta (double val)
Definition at line 175 of file AMHCopula.h.
References prior_hessian::AMHCopula< Ndim >::check_theta().
Referenced by prior_hessian::AMHCopula< Ndim >::AMHCopula(), prior_hessian::AMHCopula< Ndim >::set_params(), prior_hessian::AMHCopula< Ndim >::set_params_iter(), and prior_hessian::AMHCopula< Ndim >::theta().
template<int Ndim> double prior_hessian::AMHCopula< Ndim >::theta () const inline
Definition at line 38 of file AMHCopula.h.
References prior_hessian::AMHCopula< Ndim >::set_theta().
Referenced by prior_hessian::AMHCopula< Ndim >::AMHCopula(), prior_hessian::AMHCopula< Ndim >::append_params(), prior_hessian::AMHCopula< Ndim >::cdf(), prior_hessian::AMHCopula< Ndim >::d1_igen(), prior_hessian::AMHCopula< Ndim >::grad(), prior_hessian::AMHCopula< Ndim >::grad2(), prior_hessian::AMHCopula< Ndim >::hess(), prior_hessian::AMHCopula< Ndim >::igen_sum(), prior_hessian::AMHCopula< Ndim >::operator!=(), prior_hessian::AMHCopula< Ndim >::operator==(), and prior_hessian::AMHCopula< Ndim >::pdf().
The documentation for this class was generated from the following file:
AMHCopula.h