PriorHessian: prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, MultivariateDist > > Class Template Reference
prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, MultivariateDist > > Class Template Reference
#include </home/travis/build/markjolah/PriorHessian/include/PriorHessian/CompositeDist.h>
Public Types
using ComponentDistT = Dist
Public Member Functions
ComponentDistAdaptor ()
ComponentDistAdaptor (Dist &&dist)
ComponentDistAdaptor (const Dist &dist)
template<class IterT >
void append_lbound (IterT &v) const
template<class IterT >
void append_ubound (IterT &v) const
template<class IterT >
void append_global_lbound (IterT &v) const
template<class IterT >
void append_global_ubound (IterT &v) const
template<class IterT >
void set_lbound_from_iter (IterT &v)
template<class IterT >
void set_ubound_from_iter (IterT &v)
template<class IterT >
void set_bounds_from_iter (IterT &lb_iter, IterT &ub_iter)
template<class IterT >
void append_params (IterT &v) const
template<class IterT >
void append_params_lbound (IterT &v) const
template<class IterT >
void append_params_ubound (IterT &v) const
template<class IterT >
void append_param_names (IterT &v) const
template<class IterT >
double cdf_from_iter (IterT &u) const
template<class IterT >
double pdf_from_iter (IterT &u) const
template<class IterT >
double llh_from_iter (IterT &u) const
template<class IterT >
double rllh_from_iter (IterT &u) const
void grad_accumulate_idx (const VecT &u, VecT &g, IdxT &k) const
void grad2_accumulate_idx (const VecT &u, VecT &g2, IdxT &k) const
void hess_accumulate_idx (const VecT &u, MatT &h, IdxT &k) const
void grad_grad2_accumulate_idx (const VecT &u, VecT &g, VecT &g2, IdxT &k) const
void grad_hess_accumulate_idx (const VecT &u, VecT &g, MatT &h, IdxT &k) const
template<class RngT , class IterT >
void append_sample (RngT &rng, IterT &v) const
Detailed Description
template<class Dist>
class prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, MultivariateDist > >
Definition at line 692 of file CompositeDist.h.
Member Typedef Documentation
template<class Dist > using prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, MultivariateDist > >::ComponentDistT = Dist
Definition at line 694 of file CompositeDist.h.
Constructor & Destructor Documentation
template<class Dist > prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, MultivariateDist > >::ComponentDistAdaptor () inline
Definition at line 695 of file CompositeDist.h.
template<class Dist > prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, MultivariateDist > >::ComponentDistAdaptor (Dist && dist) inline explicit
Definition at line 696 of file CompositeDist.h.
template<class Dist > prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, MultivariateDist > >::ComponentDistAdaptor (const Dist & dist) inline explicit
Definition at line 697 of file CompositeDist.h.
Member Function Documentation
template<class Dist > template<class IterT > void prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, MultivariateDist > >::append_global_lbound (IterT & v) const inline
Definition at line 705 of file CompositeDist.h.
References prior_hessian::CompositeDist::global_lbound().
template<class Dist > template<class IterT > void prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, MultivariateDist > >::append_global_ubound (IterT & v) const inline
Definition at line 708 of file CompositeDist.h.
References prior_hessian::CompositeDist::global_ubound().
template<class Dist > template<class IterT > void prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, MultivariateDist > >::append_lbound (IterT & v) const inline
Definition at line 699 of file CompositeDist.h.
References prior_hessian::CompositeDist::lbound().
template<class Dist > template<class IterT > void prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, MultivariateDist > >::append_param_names (IterT & v) const inline
Definition at line 746 of file CompositeDist.h.
References prior_hessian::CompositeDist::param_names().
template<class Dist > template<class IterT > void prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, MultivariateDist > >::append_params (IterT & v) const inline
Definition at line 737 of file CompositeDist.h.
References prior_hessian::CompositeDist::params().
template<class Dist > template<class IterT > void prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, MultivariateDist > >::append_params_lbound (IterT & v) const inline
Definition at line 740 of file CompositeDist.h.
template<class Dist > template<class IterT > void prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, MultivariateDist > >::append_params_ubound (IterT & v) const inline
Definition at line 743 of file CompositeDist.h.
template<class Dist > template<class RngT , class IterT > void prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, MultivariateDist > >::append_sample (RngT & rng, IterT & v) const inline
Definition at line 823 of file CompositeDist.h.
References prior_hessian::CompositeDist::sample().
template<class Dist > template<class IterT > void prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, MultivariateDist > >::append_ubound (IterT & v) const inline
Definition at line 702 of file CompositeDist.h.
References prior_hessian::CompositeDist::ubound().
template<class Dist > template<class IterT > double prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, MultivariateDist > >::cdf_from_iter (IterT & u) const inline
Definition at line 749 of file CompositeDist.h.
References prior_hessian::CompositeDist::cdf().
template<class Dist > void prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, MultivariateDist > >::grad2_accumulate_idx (const VecT & u, VecT & g2, IdxT & k) const inline
Definition at line 788 of file CompositeDist.h.
References prior_hessian::CompositeDist::grad2().
template<class Dist > void prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, MultivariateDist > >::grad_accumulate_idx (const VecT & u, VecT & g, IdxT & k) const inline
Definition at line 781 of file CompositeDist.h.
References prior_hessian::CompositeDist::grad().
template<class Dist > void prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, MultivariateDist > >::grad_grad2_accumulate_idx (const VecT & u, VecT & g, VecT & g2, IdxT & k) const inline
Definition at line 803 of file CompositeDist.h.
References prior_hessian::CompositeDist::grad(), and prior_hessian::CompositeDist::grad2().
template<class Dist > void prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, MultivariateDist > >::grad_hess_accumulate_idx (const VecT & u, VecT & g, MatT & h, IdxT & k) const inline
Definition at line 812 of file CompositeDist.h.
References prior_hessian::CompositeDist::grad(), and prior_hessian::CompositeDist::hess().
template<class Dist > void prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, MultivariateDist > >::hess_accumulate_idx (const VecT & u, MatT & h, IdxT & k) const inline
Definition at line 795 of file CompositeDist.h.
References prior_hessian::CompositeDist::hess().
template<class Dist > template<class IterT > double prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, MultivariateDist > >::llh_from_iter (IterT & u) const inline
Definition at line 765 of file CompositeDist.h.
References prior_hessian::CompositeDist::llh().
template<class Dist > template<class IterT > double prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, MultivariateDist > >::pdf_from_iter (IterT & u) const inline
Definition at line 757 of file CompositeDist.h.
References prior_hessian::CompositeDist::pdf().
template<class Dist > template<class IterT > double prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, MultivariateDist > >::rllh_from_iter (IterT & u) const inline
Definition at line 773 of file CompositeDist.h.
References prior_hessian::CompositeDist::rllh().
template<class Dist > template<class IterT > void prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, MultivariateDist > >::set_bounds_from_iter (IterT & lb_iter, IterT & ub_iter) inline
Definition at line 727 of file CompositeDist.h.
References prior_hessian::CompositeDist::set_bounds().
template<class Dist > template<class IterT > void prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, MultivariateDist > >::set_lbound_from_iter (IterT & v) inline
Definition at line 711 of file CompositeDist.h.
References prior_hessian::CompositeDist::set_lbound().
template<class Dist > template<class IterT > void prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, MultivariateDist > >::set_ubound_from_iter (IterT & v) inline
Definition at line 719 of file CompositeDist.h.
References prior_hessian::CompositeDist::set_ubound().
The documentation for this class was generated from the following file:
CompositeDist.h