PriorHessian: prior_hessian::ParetoDist Class Reference
prior_hessian::ParetoDist Class Reference
Pareto dist with infinite upper bound.
#include </home/travis/build/markjolah/PriorHessian/include/PriorHessian/ParetoDist.h>
Public Types
using NparamsVecT = arma::Col< double >::fixed< _num_params >
Public Member Functions
bool in_bounds (double u) const
ParetoDist ()
ParetoDist (double min, double alpha)
template<class Vec , meta::ConstructableIfNotSelfT< Vec, ParetoDist > = true>
ParetoDist (const Vec &params)
double get_param (int idx) const
void set_param (int idx, double val)
NparamsVecT params () const
void set_params (double min, double alpha)
template<class Vec >
void set_params (const Vec &p)
bool operator== (const ParetoDist &o) const
bool operator!= (const ParetoDist &o) const
double alpha () const
double min () const
void set_min (double val)
void set_alpha (double val)
double lbound () const
void set_lbound (double lbound)
double mean () const
double median () const
double cdf (double x) const
double icdf (double u) const
double pdf (double x) const
double llh (double x) const
double rllh (double x) const
double grad (double x) const
double grad2 (double x) const
void grad_grad2_accumulate (double x, double &g, double &g2) const
template<class RngT >
double sample (RngT &rng) const
template<class IterT >
void set_params_iter (IterT &params)
Static Public Member Functions
static constexpr IdxT num_params ()
static constexpr double global_lbound ()
static constexpr double ubound ()
static const StringVecT & param_names ()
static const NparamsVecT & param_lbound ()
static const NparamsVecT & param_ubound ()
static bool check_params (double min, double alpha)
template<class Vec >
static bool check_params (const Vec &params)
static bool check_lbound (double min)
template<class IterT >
static bool check_params_iter (IterT &params)
static constexpr IdxT num_dim ()
Static Protected Member Functions
static void check_bounds (double lbound, double ubound)
Detailed Description
Pareto dist with infinite upper bound.
Definition at line 20 of file ParetoDist.h.
Member Typedef Documentation
using prior_hessian::ParetoDist::NparamsVecT = arma::Col<double>::fixed<_num_params>
Definition at line 24 of file ParetoDist.h.
Constructor & Destructor Documentation
prior_hessian::ParetoDist::ParetoDist () inline
Definition at line 41 of file ParetoDist.h.
prior_hessian::ParetoDist::ParetoDist (double min, double alpha)
Definition at line 21 of file ParetoDist.cpp.
template<class Vec , meta::ConstructableIfNotSelfT< Vec, ParetoDist > = true> prior_hessian::ParetoDist::ParetoDist (const Vec & params) inline explicit
Definition at line 44 of file ParetoDist.h.
References get_param(), and set_param().
Member Function Documentation
double prior_hessian::ParetoDist::alpha () const inline
Definition at line 55 of file ParetoDist.h.
Referenced by cdf(), grad(), grad2(), grad_grad2_accumulate(), icdf(), llh(), median(), operator==(), param_ubound(), params(), rllh(), and set_params_iter().
double prior_hessian::ParetoDist::cdf (double x) const inline
Definition at line 155 of file ParetoDist.h.
References alpha(), and lbound().
Referenced by lbound().
void prior_hessian::UnivariateDist::check_bounds (double lbound, double ubound) static protected inherited
Definition at line 17 of file UnivariateDist.cpp.
Referenced by prior_hessian::UnivariateDist::UnivariateDist().
bool prior_hessian::ParetoDist::check_lbound (double min) inline static
Definition at line 149 of file ParetoDist.h.
Referenced by check_params().
bool prior_hessian::ParetoDist::check_params (double min, double alpha) inline static
Definition at line 104 of file ParetoDist.h.
Referenced by check_params_iter(), and param_ubound().
template<class Vec > static bool prior_hessian::ParetoDist::check_params (const Vec & params) inline static
Definition at line 38 of file ParetoDist.h.
References check_lbound(), check_params(), and params().
Referenced by check_params().
template<class IterT > bool prior_hessian::ParetoDist::check_params_iter (IterT & params) static
Definition at line 111 of file ParetoDist.h.
References check_params().
Referenced by lbound().
double prior_hessian::ParetoDist::get_param (int idx) const inline
Definition at line 119 of file ParetoDist.h.
References lbound().
Referenced by ParetoDist().
static constexpr double prior_hessian::ParetoDist::global_lbound () inline static
Definition at line 26 of file ParetoDist.h.
double prior_hessian::ParetoDist::grad (double x) const inline
Definition at line 179 of file ParetoDist.h.
References alpha().
Referenced by lbound().
double prior_hessian::ParetoDist::grad2 (double x) const inline
Definition at line 185 of file ParetoDist.h.
References alpha().
Referenced by lbound().
void prior_hessian::ParetoDist::grad_grad2_accumulate (double x, double & g, double & g2) const inline
Definition at line 191 of file ParetoDist.h.
References alpha().
Referenced by lbound().
double prior_hessian::ParetoDist::icdf (double u) const inline
Definition at line 161 of file ParetoDist.h.
References alpha(), and lbound().
Referenced by lbound().
bool prior_hessian::ParetoDist::in_bounds (double u) const inline
Definition at line 28 of file ParetoDist.h.
References lbound(), and ubound().
double prior_hessian::ParetoDist::lbound () const inline
Definition at line 60 of file ParetoDist.h.
References cdf(), check_params_iter(), grad(), grad2(), grad_grad2_accumulate(), icdf(), llh(), mean(), median(), params(), pdf(), rllh(), sample(), set_lbound(), and set_params_iter().
Referenced by cdf(), get_param(), icdf(), in_bounds(), llh(), mean(), median(), params(), pdf(), and sample().
double prior_hessian::ParetoDist::llh (double x) const
Definition at line 64 of file ParetoDist.cpp.
References alpha(), lbound(), and rllh().
Referenced by lbound().
double prior_hessian::ParetoDist::mean () const
Definition at line 54 of file ParetoDist.cpp.
References lbound().
Referenced by lbound().
double prior_hessian::ParetoDist::median () const
Definition at line 59 of file ParetoDist.cpp.
References alpha(), and lbound().
Referenced by lbound().
double prior_hessian::ParetoDist::min () const inline
Definition at line 56 of file ParetoDist.h.
References set_alpha(), and set_min().
Referenced by operator==(), param_ubound(), and set_params_iter().
static constexpr IdxT prior_hessian::UnivariateDist::num_dim () inline static inherited
Definition at line 17 of file UnivariateDist.h.
static constexpr IdxT prior_hessian::ParetoDist::num_params () inline static
Definition at line 25 of file ParetoDist.h.
bool prior_hessian::ParetoDist::operator!= (const ParetoDist & o) const inline
Definition at line 53 of file ParetoDist.h.
References operator==().
bool prior_hessian::ParetoDist::operator== (const ParetoDist & o) const inline
Definition at line 52 of file ParetoDist.h.
References alpha(), and min().
Referenced by operator!=().
static const NparamsVecT& prior_hessian::ParetoDist::param_lbound () inline static
Definition at line 32 of file ParetoDist.h.
static const StringVecT& prior_hessian::ParetoDist::param_names () inline static
Definition at line 31 of file ParetoDist.h.
static const NparamsVecT& prior_hessian::ParetoDist::param_ubound () inline static
Definition at line 33 of file ParetoDist.h.
References alpha(), check_params(), and min().
NparamsVecT prior_hessian::ParetoDist::params () const inline
Definition at line 48 of file ParetoDist.h.
References alpha(), lbound(), and set_params().
Referenced by check_params(), and lbound().
double prior_hessian::ParetoDist::pdf (double x) const inline
Definition at line 167 of file ParetoDist.h.
References lbound().
Referenced by lbound().
double prior_hessian::ParetoDist::rllh (double x) const inline
Definition at line 173 of file ParetoDist.h.
References alpha().
Referenced by lbound(), and llh().
template<class RngT > double prior_hessian::ParetoDist::sample (RngT & rng) const
Definition at line 200 of file ParetoDist.h.
References lbound().
Referenced by lbound().
void prior_hessian::ParetoDist::set_alpha (double val)
Definition at line 35 of file ParetoDist.cpp.
Referenced by min(), and set_param().
void prior_hessian::ParetoDist::set_lbound (double lbound)
Definition at line 48 of file ParetoDist.cpp.
Referenced by lbound().
void prior_hessian::ParetoDist::set_min (double val)
Definition at line 29 of file ParetoDist.cpp.
Referenced by min(), and set_param().
void prior_hessian::ParetoDist::set_param (int idx, double val) inline
Definition at line 133 of file ParetoDist.h.
References set_alpha(), and set_min().
Referenced by ParetoDist().
void prior_hessian::ParetoDist::set_params (double min, double alpha)
Definition at line 41 of file ParetoDist.cpp.
Referenced by params(), and set_params_iter().
template<class Vec > void prior_hessian::ParetoDist::set_params (const Vec & p) inline
Definition at line 51 of file ParetoDist.h.
References set_params().
Referenced by set_params().
template<class IterT > void prior_hessian::ParetoDist::set_params_iter (IterT & params)
Definition at line 208 of file ParetoDist.h.
References alpha(), min(), and set_params().
Referenced by lbound().
static constexpr double prior_hessian::ParetoDist::ubound () inline static
Definition at line 27 of file ParetoDist.h.
Referenced by in_bounds().
The documentation for this class was generated from the following files:
ParetoDist.h
ParetoDist.cpp