PriorHessian: prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, UnivariateDist > > Class Template Reference
prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, UnivariateDist > > Class Template Reference
#include </home/travis/build/markjolah/PriorHessian/include/PriorHessian/CompositeDist.h>
Public Types
using ComponentDistT = Dist
Public Member Functions
ComponentDistAdaptor ()
ComponentDistAdaptor (Dist &&dist)
ComponentDistAdaptor (const Dist &dist)
template<class IterT >
void append_lbound (IterT &v) const
template<class IterT >
void append_ubound (IterT &v) const
template<class IterT >
void append_global_lbound (IterT &v) const
template<class IterT >
void append_global_ubound (IterT &v) const
template<class IterT >
void set_lbound_from_iter (IterT &lbounds)
template<class IterT >
void set_ubound_from_iter (IterT &ubounds)
template<class IterT >
void set_bounds_from_iter (IterT &lbounds, IterT &ubounds)
template<class IterT >
void append_params (IterT &v) const
template<class IterT >
void append_params_lbound (IterT &v) const
template<class IterT >
void append_params_ubound (IterT &v) const
template<class IterT >
void append_param_names (IterT &v) const
template<class IterT >
double cdf_from_iter (IterT &u) const
template<class IterT >
double pdf_from_iter (IterT &u) const
template<class IterT >
double llh_from_iter (IterT &u) const
template<class IterT >
double rllh_from_iter (IterT &u) const
void grad_accumulate_idx (const VecT &u, VecT &g, IdxT &k) const
void grad2_accumulate_idx (const VecT &u, VecT &g2, IdxT &k) const
void hess_accumulate_idx (const VecT &u, MatT &h, IdxT &k) const
void grad_grad2_accumulate_idx (const VecT &u, VecT &g, VecT &g2, IdxT &k) const
void grad_hess_accumulate_idx (const VecT &u, VecT &g, MatT &h, IdxT &k) const
template<class RngT , class IterT >
void append_sample (RngT &rng, IterT &iter) const
Detailed Description
template<class Dist>
class prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, UnivariateDist > >
Definition at line 622 of file CompositeDist.h.
Member Typedef Documentation
template<class Dist > using prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, UnivariateDist > >::ComponentDistT = Dist
Definition at line 624 of file CompositeDist.h.
Constructor & Destructor Documentation
template<class Dist > prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, UnivariateDist > >::ComponentDistAdaptor () inline
Definition at line 625 of file CompositeDist.h.
template<class Dist > prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, UnivariateDist > >::ComponentDistAdaptor (Dist && dist) inline explicit
Definition at line 626 of file CompositeDist.h.
template<class Dist > prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, UnivariateDist > >::ComponentDistAdaptor (const Dist & dist) inline explicit
Definition at line 627 of file CompositeDist.h.
Member Function Documentation
template<class Dist > template<class IterT > void prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, UnivariateDist > >::append_global_lbound (IterT & v) const inline
Definition at line 631 of file CompositeDist.h.
References prior_hessian::CompositeDist::lbound().
template<class Dist > template<class IterT > void prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, UnivariateDist > >::append_global_ubound (IterT & v) const inline
Definition at line 632 of file CompositeDist.h.
References prior_hessian::CompositeDist::ubound().
template<class Dist > template<class IterT > void prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, UnivariateDist > >::append_lbound (IterT & v) const inline
Definition at line 629 of file CompositeDist.h.
References prior_hessian::CompositeDist::lbound().
template<class Dist > template<class IterT > void prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, UnivariateDist > >::append_param_names (IterT & v) const inline
Definition at line 648 of file CompositeDist.h.
References prior_hessian::CompositeDist::param_names().
template<class Dist > template<class IterT > void prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, UnivariateDist > >::append_params (IterT & v) const inline
Definition at line 639 of file CompositeDist.h.
References prior_hessian::CompositeDist::params().
template<class Dist > template<class IterT > void prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, UnivariateDist > >::append_params_lbound (IterT & v) const inline
Definition at line 642 of file CompositeDist.h.
template<class Dist > template<class IterT > void prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, UnivariateDist > >::append_params_ubound (IterT & v) const inline
Definition at line 645 of file CompositeDist.h.
template<class Dist > template<class RngT , class IterT > void prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, UnivariateDist > >::append_sample (RngT & rng, IterT & iter) const inline
Definition at line 687 of file CompositeDist.h.
References prior_hessian::CompositeDist::sample().
template<class Dist > template<class IterT > void prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, UnivariateDist > >::append_ubound (IterT & v) const inline
Definition at line 630 of file CompositeDist.h.
References prior_hessian::CompositeDist::ubound().
template<class Dist > template<class IterT > double prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, UnivariateDist > >::cdf_from_iter (IterT & u) const inline
Definition at line 651 of file CompositeDist.h.
References prior_hessian::CompositeDist::cdf().
template<class Dist > void prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, UnivariateDist > >::grad2_accumulate_idx (const VecT & u, VecT & g2, IdxT & k) const inline
Definition at line 662 of file CompositeDist.h.
References prior_hessian::CompositeDist::grad2().
template<class Dist > void prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, UnivariateDist > >::grad_accumulate_idx (const VecT & u, VecT & g, IdxT & k) const inline
Definition at line 656 of file CompositeDist.h.
References prior_hessian::CompositeDist::grad().
template<class Dist > void prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, UnivariateDist > >::grad_grad2_accumulate_idx (const VecT & u, VecT & g, VecT & g2, IdxT & k) const inline
Definition at line 674 of file CompositeDist.h.
References prior_hessian::CompositeDist::grad_grad2_accumulate().
template<class Dist > void prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, UnivariateDist > >::grad_hess_accumulate_idx (const VecT & u, VecT & g, MatT & h, IdxT & k) const inline
Definition at line 680 of file CompositeDist.h.
References prior_hessian::CompositeDist::grad_grad2_accumulate().
template<class Dist > void prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, UnivariateDist > >::hess_accumulate_idx (const VecT & u, MatT & h, IdxT & k) const inline
Definition at line 668 of file CompositeDist.h.
References prior_hessian::CompositeDist::grad2().
template<class Dist > template<class IterT > double prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, UnivariateDist > >::llh_from_iter (IterT & u) const inline
Definition at line 653 of file CompositeDist.h.
References prior_hessian::CompositeDist::llh().
template<class Dist > template<class IterT > double prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, UnivariateDist > >::pdf_from_iter (IterT & u) const inline
Definition at line 652 of file CompositeDist.h.
References prior_hessian::CompositeDist::pdf().
template<class Dist > template<class IterT > double prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, UnivariateDist > >::rllh_from_iter (IterT & u) const inline
Definition at line 654 of file CompositeDist.h.
References prior_hessian::CompositeDist::rllh().
template<class Dist > template<class IterT > void prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, UnivariateDist > >::set_bounds_from_iter (IterT & lbounds, IterT & ubounds) inline
Definition at line 636 of file CompositeDist.h.
References prior_hessian::CompositeDist::set_bounds().
template<class Dist > template<class IterT > void prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, UnivariateDist > >::set_lbound_from_iter (IterT & lbounds) inline
Definition at line 633 of file CompositeDist.h.
References prior_hessian::CompositeDist::set_lbound().
template<class Dist > template<class IterT > void prior_hessian::CompositeDist::ComponentDistAdaptor< Dist, meta::EnableIfSubclassT< Dist, UnivariateDist > >::set_ubound_from_iter (IterT & ubounds) inline
Definition at line 634 of file CompositeDist.h.
References prior_hessian::CompositeDist::set_ubound().
The documentation for this class was generated from the following file:
CompositeDist.h