PriorHessian: prior_hessian::NormalDist Class Reference
prior_hessian::NormalDist Class Reference
Normal distribution with truncation.
#include </home/travis/build/markjolah/PriorHessian/include/PriorHessian/NormalDist.h>
Public Types
using NparamsVecT = arma::Col< double >::fixed< _num_params >
Public Member Functions
NormalDist (double mu, double sigma)
NormalDist ()
template<class Vec , meta::ConstructableIfNotSelfT< Vec, NormalDist > = true>
NormalDist (const Vec &params)
double mu () const
double sigma () const
void set_mu (double val)
void set_sigma (double val)
bool operator== (const NormalDist &o) const
bool operator!= (const NormalDist &o) const
double get_param (int idx) const
void set_param (int idx, double val)
NparamsVecT params () const
void set_params (double mu, double sigma)
template<class Vec >
void set_params (const Vec &p)
double mean () const
double median () const
double cdf (double x) const
double icdf (double u) const
double pdf (double x) const
double llh (double x) const
double rllh (double x) const
double grad (double x) const
double grad2 (double x) const
void grad_grad2_accumulate (double x, double &g, double &g2) const
template<class RngT >
double sample (RngT &rng) const
template<class IterT >
void append_params_iter (IterT &params) const
template<class IterT >
void set_params_iter (IterT &params)
Static Public Member Functions
static constexpr IdxT num_params ()
static constexpr double lbound ()
static constexpr double ubound ()
static bool in_bounds (double u)
static const StringVecT & param_names ()
static const NparamsVecT & param_lbound ()
static const NparamsVecT & param_ubound ()
static bool check_params (double mu, double sigma)
template<class Vec >
static bool check_params (const Vec &p)
template<class IterT >
static bool check_params_iter (IterT &params)
static constexpr IdxT num_dim ()
Static Protected Member Functions
static void check_bounds (double lbound, double ubound)
Detailed Description
Normal distribution with truncation.
Definition at line 21 of file NormalDist.h.
Member Typedef Documentation
using prior_hessian::NormalDist::NparamsVecT = arma::Col<double>::fixed<_num_params>
Definition at line 25 of file NormalDist.h.
Constructor & Destructor Documentation
prior_hessian::NormalDist::NormalDist (double mu, double sigma)
Definition at line 27 of file NormalDist.cpp.
References set_params().
prior_hessian::NormalDist::NormalDist () inline
Definition at line 43 of file NormalDist.h.
Referenced by check_params().
template<class Vec , meta::ConstructableIfNotSelfT< Vec, NormalDist > = true> prior_hessian::NormalDist::NormalDist (const Vec & params) inline explicit
Definition at line 45 of file NormalDist.h.
Member Function Documentation
template<class IterT > void prior_hessian::NormalDist::append_params_iter (IterT & params) const
Definition at line 205 of file NormalDist.h.
References mu(), and sigma().
Referenced by median().
double prior_hessian::NormalDist::cdf (double x) const
Definition at line 42 of file NormalDist.cpp.
References prior_hessian::constants::sqrt2_inv.
Referenced by median().
void prior_hessian::UnivariateDist::check_bounds (double lbound, double ubound) static protected inherited
Definition at line 22 of file UnivariateDist.cpp.
Referenced by prior_hessian::UnivariateDist::UnivariateDist().
bool prior_hessian::NormalDist::check_params (double mu, double sigma) inline static
Definition at line 121 of file NormalDist.h.
Referenced by check_params_iter(), and param_ubound().
template<class Vec > static bool prior_hessian::NormalDist::check_params (const Vec & p) inline static
Definition at line 39 of file NormalDist.h.
References check_params(), and NormalDist().
Referenced by check_params().
template<class IterT > bool prior_hessian::NormalDist::check_params_iter (IterT & params) static
Definition at line 197 of file NormalDist.h.
References check_params(), mu(), and sigma().
Referenced by median().
double prior_hessian::NormalDist::get_param (int idx) const inline
Definition at line 127 of file NormalDist.h.
References mu(), and sigma().
Referenced by operator!=().
double prior_hessian::NormalDist::grad (double x) const inline
Definition at line 168 of file NormalDist.h.
References prior_hessian::square().
Referenced by median().
double prior_hessian::NormalDist::grad2 (double x) const inline
Definition at line 174 of file NormalDist.h.
References prior_hessian::square().
Referenced by median().
void prior_hessian::NormalDist::grad_grad2_accumulate (double x, double & g, double & g2) const inline
Definition at line 180 of file NormalDist.h.
References prior_hessian::square().
Referenced by median().
double prior_hessian::NormalDist::icdf (double u) const
Definition at line 47 of file NormalDist.cpp.
References mu(), sigma(), and prior_hessian::constants::sqrt2.
Referenced by median().
static bool prior_hessian::NormalDist::in_bounds (double u) inline static
Definition at line 31 of file NormalDist.h.
References lbound(), and ubound().
static constexpr double prior_hessian::NormalDist::lbound () inline static
Definition at line 29 of file NormalDist.h.
Referenced by in_bounds().
double prior_hessian::NormalDist::llh (double x) const
Definition at line 72 of file NormalDist.cpp.
References prior_hessian::constants::log2pi, rllh(), and sigma().
Referenced by median().
double prior_hessian::NormalDist::mean () const inline
Definition at line 62 of file NormalDist.h.
References mu().
double prior_hessian::NormalDist::median () const inline
Definition at line 63 of file NormalDist.h.
References append_params_iter(), cdf(), check_params_iter(), grad(), grad2(), grad_grad2_accumulate(), icdf(), llh(), mu(), params(), pdf(), rllh(), sample(), and set_params_iter().
double prior_hessian::NormalDist::mu () const inline
Definition at line 48 of file NormalDist.h.
Referenced by append_params_iter(), check_params_iter(), get_param(), icdf(), mean(), median(), operator==(), param_ubound(), params(), sample(), and set_params_iter().
static constexpr IdxT prior_hessian::UnivariateDist::num_dim () inline static inherited
Definition at line 17 of file UnivariateDist.h.
static constexpr IdxT prior_hessian::NormalDist::num_params () inline static
Definition at line 28 of file NormalDist.h.
bool prior_hessian::NormalDist::operator!= (const NormalDist & o) const inline
Definition at line 53 of file NormalDist.h.
References get_param(), operator==(), and set_param().
bool prior_hessian::NormalDist::operator== (const NormalDist & o) const inline
Definition at line 52 of file NormalDist.h.
References mu(), and sigma().
Referenced by operator!=().
static const NparamsVecT& prior_hessian::NormalDist::param_lbound () inline static
Definition at line 34 of file NormalDist.h.
static const StringVecT& prior_hessian::NormalDist::param_names () inline static
Definition at line 33 of file NormalDist.h.
static const NparamsVecT& prior_hessian::NormalDist::param_ubound () inline static
Definition at line 35 of file NormalDist.h.
References check_params(), mu(), and sigma().
NparamsVecT prior_hessian::NormalDist::params () const inline
Definition at line 57 of file NormalDist.h.
References mu(), set_params(), and sigma().
Referenced by median().
double prior_hessian::NormalDist::pdf (double x) const inline
Definition at line 156 of file NormalDist.h.
References prior_hessian::constants::sqrt2pi_inv, and prior_hessian::square().
Referenced by median().
double prior_hessian::NormalDist::rllh (double x) const inline
Definition at line 162 of file NormalDist.h.
References prior_hessian::square().
Referenced by llh(), and median().
template<class RngT > double prior_hessian::NormalDist::sample (RngT & rng) const
Definition at line 188 of file NormalDist.h.
References mu(), and sigma().
Referenced by median().
void prior_hessian::NormalDist::set_mu (double val) inline
Definition at line 110 of file NormalDist.h.
Referenced by set_param(), set_params(), and sigma().
void prior_hessian::NormalDist::set_param (int idx, double val) inline
Definition at line 141 of file NormalDist.h.
References set_mu(), and set_sigma().
Referenced by operator!=().
void prior_hessian::NormalDist::set_params (double mu, double sigma) inline
Definition at line 114 of file NormalDist.h.
References set_mu(), and set_sigma().
Referenced by NormalDist(), params(), and set_params_iter().
template<class Vec > void prior_hessian::NormalDist::set_params (const Vec & p) inline
Definition at line 60 of file NormalDist.h.
References set_params().
Referenced by set_params().
template<class IterT > void prior_hessian::NormalDist::set_params_iter (IterT & params)
Definition at line 213 of file NormalDist.h.
References mu(), set_params(), and sigma().
Referenced by median().
void prior_hessian::NormalDist::set_sigma (double val)
Definition at line 35 of file NormalDist.cpp.
Referenced by set_param(), set_params(), and sigma().
double prior_hessian::NormalDist::sigma () const inline
Definition at line 49 of file NormalDist.h.
References set_mu(), and set_sigma().
Referenced by append_params_iter(), check_params_iter(), get_param(), icdf(), llh(), operator==(), param_ubound(), params(), sample(), and set_params_iter().
static constexpr double prior_hessian::NormalDist::ubound () inline static
Definition at line 30 of file NormalDist.h.
Referenced by in_bounds().
The documentation for this class was generated from the following files:
NormalDist.h
NormalDist.cpp