PriorHessian: prior_hessian::SymmetricBetaDist Class Reference
prior_hessian::SymmetricBetaDist Class Reference
Single parameter beta distribution where = , leading to symmetric bounded distribution.
#include </home/travis/build/markjolah/PriorHessian/include/PriorHessian/SymmetricBetaDist.h>
Public Types
using NparamsVecT = arma::Col< double >::fixed< _num_params >
Public Member Functions
SymmetricBetaDist ()
SymmetricBetaDist (double beta)
template<class Vec , meta::ConstructableIfNotSelfT< Vec, SymmetricBetaDist > = true>
SymmetricBetaDist (const Vec &params)
double beta () const
void set_beta (double val)
double get_param (int idx) const
void set_param (int idx, double val)
NparamsVecT params () const
void set_params (double beta)
template<class Vec >
void set_params (const Vec &p)
bool operator== (const SymmetricBetaDist &o) const
bool operator!= (const SymmetricBetaDist &o) const
double mean () const
double median () const
double cdf (double x) const
double icdf (double u) const
double pdf (double x) const
double llh (double x) const
double rllh (double x) const
double grad (double x) const
double grad2 (double x) const
void grad_grad2_accumulate (double x, double &g, double &g2) const
template<class RngT >
double sample (RngT &rng) const
template<class IterT >
void set_params_iter (IterT &params)
Static Public Member Functions
static constexpr IdxT num_params ()
static constexpr double lbound ()
static constexpr double ubound ()
static bool in_bounds (double u)
static const StringVecT & param_names ()
static const VecT & param_lbound ()
static const VecT & param_ubound ()
static bool check_params (double beta)
template<class Vec >
static bool check_params (Vec &p)
template<class IterT >
static bool check_params_iter (IterT &params)
static constexpr IdxT num_dim ()
Static Protected Member Functions
static void check_bounds (double lbound, double ubound)
Detailed Description
Single parameter beta distribution where = , leading to symmetric bounded distribution.
Definition at line 22 of file SymmetricBetaDist.h.
Member Typedef Documentation
using prior_hessian::SymmetricBetaDist::NparamsVecT = arma::Col<double>::fixed<_num_params>
Definition at line 26 of file SymmetricBetaDist.h.
Constructor & Destructor Documentation
prior_hessian::SymmetricBetaDist::SymmetricBetaDist () inline
Definition at line 42 of file SymmetricBetaDist.h.
prior_hessian::SymmetricBetaDist::SymmetricBetaDist (double beta) explicit
Definition at line 23 of file SymmetricBetaDist.cpp.
template<class Vec , meta::ConstructableIfNotSelfT< Vec, SymmetricBetaDist > = true> prior_hessian::SymmetricBetaDist::SymmetricBetaDist (const Vec & params) inline explicit
Definition at line 45 of file SymmetricBetaDist.h.
Member Function Documentation
double prior_hessian::SymmetricBetaDist::beta () const inline
Definition at line 47 of file SymmetricBetaDist.h.
References get_param(), set_beta(), and set_param().
Referenced by llh(), operator==(), param_ubound(), and params().
double prior_hessian::SymmetricBetaDist::cdf (double x) const
Definition at line 36 of file SymmetricBetaDist.cpp.
Referenced by median().
void prior_hessian::UnivariateDist::check_bounds (double lbound, double ubound) static protected inherited
Definition at line 22 of file UnivariateDist.cpp.
Referenced by prior_hessian::UnivariateDist::UnivariateDist().
bool prior_hessian::SymmetricBetaDist::check_params (double beta) inline static
Definition at line 101 of file SymmetricBetaDist.h.
Referenced by check_params_iter(), and param_ubound().
template<class Vec > static bool prior_hessian::SymmetricBetaDist::check_params (Vec & p) inline static
Definition at line 40 of file SymmetricBetaDist.h.
References check_params().
Referenced by check_params().
template<class IterT > bool prior_hessian::SymmetricBetaDist::check_params_iter (IterT & params) static
Definition at line 167 of file SymmetricBetaDist.h.
References check_params().
Referenced by median().
double prior_hessian::SymmetricBetaDist::get_param (int idx) const inline
Definition at line 107 of file SymmetricBetaDist.h.
Referenced by beta().
double prior_hessian::SymmetricBetaDist::grad (double x) const inline
Definition at line 137 of file SymmetricBetaDist.h.
Referenced by median().
double prior_hessian::SymmetricBetaDist::grad2 (double x) const inline
Definition at line 143 of file SymmetricBetaDist.h.
References prior_hessian::square().
Referenced by median().
void prior_hessian::SymmetricBetaDist::grad_grad2_accumulate (double x, double & g, double & g2) const inline
Definition at line 149 of file SymmetricBetaDist.h.
Referenced by median().
double prior_hessian::SymmetricBetaDist::icdf (double u) const
Definition at line 43 of file SymmetricBetaDist.cpp.
Referenced by median(), and sample().
static bool prior_hessian::SymmetricBetaDist::in_bounds (double u) inline static
Definition at line 32 of file SymmetricBetaDist.h.
References lbound(), and ubound().
static constexpr double prior_hessian::SymmetricBetaDist::lbound () inline static
Definition at line 30 of file SymmetricBetaDist.h.
Referenced by in_bounds().
double prior_hessian::SymmetricBetaDist::llh (double x) const
Definition at line 55 of file SymmetricBetaDist.cpp.
References beta(), and rllh().
Referenced by median().
double prior_hessian::SymmetricBetaDist::mean () const inline
Definition at line 60 of file SymmetricBetaDist.h.
double prior_hessian::SymmetricBetaDist::median () const inline
Definition at line 61 of file SymmetricBetaDist.h.
References cdf(), check_params_iter(), grad(), grad2(), grad_grad2_accumulate(), icdf(), llh(), params(), pdf(), rllh(), sample(), and set_params_iter().
static constexpr IdxT prior_hessian::UnivariateDist::num_dim () inline static inherited
Definition at line 17 of file UnivariateDist.h.
static constexpr IdxT prior_hessian::SymmetricBetaDist::num_params () inline static
Definition at line 29 of file SymmetricBetaDist.h.
bool prior_hessian::SymmetricBetaDist::operator!= (const SymmetricBetaDist & o) const inline
Definition at line 58 of file SymmetricBetaDist.h.
References operator==().
bool prior_hessian::SymmetricBetaDist::operator== (const SymmetricBetaDist & o) const inline
Definition at line 57 of file SymmetricBetaDist.h.
References beta().
Referenced by operator!=().
static const VecT& prior_hessian::SymmetricBetaDist::param_lbound () inline static
Definition at line 35 of file SymmetricBetaDist.h.
static const StringVecT& prior_hessian::SymmetricBetaDist::param_names () inline static
Definition at line 34 of file SymmetricBetaDist.h.
static const VecT& prior_hessian::SymmetricBetaDist::param_ubound () inline static
Definition at line 36 of file SymmetricBetaDist.h.
References beta(), and check_params().
NparamsVecT prior_hessian::SymmetricBetaDist::params () const inline
Definition at line 52 of file SymmetricBetaDist.h.
References beta().
Referenced by median().
double prior_hessian::SymmetricBetaDist::pdf (double x) const
Definition at line 50 of file SymmetricBetaDist.cpp.
Referenced by median().
double prior_hessian::SymmetricBetaDist::rllh (double x) const inline
Definition at line 131 of file SymmetricBetaDist.h.
Referenced by llh(), and median().
template<class RngT > double prior_hessian::SymmetricBetaDist::sample (RngT & rng) const
Definition at line 159 of file SymmetricBetaDist.h.
References icdf().
Referenced by median().
void prior_hessian::SymmetricBetaDist::set_beta (double val)
Definition at line 30 of file SymmetricBetaDist.cpp.
Referenced by beta(), set_param(), and set_params().
void prior_hessian::SymmetricBetaDist::set_param (int idx, double val) inline
Definition at line 119 of file SymmetricBetaDist.h.
References set_beta().
Referenced by beta().
void prior_hessian::SymmetricBetaDist::set_params (double beta) inline
Definition at line 53 of file SymmetricBetaDist.h.
References set_beta().
Referenced by set_params_iter().
template<class Vec > void prior_hessian::SymmetricBetaDist::set_params (const Vec & p) inline
Definition at line 56 of file SymmetricBetaDist.h.
References set_beta().
template<class IterT > void prior_hessian::SymmetricBetaDist::set_params_iter (IterT & params)
Definition at line 173 of file SymmetricBetaDist.h.
References set_params().
Referenced by median().
static constexpr double prior_hessian::SymmetricBetaDist::ubound () inline static
Definition at line 31 of file SymmetricBetaDist.h.
Referenced by in_bounds().
The documentation for this class was generated from the following files:
SymmetricBetaDist.h
SymmetricBetaDist.cpp