PriorHessian: prior_hessian::polylog Namespace Reference
prior_hessian::polylog Namespace Reference
Functions
template<int n>
double eulerian_polynomial (double z)
template<>
double eulerian_polynomial< 0 > (double)
template<>
double eulerian_polynomial< 1 > (double z)
template<>
double eulerian_polynomial< 2 > (double z)
template<>
double eulerian_polynomial< 3 > (double z)
template<>
double eulerian_polynomial< 4 > (double z)
template<>
double eulerian_polynomial< 5 > (double z)
template<>
double eulerian_polynomial< 6 > (double z)
template<>
double eulerian_polynomial< 7 > (double z)
template<>
double eulerian_polynomial< 8 > (double z)
template<>
double eulerian_polynomial< 9 > (double z)
template<int n>
double polylog (double z)
template<>
double polylog< 1 > (double z)
Function Documentation
template<int n> double prior_hessian::polylog::eulerian_polynomial (double z)
template<> double prior_hessian::polylog::eulerian_polynomial< 0 > (double)
Definition at line 17 of file PolyLog.h.
template<> double prior_hessian::polylog::eulerian_polynomial< 1 > (double z)
Definition at line 23 of file PolyLog.h.
template<> double prior_hessian::polylog::eulerian_polynomial< 2 > (double z)
Definition at line 29 of file PolyLog.h.
template<> double prior_hessian::polylog::eulerian_polynomial< 3 > (double z)
Definition at line 35 of file PolyLog.h.
template<> double prior_hessian::polylog::eulerian_polynomial< 4 > (double z)
Definition at line 41 of file PolyLog.h.
template<> double prior_hessian::polylog::eulerian_polynomial< 5 > (double z)
Definition at line 47 of file PolyLog.h.
template<> double prior_hessian::polylog::eulerian_polynomial< 6 > (double z)
Definition at line 53 of file PolyLog.h.
template<> double prior_hessian::polylog::eulerian_polynomial< 7 > (double z)
Definition at line 59 of file PolyLog.h.
template<> double prior_hessian::polylog::eulerian_polynomial< 8 > (double z)
Definition at line 65 of file PolyLog.h.
template<> double prior_hessian::polylog::eulerian_polynomial< 9 > (double z)
Definition at line 70 of file PolyLog.h.
References polylog().
template<int n> double prior_hessian::polylog::polylog (double z)
Referenced by prior_hessian::AMHCopula< Ndim >::d1_igen(), prior_hessian::AMHCopula< Ndim >::ddim_gen(), eulerian_polynomial< 9 >(), and polylog< 1 >().
template<> double prior_hessian::polylog::polylog< 1 > (double z)
Definition at line 120 of file PolyLog.h.
References polylog().