PriorHessian: prior_hessian::constants Namespace Reference
prior_hessian::constants Namespace Reference
Variables
const double sqrt2 = std::sqrt(2.)
const double sqrt2_inv = 1./std::sqrt(2.)
const double sqrt2pi = std::sqrt(2.*arma::datum::pi)
const double sqrt2pi_inv = 1./std::sqrt(2.*arma::datum::pi)
const double log2pi = std::log(2.*arma::datum::pi)
Variable Documentation
const double prior_hessian::constants::log2pi = std::log(2.*arma::datum::pi)
Definition at line 16 of file util.cpp.
Referenced by prior_hessian::NormalDist::llh(), and prior_hessian::MultivariateNormalDist< Ndim >::sample().
const double prior_hessian::constants::sqrt2 = std::sqrt(2.)
Definition at line 12 of file util.cpp.
Referenced by prior_hessian::NormalDist::icdf(), and prior_hessian::unit_normal_icdf().
const double prior_hessian::constants::sqrt2_inv = 1./std::sqrt(2.)
Definition at line 13 of file util.cpp.
Referenced by prior_hessian::NormalDist::cdf().
const double prior_hessian::constants::sqrt2pi = std::sqrt(2.*arma::datum::pi)
Definition at line 14 of file util.cpp.
const double prior_hessian::constants::sqrt2pi_inv = 1./std::sqrt(2.*arma::datum::pi)
Definition at line 15 of file util.cpp.
Referenced by prior_hessian::NormalDist::pdf().