PriorHessian: prior_hessian::detail Namespace Reference
prior_hessian::detail Namespace Reference
Classes
class dist_adaptor_traits
struct dist_adaptor_traits< CopulaDistImpl::CopulaDist< CopulaTemplate, DistTs... > >
struct dist_adaptor_traits< GammaDist >
struct dist_adaptor_traits< MultivariateNormalDist< Ndim > >
struct dist_adaptor_traits< NormalDist >
struct dist_adaptor_traits< ParetoDist >
struct dist_adaptor_traits< ScaledSymmetricBetaDist >
struct dist_adaptor_traits< SymmetricBetaDist >
struct dist_adaptor_traits< TruncatedGammaDist >
struct dist_adaptor_traits< TruncatedMultivariateNormalDist< Ndim > >
struct dist_adaptor_traits< TruncatedNormalDist >
struct dist_adaptor_traits< TruncatedParetoDist >
Typedefs
template<class DistT >
using DistTraitsT = detail::dist_adaptor_traits< std::decay_t< DistT >>
Functions
template<class... Ts, std::size_t... I>
std::tuple< BoundsAdaptedDistT< Ts >... > make_adapted_bounded_dist_tuple (std::tuple< Ts... > &&dists, std::index_sequence< I... >)
template<class... Ts, std::size_t... I>
std::tuple< BoundsAdaptedDistT< Ts >... > make_adapted_bounded_dist_tuple (const std::tuple< Ts... > &dists, std::index_sequence< I... >)
template<long N, long... I>
VecT eulerian_polynomial ()
Typedef Documentation
template<class DistT > using prior_hessian::detail::DistTraitsT = typedef detail::dist_adaptor_traits<std::decay_t<DistT>>
Type traits class for distribution type DistT.
The traits class describes the Adaptor classes applicable to each individual distribution
Definition at line 52 of file BoundsAdaptedDist.h.
Function Documentation
template<long N, long... I> VecT prior_hessian::detail::eulerian_polynomial ()
Definition at line 26 of file EulerianPolynomial.h.
template<class... Ts, std::size_t... I> std::tuple<BoundsAdaptedDistT<Ts>...> prior_hessian::detail::make_adapted_bounded_dist_tuple (std::tuple< Ts... > && dists, std::index_sequence< I... >)
Definition at line 66 of file BoundsAdaptedDist.h.
References prior_hessian::make_adapted_bounded_dist().
Referenced by prior_hessian::make_adapted_bounded_dist_tuple().
template<class... Ts, std::size_t... I> std::tuple<BoundsAdaptedDistT<Ts>...> prior_hessian::detail::make_adapted_bounded_dist_tuple (const std::tuple< Ts... > & dists, std::index_sequence< I... >)
Definition at line 73 of file BoundsAdaptedDist.h.
References prior_hessian::make_adapted_bounded_dist().