PriorHessian: prior_hessian::meta Namespace Reference
prior_hessian::meta Namespace Reference
Class templates to utilize sequencing behaviour of std::initializer_list expressions.
Classes
struct all_dists_are_bounded
struct conjunction
struct conjunction< B1 >
struct conjunction< B1, Bn... >
struct disjunction
struct disjunction< B1 >
struct disjunction< B1, Bn... >
class is_copula
struct is_numeric_template_of
struct is_numeric_template_of< ClassNumericTemplate, ClassNumericTemplate< Is... > >
class is_subclass_of_numeric_template
struct is_template_of
struct is_template_of< ClassTemplate, ClassTemplate< Ts... > >
Typedefs
template<class... DistTs>
using ConstructableIfAllDistsAreBoundedT = std::enable_if< all_dists_are_bounded< DistTs... >::value, bool >
template<class... DistTs>
using ConstructableIfNotAllDistsAreBoundedT = std::enable_if<!all_dists_are_bounded< DistTs... >::value, bool >
template<template< template< int > class, class... > class CopulaT, class U >
using ConstructableIfIsCopulaT = std::enable_if_t< is_copula< CopulaT, U >::value,bool >
template<class ReturnT , class BoolT >
using ReturnIfT = std::enable_if_t< BoolT::value, ReturnT >
template<bool val>
using ConstructableIf = std::enable_if_t< val, bool >
template<bool val>
using ConstructableIfNot = std::enable_if_t<!val, bool >
template<class T , class SelfT >
using ConstructableIfNotSelfT = std::enable_if_t<!std::is_same< std::decay_t< T >, SelfT >::value, bool >
template<class T , class BaseT >
using EnableIfSubclassT = std::enable_if_t< std::is_base_of< std::remove_reference_t< BaseT >, std::remove_reference_t< T >>::value >
template<class T , template< int > class ClassNumericTemplate>
using EnableIfSubclassOfNumericTemplateT = std::enable_if_t< is_subclass_of_numeric_template< ClassNumericTemplate, std::remove_reference_t< T >>::value >
template<class ReturnT , class T , template< int > class ClassNumericTemplate>
using ReturnIfSubclassOfNumericTemplateT = std::enable_if_t< is_subclass_of_numeric_template< ClassNumericTemplate, std::remove_reference_t< T >>::value, ReturnT >
template<class T , class SelfT >
using EnableIfNotIsSelfT = std::enable_if_t< !std::is_same< std::decay_t< T >, SelfT >::value >
template<class ReturnT , class T , class BaseT >
using ReturnIfSubclassT = std::enable_if_t< std::is_base_of< std::remove_reference_t< BaseT >, std::remove_reference_t< T >>::value, ReturnT >
template<class BaseT , class... Ts>
using EnableIfIsSuperclassOfAllT = std::enable_if_t< conjunction< std::is_base_of< std::remove_reference_t< BaseT >, std::remove_reference_t< Ts >>... >::value >
template<class T , template< typename... > class ClassTemplate>
using EnableIfInstantiatedFromT = std::enable_if_t< is_template_of< ClassTemplate, std::remove_reference_t< T >>::value >
template<class T , template< int > class ClassTemplate>
using EnableIfInstantiatedFromNumericT = std::enable_if_t< is_numeric_template_of< ClassTemplate, std::remove_reference_t< T >>::value >
template<class ReturnT , class T , template< int > class ClassTemplate>
using ReturnIfInstantiatedFromNumericT = std::enable_if_t< is_numeric_template_of< ClassTemplate, std::remove_reference_t< T >>::value, ReturnT >
template<class T , template< typename... > class ClassTemplate>
using EnableIfNotInstantiatedFromT = std::enable_if_t< !is_template_of< ClassTemplate, std::remove_reference_t< T >>::value >
template<class ReturnT , class TestT , template< typename... > class ClassTemplate>
using ReturnIfInstantiatedFromT = std::enable_if_t< is_template_of< ClassTemplate, std::remove_reference_t< TestT >>::value, ReturnT >
template<class ReturnT , class TestT , template< typename... > class ClassTemplate>
using ReturnIfNotInstantiatedFromT = std::enable_if_t< !is_template_of< ClassTemplate, std::remove_reference_t< TestT >>::value, ReturnT >
template<template< typename > class ClassTemplate, class... Ts>
using EnableIfIsTemplateForAllT = std::enable_if_t< conjunction< is_template_of< ClassTemplate, std::remove_reference_t< Ts >>... >::value >
template<template< typename... > class ClassTemplate, class... Ts>
using ConstructableIfIsTemplateForAllT = std::enable_if_t< conjunction< is_template_of< ClassTemplate, std::remove_reference_t< Ts >>... >::value, bool >
template<class SuperClass , class T >
using ConstructableIfIsSuperClassT = std::enable_if_t< std::is_base_of< std::remove_reference_t< SuperClass >, std::remove_reference_t< T >>::value, bool >
template<class SuperClass , class... Ts>
using ConstructableIfIsSuperClassForAllT = std::enable_if_t< conjunction< std::is_base_of< std::remove_reference_t< SuperClass >, std::remove_reference_t< Ts >>... >::value, bool >
template<class T , template< int > class ClassTemplate>
using ConstructableIfInstantiatedFromNumericT = std::enable_if_t< is_numeric_template_of< ClassTemplate, std::remove_reference_t< T >>::value, bool >
template<class T >
using EnableIfIsNotTupleT = std::enable_if_t< !is_template_of< std::tuple, std::remove_reference_t< T >>::value >
template<class... Ts>
using EnableIfNonEmpty = std::enable_if_t< (sizeof...(Ts)>0) >
template<class... Ts>
using EnableIfAllAreNotTupleT = std::enable_if_t< !disjunction< is_template_of< std::tuple, std::remove_reference_t< Ts >>... >::value >
template<class SelfT , class T >
using EnableIfIsNotTupleAndIsNotSelfT = std::enable_if_t< !is_template_of< std::tuple, std::remove_reference_t< T >>::value &&!std::is_same< std::decay_t< T >, SelfT >::value >
template<class T , class... Ts>
using ConstructableIfAllAreNotTupleAndAreNotT = std::enable_if_t< !disjunction< is_template_of< std::tuple, std::remove_reference_t< Ts >>... >::value &&!disjunction< std::is_same< std::decay_t< Ts >, T >... >::value, bool >
template<class Dist , class BaseDist >
using DerivedFrom = std::enable_if_t< std::is_base_of< std::decay_t< BaseDist >, std::decay_t< Dist >>::value, std::decay_t< Dist >>
Functions
template<class T >
void call_in_order (std::initializer_list< T >)
template<class InputIterator , class ResultT , class BinaryOperation >
PRIOR_HESSIAN_META_CONSTEXPR ResultT constexpr_accumulate (InputIterator first, InputIterator last, ResultT init, BinaryOperation op)
PRIOR_HESSIAN_META_CONSTEXPR bool logical_and_in_order (std::initializer_list< bool > L)
template<class T >
PRIOR_HESSIAN_META_CONSTEXPR T sum_in_order (std::initializer_list< T > L)
template<class T >
PRIOR_HESSIAN_META_CONSTEXPR T prod_in_order (std::initializer_list< T > L)
Detailed Description
Class templates to utilize sequencing behaviour of std::initializer_list expressions.
These class templates are intended to be used in variadic template functions to sequence the order of calls as a std::initializer_list.
Typedef Documentation
template<bool val> using prior_hessian::meta::ConstructableIf = typedef std::enable_if_t<val,bool>
Definition at line 117 of file Meta.h.
template<class T , class... Ts> using prior_hessian::meta::ConstructableIfAllAreNotTupleAndAreNotT = typedef std::enable_if_t< !disjunction<is_template_of<std::tuple,std::remove_reference_t<Ts>>...>::value && !disjunction<std::is_same<std::decay_t<Ts>,T>...>::value, bool>
Definition at line 214 of file Meta.h.
template<class... DistTs> using prior_hessian::meta::ConstructableIfAllDistsAreBoundedT = typedef std::enable_if<all_dists_are_bounded<DistTs...>::value,bool>
Definition at line 87 of file BoundsAdaptedDist.h.
template<class T , template< int > class ClassTemplate> using prior_hessian::meta::ConstructableIfInstantiatedFromNumericT = typedef std::enable_if_t< is_numeric_template_of<ClassTemplate, std::remove_reference_t<T>>::value, bool >
Definition at line 194 of file Meta.h.
template<template< template< int > class, class... > class CopulaT, class U > using prior_hessian::meta::ConstructableIfIsCopulaT = typedef std::enable_if_t<is_copula<CopulaT,U>::value ,bool>
Definition at line 111 of file Meta.h.
template<class SuperClass , class... Ts> using prior_hessian::meta::ConstructableIfIsSuperClassForAllT = typedef std::enable_if_t< conjunction< std::is_base_of<std::remove_reference_t<SuperClass>,std::remove_reference_t<Ts>>... >::value, bool>
Definition at line 190 of file Meta.h.
template<class SuperClass , class T > using prior_hessian::meta::ConstructableIfIsSuperClassT = typedef std::enable_if_t< std::is_base_of<std::remove_reference_t<SuperClass>,std::remove_reference_t<T>>::value, bool>
Definition at line 186 of file Meta.h.
template<template< typename... > class ClassTemplate, class... Ts> using prior_hessian::meta::ConstructableIfIsTemplateForAllT = typedef std::enable_if_t< conjunction< is_template_of<ClassTemplate,std::remove_reference_t<Ts>> ... >::value, bool>
Definition at line 182 of file Meta.h.
template<bool val> using prior_hessian::meta::ConstructableIfNot = typedef std::enable_if_t<!val,bool>
Definition at line 120 of file Meta.h.
template<class... DistTs> using prior_hessian::meta::ConstructableIfNotAllDistsAreBoundedT = typedef std::enable_if<!all_dists_are_bounded<DistTs...>::value,bool>
Definition at line 89 of file BoundsAdaptedDist.h.
template<class T , class SelfT > using prior_hessian::meta::ConstructableIfNotSelfT = typedef std::enable_if_t<!std::is_same<std::decay_t<T>,SelfT>::value,bool>
Definition at line 123 of file Meta.h.
template<class Dist , class BaseDist > using prior_hessian::meta::DerivedFrom = typedef std::enable_if_t<std::is_base_of<std::decay_t<BaseDist>,std::decay_t<Dist>>::value,std::decay_t<Dist>>
Definition at line 228 of file Meta.h.
template<class... Ts> using prior_hessian::meta::EnableIfAllAreNotTupleT = typedef std::enable_if_t< !disjunction< is_template_of<std::tuple,std::remove_reference_t<Ts>>... >::value >
Definition at line 204 of file Meta.h.
template<class T , template< int > class ClassTemplate> using prior_hessian::meta::EnableIfInstantiatedFromNumericT = typedef std::enable_if_t< is_numeric_template_of<ClassTemplate, std::remove_reference_t<T>>::value>
Definition at line 158 of file Meta.h.
template<class T , template< typename... > class ClassTemplate> using prior_hessian::meta::EnableIfInstantiatedFromT = typedef std::enable_if_t< is_template_of<ClassTemplate, std::remove_reference_t<T>>::value >
Definition at line 150 of file Meta.h.
template<class SelfT , class T > using prior_hessian::meta::EnableIfIsNotTupleAndIsNotSelfT = typedef std::enable_if_t< !is_template_of<std::tuple,std::remove_reference_t<T>>::value && !std::is_same<std::decay_t<T>,SelfT>::value >
Definition at line 209 of file Meta.h.
template<class T > using prior_hessian::meta::EnableIfIsNotTupleT = typedef std::enable_if_t< !is_template_of<std::tuple,std::remove_reference_t<T>>::value >
Definition at line 197 of file Meta.h.
template<class BaseT , class... Ts> using prior_hessian::meta::EnableIfIsSuperclassOfAllT = typedef std::enable_if_t<conjunction< std::is_base_of<std::remove_reference_t<BaseT>,std::remove_reference_t<Ts>> ... >::value >
Definition at line 146 of file Meta.h.
template<template< typename > class ClassTemplate, class... Ts> using prior_hessian::meta::EnableIfIsTemplateForAllT = typedef std::enable_if_t< conjunction< is_template_of<ClassTemplate,std::remove_reference_t<Ts>> ... >::value >
Definition at line 178 of file Meta.h.
template<class... Ts> using prior_hessian::meta::EnableIfNonEmpty = typedef std::enable_if_t< (sizeof...(Ts)>0) >
Definition at line 200 of file Meta.h.
template<class T , template< typename... > class ClassTemplate> using prior_hessian::meta::EnableIfNotInstantiatedFromT = typedef std::enable_if_t< !is_template_of<ClassTemplate, std::remove_reference_t<T>>::value >
Definition at line 166 of file Meta.h.
template<class T , class SelfT > using prior_hessian::meta::EnableIfNotIsSelfT = typedef std::enable_if_t< !std::is_same<std::decay_t<T>,SelfT>::value >
Definition at line 138 of file Meta.h.
template<class T , template< int > class ClassNumericTemplate> using prior_hessian::meta::EnableIfSubclassOfNumericTemplateT = typedef std::enable_if_t< is_subclass_of_numeric_template<ClassNumericTemplate, std::remove_reference_t<T>>::value>
Definition at line 131 of file Meta.h.
template<class T , class BaseT > using prior_hessian::meta::EnableIfSubclassT = typedef std::enable_if_t< std::is_base_of<std::remove_reference_t<BaseT>,std::remove_reference_t<T>>::value>
Definition at line 127 of file Meta.h.
template<class ReturnT , class T , template< int > class ClassTemplate> using prior_hessian::meta::ReturnIfInstantiatedFromNumericT = typedef std::enable_if_t< is_numeric_template_of<ClassTemplate, std::remove_reference_t<T>>::value, ReturnT>
Definition at line 162 of file Meta.h.
template<class ReturnT , class TestT , template< typename... > class ClassTemplate> using prior_hessian::meta::ReturnIfInstantiatedFromT = typedef std::enable_if_t< is_template_of<ClassTemplate, std::remove_reference_t<TestT>>::value, ReturnT>
Definition at line 170 of file Meta.h.
template<class ReturnT , class TestT , template< typename... > class ClassTemplate> using prior_hessian::meta::ReturnIfNotInstantiatedFromT = typedef std::enable_if_t< !is_template_of<ClassTemplate, std::remove_reference_t<TestT>>::value, ReturnT>
Definition at line 174 of file Meta.h.
template<class ReturnT , class T , template< int > class ClassNumericTemplate> using prior_hessian::meta::ReturnIfSubclassOfNumericTemplateT = typedef std::enable_if_t< is_subclass_of_numeric_template<ClassNumericTemplate, std::remove_reference_t<T>>::value, ReturnT>
Definition at line 135 of file Meta.h.
template<class ReturnT , class T , class BaseT > using prior_hessian::meta::ReturnIfSubclassT = typedef std::enable_if_t< std::is_base_of<std::remove_reference_t<BaseT>,std::remove_reference_t<T>>::value, ReturnT>
Definition at line 142 of file Meta.h.
template<class ReturnT , class BoolT > using prior_hessian::meta::ReturnIfT = typedef std::enable_if_t<BoolT::value,ReturnT>
Definition at line 114 of file Meta.h.
Function Documentation
template<class T > void prior_hessian::meta::call_in_order (std::initializer_list< T >)
NOOP function which is used to ensure call order on a variadic sequence of function calls
Definition at line 41 of file Meta.h.
References PRIOR_HESSIAN_META_CONSTEXPR.
Referenced by prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::global_ubound(), and prior_hessian::CompositeDist::rllh_components().
template<class InputIterator , class ResultT , class BinaryOperation > PRIOR_HESSIAN_META_CONSTEXPR ResultT prior_hessian::meta::constexpr_accumulate (InputIterator first, InputIterator last, ResultT init, BinaryOperation op)
Definition at line 46 of file Meta.h.
References PRIOR_HESSIAN_META_CONSTEXPR.
Referenced by logical_and_in_order(), prod_in_order(), and sum_in_order().
PRIOR_HESSIAN_META_CONSTEXPR bool prior_hessian::meta::logical_and_in_order (std::initializer_list< bool > L) inline
Definition at line 53 of file Meta.h.
References constexpr_accumulate(), and PRIOR_HESSIAN_META_CONSTEXPR.
Referenced by prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::global_ubound(), and prior_hessian::CompositeDist::rllh_components().
template<class T > PRIOR_HESSIAN_META_CONSTEXPR T prior_hessian::meta::prod_in_order (std::initializer_list< T > L)
Definition at line 63 of file Meta.h.
References constexpr_accumulate().
Referenced by prior_hessian::CompositeDist::rllh_components().
template<class T > PRIOR_HESSIAN_META_CONSTEXPR T prior_hessian::meta::sum_in_order (std::initializer_list< T > L)
Definition at line 58 of file Meta.h.
References constexpr_accumulate(), and PRIOR_HESSIAN_META_CONSTEXPR.
Referenced by prior_hessian::CompositeDist::make_component_dist_tuple(), prior_hessian::CopulaDistImpl::CopulaDist< CopulaTemplate, MarginalDistTs >::operator!=(), and prior_hessian::CompositeDist::rllh_components().