PriorHessian: prior_hessian Namespace Reference
prior_hessian Namespace Reference
Namespaces
constants
CopulaDistImpl
detail
genz
helpers
mcmc
meta
Class templates to utilize sequencing behavior of std::initializer_list expressions.
polylog
Classes
class AMHCopula
class ArchimedeanCopula
class BaseDist
class CompositeDist
A probability distribution made of independent component distributions composing groups of 1 or more variables.
struct eulerian_number
struct eulerian_number< 0, M >
class GammaDist
Gamma distribution.
struct IndexError
Indicates a index access was out of bounds.
struct InvalidOperationError
class MultivariateDist
class MultivariateNormalDist
Multivariate Normal distribution.
class NormalDist
Normal distribution with truncation.
struct NotImplementedError
struct NumericalOverflowError
struct ParameterNameError
struct ParameterNameUniquenessError
struct ParameterSizeError
struct ParameterValueError
class ParetoDist
Pareto dist with infinite upper bound.
class PriorHessianError
struct RuntimeConvergenceError
struct RuntimeSamplingError
struct RuntimeTypeError
class ScaledDist
class SymmetricBetaDist
Single parameter beta distribution where , leading to symmetric bounded distribution.
class TruncatedDist
class TruncatedMultivariateDist
class UnivariateDist
class UpperTruncatedDist
Typedefs
template<class DistT >
using BoundsAdaptedDistT = typename detail::dist_adaptor_traits< std::decay_t< DistT >>::bounds_adapted_dist
template<template< int > class CopulaTemplate, class... MarginalDistTs>
using CopulaDist = CopulaDistImpl::CopulaDist< CopulaTemplate, BoundsAdaptedDistT< MarginalDistTs >... >
using ScaledSymmetricBetaDist = ScaledDist< SymmetricBetaDist >
using TruncatedGammaDist = TruncatedDist< GammaDist >
template<IdxT Ndim>
using TruncatedMultivariateNormalDist = TruncatedMultivariateDist< MultivariateNormalDist< Ndim >>
using TruncatedNormalDist = TruncatedDist< NormalDist >
using TruncatedParetoDist = UpperTruncatedDist< ParetoDist >
using IdxT = arma::uword
using UVecT = arma::Col< IdxT >
using VecT = arma::Col< double >
using MatT = arma::Mat< double >
using StringVecT = std::vector< std::string >
using TypeInfoVecT = std::vector< std::type_index >
Functions
std::ostream & operator<< (std::ostream &out, const CompositeDist &comp_dist)
double unit_normal_cdf (double t)
double unit_normal_icdf (double u)
double bounded (double x)
double owen_t_integral (double h, double a, double gh)
double owen_b_integral (double h, double k, double r)
double donnelly_bvn_integral (double ah, double ak, double r)
double donnelly_bvn_integral_orig (double ah, double ak, double r)
template<class Dist , typename = meta::EnableIfIsNotTupleT<Dist>>
std::enable_if_t< detail::DistTraitsT< Dist >::adaptable_bounds, Dist > make_adapted_bounded_dist (Dist &&dist)
template<class Dist , typename = meta::EnableIfIsNotTupleT<Dist>>
std::enable_if_t< !detail::DistTraitsT< Dist >::adaptable_bounds, BoundsAdaptedDistT< Dist > > make_adapted_bounded_dist (Dist &&dist)
template<class Dist , class Vec , typename = meta::EnableIfIsNotTupleT<Dist>>
std::enable_if_t< detail::DistTraitsT< Dist >::adaptable_bounds, Dist > make_adapted_bounded_dist (Dist &&dist, Vec &&lbound, Vec &&ubound)
template<class Dist , class Vec , typename = meta::EnableIfIsNotTupleT<Dist>>
std::enable_if_t<!detail::DistTraitsT< Dist >::adaptable_bounds, BoundsAdaptedDistT< Dist > > make_adapted_bounded_dist (Dist &&dist, Vec &&lbound, Vec &&ubound)
template<class... Ts>
std::tuple< BoundsAdaptedDistT< Ts >... > make_adapted_bounded_dist_tuple (Ts &&...ts)
template<class... Ts>
std::tuple< BoundsAdaptedDistT< Ts >... > make_adapted_bounded_dist_tuple (std::tuple< Ts... > &&dists)
template<class... Ts>
std::tuple< BoundsAdaptedDistT< Ts >... > make_adapted_bounded_dist_tuple (const std::tuple< Ts... > &dists)
template<template< int > class CopulaTemplate, class... MarginalDistTs>
CopulaDist< CopulaTemplate, MarginalDistTs... > make_copula_dist (CopulaTemplate< sizeof...(MarginalDistTs)> &&copula, MarginalDistTs &&...dists)
template<long N>
VecT eulerian_polynomial ()
double owen_t_integral (double h, double a)
template<class Vec , class Mat >
double donnelly_bvn_cdf (const Vec &b, const Mat &sigma)
template<class Vec , class Mat >
double owen_bvn_cdf (const Vec &b, const Mat &sigma)
template<class Vec , class Mat >
double mc_mvn_integral (const Vec &a, const Vec &b, const Mat &U, double &error, int &niter)
template<class Vec , class Mat >
double mc_mvn_cdf_core (const Vec &b, const Mat &U, double &error, int &niter)
template<class Vec , class Mat >
double mc_mvn_cdf (const Vec &b, const Mat &S, double &error)
ScaledSymmetricBetaDist make_scaled_symmetric_beta_dist (double beta, std::pair< double, double > bounds)
TruncatedGammaDist make_bounded_gamma_dist (double scale, double shape, std::pair< double, double > bounds)
template<IdxT Ndim, class Vec , class Mat , class Vec2 >
TruncatedMultivariateNormalDist< Ndim > make_bounded_multivariate_normal_dist (Vec &&mu, Mat &&sigma, Vec2 &&lbound, Vec2 &&ubound)
TruncatedNormalDist make_bounded_normal_dist (double mu, double sigma, std::pair< double, double > bounds)
TruncatedParetoDist make_bounded_pareto_dist (double alpha, std::pair< double, double > bounds)
template<class T >
T square (T t)
Typedef Documentation
template<class DistT > using prior_hessian::BoundsAdaptedDistT = typedef typename detail::dist_adaptor_traits<std::decay_t<DistT>>::bounds_adapted_dist
The bounds-adapted distribution type for a given distribution type DistT This is the adapted version of the class, i.e., the class that allows truncation or scaling so that the lower and upper bounds are settable.
Definition at line 59 of file BoundsAdaptedDist.h.
template<template< int > class CopulaTemplate, class... MarginalDistTs> using prior_hessian::CopulaDist = typedef CopulaDistImpl::CopulaDist<CopulaTemplate, BoundsAdaptedDistT<MarginalDistTs>...>
Definition at line 182 of file CopulaDist.h.
using prior_hessian::IdxT = typedef arma::uword
Definition at line 28 of file util.h.
using prior_hessian::MatT = typedef arma::Mat<double>
Definition at line 31 of file util.h.
using prior_hessian::ScaledSymmetricBetaDist = typedef ScaledDist<SymmetricBetaDist>
Definition at line 15 of file ScaledSymmetricBetaDist.h.
using prior_hessian::StringVecT = typedef std::vector<std::string>
Definition at line 32 of file util.h.
using prior_hessian::TruncatedGammaDist = typedef TruncatedDist<GammaDist>
Definition at line 15 of file TruncatedGammaDist.h.
template<IdxT Ndim> using prior_hessian::TruncatedMultivariateNormalDist = typedef TruncatedMultivariateDist<MultivariateNormalDist<Ndim>>
Definition at line 18 of file TruncatedMultivariateNormalDist.h.
using prior_hessian::TruncatedNormalDist = typedef TruncatedDist<NormalDist>
Definition at line 17 of file TruncatedNormalDist.h.
using prior_hessian::TruncatedParetoDist = typedef UpperTruncatedDist<ParetoDist>
Definition at line 15 of file TruncatedParetoDist.h.
using prior_hessian::TypeInfoVecT = typedef std::vector<std::type_index>
Definition at line 33 of file util.h.
using prior_hessian::UVecT = typedef arma::Col<IdxT>
Definition at line 29 of file util.h.
using prior_hessian::VecT = typedef arma::Col<double>
Definition at line 30 of file util.h.
Function Documentation
double prior_hessian::bounded (double x)
Definition at line 42 of file mvn_cdf.cpp.
Referenced by donnelly_bvn_integral().
template<class Vec , class Mat > double prior_hessian::donnelly_bvn_cdf (const Vec & b, const Mat & sigma)
Definition at line 55 of file mvn_cdf.h.
References donnelly_bvn_integral().
double prior_hessian::donnelly_bvn_integral (double ah, double ak, double r)
compute the bivariate normal cdf integral computes the probability for two normal variates X and Y whose correlation is R, that AH <= X and AK <= Y.
Adapted to modern C++ with efficiency improvements by: Mark Olah (mjo@c.nosp@m.s.un.nosp@m.m DOT edu) 10/2018
Reference: Thomas Donnelly, Algorithm 462: Bivariate Normal Distribution, Communications of the ACM, October 1973, Volume 16, Number 10, page 638.
compute the upper-right tail of the bivariate normal distribution computes the probability for two normal variates X and Y whose correlation is R, that AH <= X and AK <= Y.
Adapted to modern C++ with efficiency improvements by: Mark Olah (mjo@c.nosp@m.s.un.nosp@m.m DOT edu) 10/2018
Reference: Thomas Donnelly, Algorithm 462: Bivariate Normal Distribution, Communications of the ACM, October 1973, Volume 16, Number 10, page 638.
Definition at line 158 of file mvn_cdf.cpp.
References bounded(), and unit_normal_cdf().
Referenced by donnelly_bvn_cdf(), and owen_t_integral().
double prior_hessian::donnelly_bvn_integral_orig (double ah, double ak, double r)
Definition at line 268 of file mvn_cdf.cpp.
References unit_normal_cdf().
Referenced by owen_t_integral().
template<long N> VecT prior_hessian::eulerian_polynomial ()
Definition at line 33 of file EulerianPolynomial.h.
template<class Dist , typename = meta::EnableIfIsNotTupleT<Dist>> std::enable_if_t< detail::DistTraitsT<Dist>::adaptable_bounds, Dist> prior_hessian::make_adapted_bounded_dist (Dist && dist)
make_adapted_bounded_dist() [4-forms] If the given distribution is not bounded then the appropriate bounding distribution is wrapped around it. We detect the boundedness of the distribution using detail::adaptable_bounds type-traits class. Can be replaced with constexpr if in c++17. Uses SFINAE in c++14.
Definition at line 99 of file BoundsAdaptedDist.h.
Referenced by prior_hessian::detail::make_adapted_bounded_dist_tuple(), make_adapted_bounded_dist_tuple(), prior_hessian::CompositeDist::make_component_dist(), prior_hessian::CompositeDist::make_component_dist_tuple(), and make_copula_dist().
template<class Dist , typename = meta::EnableIfIsNotTupleT<Dist>> std::enable_if_t< !detail::DistTraitsT<Dist>::adaptable_bounds, BoundsAdaptedDistT<Dist> > prior_hessian::make_adapted_bounded_dist (Dist && dist)
Definition at line 104 of file BoundsAdaptedDist.h.
template<class Dist , class Vec , typename = meta::EnableIfIsNotTupleT<Dist>> std::enable_if_t<detail::DistTraitsT<Dist>::adaptable_bounds, Dist> prior_hessian::make_adapted_bounded_dist (Dist && dist, Vec && lbound, Vec && ubound)
Definition at line 109 of file BoundsAdaptedDist.h.
template<class Dist , class Vec , typename = meta::EnableIfIsNotTupleT<Dist>> std::enable_if_t<!detail::DistTraitsT<Dist>::adaptable_bounds, BoundsAdaptedDistT<Dist> > prior_hessian::make_adapted_bounded_dist (Dist && dist, Vec && lbound, Vec && ubound)
Definition at line 117 of file BoundsAdaptedDist.h.
template<class... Ts> std::tuple<BoundsAdaptedDistT<Ts>...> prior_hessian::make_adapted_bounded_dist_tuple (Ts &&... ts)
Definition at line 132 of file BoundsAdaptedDist.h.
References make_adapted_bounded_dist().
template<class... Ts> std::tuple<BoundsAdaptedDistT<Ts>...> prior_hessian::make_adapted_bounded_dist_tuple (std::tuple< Ts... > && dists)
Definition at line 139 of file BoundsAdaptedDist.h.
References prior_hessian::detail::make_adapted_bounded_dist_tuple().
template<class... Ts> std::tuple<BoundsAdaptedDistT<Ts>...> prior_hessian::make_adapted_bounded_dist_tuple (const std::tuple< Ts... > & dists)
Definition at line 146 of file BoundsAdaptedDist.h.
References prior_hessian::detail::make_adapted_bounded_dist_tuple().
TruncatedGammaDist prior_hessian::make_bounded_gamma_dist (double scale, double shape, std::pair< double, double > bounds) inline
Definition at line 18 of file TruncatedGammaDist.h.
template<IdxT Ndim, class Vec , class Mat , class Vec2 > TruncatedMultivariateNormalDist<Ndim> prior_hessian::make_bounded_multivariate_normal_dist (Vec && mu, Mat && sigma, Vec2 && lbound, Vec2 && ubound)
Definition at line 22 of file TruncatedMultivariateNormalDist.h.
TruncatedNormalDist prior_hessian::make_bounded_normal_dist (double mu, double sigma, std::pair< double, double > bounds) inline
Definition at line 20 of file TruncatedNormalDist.h.
TruncatedParetoDist prior_hessian::make_bounded_pareto_dist (double alpha, std::pair< double, double > bounds) inline
Definition at line 18 of file TruncatedParetoDist.h.
template<template< int > class CopulaTemplate, class... MarginalDistTs> CopulaDist<CopulaTemplate,MarginalDistTs...> prior_hessian::make_copula_dist (CopulaTemplate< sizeof...(MarginalDistTs)> && copula, MarginalDistTs &&... dists)
Definition at line 187 of file CopulaDist.h.
References make_adapted_bounded_dist().
ScaledSymmetricBetaDist prior_hessian::make_scaled_symmetric_beta_dist (double beta, std::pair< double, double > bounds) inline
Definition at line 18 of file ScaledSymmetricBetaDist.h.
template<class Vec , class Mat > double prior_hessian::mc_mvn_cdf (const Vec & b, const Mat & S, double & error)
Definition at line 169 of file mvn_cdf.h.
References mc_mvn_cdf_core().
template<class Vec , class Mat > double prior_hessian::mc_mvn_cdf_core (const Vec & b, const Mat & U, double & error, int & niter)
For the cdf a=-Infinity, so d=0.
Definition at line 130 of file mvn_cdf.h.
References unit_normal_cdf(), and unit_normal_icdf().
Referenced by mc_mvn_cdf().
template<class Vec , class Mat > double prior_hessian::mc_mvn_integral (const Vec & a, const Vec & b, const Mat & U, double & error, int & niter)
compute the multivariate normal cdf integral
Definition at line 81 of file mvn_cdf.h.
References unit_normal_cdf(), and unit_normal_icdf().
std::ostream & prior_hessian::operator<< (std::ostream & out, const CompositeDist & comp_dist)
Definition at line 80 of file CompositeDist.cpp.
References prior_hessian::CompositeDist::component_names(), prior_hessian::CompositeDist::dim_variables(), prior_hessian::CompositeDist::global_lbound(), prior_hessian::CompositeDist::global_ubound(), prior_hessian::CompositeDist::lbound(), prior_hessian::CompositeDist::num_components(), prior_hessian::CompositeDist::num_dim(), prior_hessian::CompositeDist::num_dim_components(), prior_hessian::CompositeDist::num_params(), prior_hessian::CompositeDist::num_params_components(), prior_hessian::CompositeDist::param_names(), prior_hessian::CompositeDist::params(), prior_hessian::CompositeDist::params_lbound(), prior_hessian::CompositeDist::params_ubound(), and prior_hessian::CompositeDist::ubound().
Referenced by prior_hessian::CompositeDist::set_param_names().
double prior_hessian::owen_b_integral (double h, double k, double r)
Definition at line 108 of file mvn_cdf.cpp.
References owen_t_integral(), and unit_normal_cdf().
Referenced by owen_bvn_cdf(), and owen_t_integral().
template<class Vec , class Mat > double prior_hessian::owen_bvn_cdf (const Vec & b, const Mat & sigma)
Definition at line 67 of file mvn_cdf.h.
References owen_b_integral().
Referenced by prior_hessian::MultivariateNormalDist< Ndim >::cdf().
double prior_hessian::owen_t_integral (double h, double a) inline
Definition at line 26 of file mvn_cdf.h.
References donnelly_bvn_integral(), donnelly_bvn_integral_orig(), owen_b_integral(), owen_t_integral(), and unit_normal_cdf().
double prior_hessian::owen_t_integral (double h, double a, double gh)
Definition at line 54 of file mvn_cdf.cpp.
References unit_normal_cdf().
Referenced by owen_b_integral(), and owen_t_integral().
template<class T > T prior_hessian::square (T t)
Definition at line 44 of file util.h.
Referenced by prior_hessian::helpers::compute_quadratic_from_symmetric(), prior_hessian::NormalDist::grad(), prior_hessian::SymmetricBetaDist::grad2(), prior_hessian::NormalDist::grad2(), prior_hessian::AMHCopula< Ndim >::grad2(), prior_hessian::NormalDist::grad_grad2_accumulate(), prior_hessian::AMHCopula< Ndim >::hess(), prior_hessian::NormalDist::pdf(), and prior_hessian::NormalDist::rllh().
double prior_hessian::unit_normal_cdf (double t)
area of the lower tail of the unit normal curve below t.
Definition at line 28 of file mvn_cdf.cpp.
Referenced by donnelly_bvn_integral(), donnelly_bvn_integral_orig(), mc_mvn_cdf_core(), mc_mvn_integral(), owen_b_integral(), and owen_t_integral().
double prior_hessian::unit_normal_icdf (double u)
Definition at line 35 of file mvn_cdf.cpp.
References prior_hessian::constants::sqrt2.
Referenced by mc_mvn_cdf_core(), and mc_mvn_integral().